//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdMoGoAdNetworkAdapter.h"

#import "DMSplashAdControllerDelegate.h"

@class DMSplashAdController;

__attribute__((visibility("hidden")))
@interface AdMoGoAdapterDoMobSplash : AdMoGoAdNetworkAdapter <DMSplashAdControllerDelegate>
{
    DMSplashAdController *_splashAd;
    BOOL isFail;
    BOOL isSuccess;
}

+ (void)load;
+ (int)networkType;
- (void)dmSplashAdDidDismissScreen:(id)arg1;
- (void)dmSplashAdWillPresentScreen:(id)arg1;
- (void)dmSplashAdFailToLoadAd:(id)arg1 withError:(id)arg2;
- (void)dmSplashAdSuccessToLoadAd:(id)arg1;
- (BOOL)isSupportSplashCache;
- (void)adFailWith:(id)arg1;
- (void)adSuccess:(id)arg1;
- (void)dealloc;
- (void)stopBeingDelegate;
- (void)getAd;

@end

