//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface AdMoGoS2SStatic : NSObject
{
    NSOperationQueue *requestQueue;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)singleton;
- (void)requestServerInThread:(id)arg1 andParams:(id)arg2 andHeader:(id)arg3 withRequestType:(id)arg4;
- (void)requestMoGoServerWithUrl:(id)arg1 andParams:(id)arg2 andHeader:(id)arg3 withRequestType:(id)arg4;
- (void)dealloc;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

