//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AdMoGoConfig : NSObject
{
    struct __CFRunLoop *runloopref;
    BOOL isExecuting;
    NSString *_notificationKey;
}

@property(nonatomic) NSString *notificationKey; // @synthesize notificationKey=_notificationKey;
- (void)dealloc;
- (void)stopGettingConfigData;
- (void)sendDbData:(id)arg1;
- (void)getAdMoGoConfigData:(id)arg1;

@end

