//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WBRequestDelegate.h"

@class NSString, WebRequest;

@interface AdWebRequest : NSObject <WBRequestDelegate>
{
    NSString *_domainURL;
    WebRequest *_webRequest;
}

@property(retain, nonatomic) WebRequest *webRequest; // @synthesize webRequest=_webRequest;
- (void)request:(id)arg1 didFinishLoadingWithResult:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)request:(id)arg1 didReceiveRawData:(id)arg2;
- (void)request:(id)arg1 didReceiveResponse:(id)arg2;
- (void)dealloc;
- (void)sendAdRequestWithDict:(id)arg1;

@end

