//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DMViewControllerHolder.h"

#import "DMURLDownloaderDelegate.h"
#import "PKAddPassesViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class DMURLDownloader, UIAlertView;

@interface DMAddPassesViewControllerHolder : DMViewControllerHolder <DMURLDownloaderDelegate, PKAddPassesViewControllerDelegate, UIAlertViewDelegate>
{
    DMURLDownloader *_passFileDownloader;
    UIAlertView *_alertView;
    CDUnknownBlockType _lifecycelBlock;
    BOOL _presentingWithError;
}

- (void)addPassesViewControllerDidFinish:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dmDownloader:(id)arg1 didFinished:(id)arg2;
- (void)dmDownloader:(id)arg1 receivedBytes:(long long)arg2 totalReceivedBytes:(long long)arg3 contentLength:(long long)arg4;
- (void)dmDownloader:(id)arg1 didFailWithError:(id)arg2;
- (void)dmDownloaderWillStart:(id)arg1;
- (void)presentWithLifecycelBlock:(CDUnknownBlockType)arg1;
- (void)whenViewControllerHolderFinished;
- (void)whenPresentingError:(id)arg1;
- (void)whenWillPresent;
- (void)dealloc;

@end

