//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DMRidModel : NSObject
{
    NSString *_rgid;
    double _expires;
    NSString *_rid;
    int _type;
    NSString *_rurl;
    NSString *_path;
    int _downState;
    double _contentlength;
    long _creatDate;
    NSString *_ppid;
    NSString *_pubid;
    NSString *_tracker;
    NSString *_eventTrackerUrl;
    int _width;
    int _height;
}

@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *eventTrackerUrl; // @synthesize eventTrackerUrl=_eventTrackerUrl;
@property(copy, nonatomic) NSString *tracker; // @synthesize tracker=_tracker;
@property(copy, nonatomic) NSString *pubid; // @synthesize pubid=_pubid;
@property(copy, nonatomic) NSString *ppid; // @synthesize ppid=_ppid;
@property(nonatomic) long creatDate; // @synthesize creatDate=_creatDate;
@property(nonatomic) double contentlength; // @synthesize contentlength=_contentlength;
@property(nonatomic) int downState; // @synthesize downState=_downState;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *rurl; // @synthesize rurl=_rurl;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *rid; // @synthesize rid=_rid;
@property(nonatomic) double expires; // @synthesize expires=_expires;
@property(copy, nonatomic) NSString *rgid; // @synthesize rgid=_rgid;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

