//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DMSqliteFreqManager : NSObject
{
    struct sqlite3 *db;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void)versionRecords;
- (void)alterTable;
- (void)dealloc;
- (void)PrintAllInDb;
- (BOOL)isHasInSqlWithFrequencyId:(id)arg1;
- (void)changeDataFromFreq:(id)arg1;
- (id)selectClickTimeWithFreqMax:(int)arg1;
- (id)selectImpTimeWithFreqMax:(int)arg1;
- (void)updateClickTimesWithFrenquencyId:(id)arg1 andTime:(double)arg2;
- (void)updateImpTimesWithFrenquencyId:(id)arg1 andTime:(double)arg2;
- (void)updateFrequencyTableWithFrenquencyModel:(id)arg1 withType:(int)arg2;
- (void)deleteFrequencyTableWithFrequency:(id)arg1;
- (void)deleteFrequencyTableDataBase;
- (void)deleteFrequencyTableUseDate;
- (void)insertFrequencyTableWithModel:(id)arg1;
- (void)creatFrequencyTable;
- (void)execSql:(id)arg1;
- (id)init;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

