//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YMLGCDAsyncUdpSocketDelegate.h"

@class YMLGCDAsyncUdpSocket;

__attribute__((visibility("hidden")))
@interface YMLUDPSender : NSObject <YMLGCDAsyncUdpSocketDelegate>
{
    YMLGCDAsyncUdpSocket *_socket;
}

+ (void)sendMessage:(id)arg1 toHost:(id)arg2 port:(unsigned short)arg3;
@property(retain, nonatomic) YMLGCDAsyncUdpSocket *socket; // @synthesize socket=_socket;
- (void)udpSocket:(id)arg1 didNotSendDataWithTag:(long)arg2 dueToError:(id)arg3;
- (void)udpSocket:(id)arg1 didSendDataWithTag:(long)arg2;
- (void)dealloc;
- (id)initWithMessage:(id)arg1 host:(id)arg2 port:(unsigned short)arg3;

@end

