//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface YMStateURLInfo : NSObject
{
    NSString *_stateURLHost;
}

+ (id)sharedInstance;
- (id)appInstalledPath;
- (id)launchInitPath;
- (id)stateURLHost;
- (void)setStateURLHost:(id)arg1;
- (void)dealloc;
- (void)_setup;

@end

