//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface CityGridCell : UIView
{
    UILabel *_timeLabel;
    UILabel *_degreeLabel;
    UILabel *_nameLabel;
    BOOL _editing;
    UIImageView *_weatherImageView;
    id <CityGridCellDelegate> _delegate;
    UILabel *_temperatureLabel;
    UIActivityIndicatorView *_activityView;
    UIView *_contentView;
    UIButton *_deleteButton;
    UIImageView *_autoCityImageView;
    UIButton *_selectButton;
}

@property(nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(nonatomic) UIImageView *autoCityImageView; // @synthesize autoCityImageView=_autoCityImageView;
@property(nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(nonatomic) UILabel *temperatureLabel; // @synthesize temperatureLabel=_temperatureLabel;
@property(nonatomic) id <CityGridCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) UIImageView *weatherImageView; // @synthesize weatherImageView=_weatherImageView;
@property(nonatomic) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) UILabel *degreeLabel; // @synthesize degreeLabel=_degreeLabel;
@property(nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)deleteDidClick:(id)arg1;
- (void)selectDidTouchUpInside:(id)arg1;
- (void)selectDidClickDown:(id)arg1;
- (void)initSubViews;
- (void)hideActivity;
- (void)showActivity;
- (void)stopEditing;
- (void)startEditing;
- (void)layoutSubviews;
- (id)init;

@end

