//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TACommHttp.h"

@class NSString;

@interface CmObjUapLogout : TACommHttp
{
    id bizDelegate;
    NSString *UID;
    NSString *SID;
}

+ (id)commHttpWithTimeoutSeconds:(double)arg1 uid:(id)arg2 sid:(id)arg3 bizDelegate:(id)arg4;
+ (id)commHttpWithDelegate:(id)arg1 timeoutSeconds:(double)arg2 uid:(id)arg3 sid:(id)arg4 bizDelegate:(id)arg5;
@property(copy, nonatomic) NSString *SID; // @synthesize SID;
@property(copy, nonatomic) NSString *UID; // @synthesize UID;
- (void)commHttpDidFailToComm:(id)arg1;
- (void)commHttp:(id)arg1 didCommWithResponeHeader:(id)arg2 responseData:(id)arg3;
- (id)transferDataOfCommHttp:(id)arg1;
- (id)allHTTPHeaderFieldsOfCommHttp:(id)arg1;
- (id)methodOfCommHttp:(id)arg1;
- (id)targetURLOfCommHttp:(id)arg1;
- (id)initWithTimeoutSeconds:(double)arg1 autoRelease:(BOOL)arg2 uid:(id)arg3 sid:(id)arg4 bizDelegate:(id)arg5;
- (id)initWithDelegate:(id)arg1 timeoutSeconds:(double)arg2 autoRelease:(BOOL)arg3 uid:(id)arg4 sid:(id)arg5 bizDelegate:(id)arg6;
- (void)dealloc;
- (id)init;

@end

