//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LocalNotificationModelInterface.h"

__attribute__((visibility("hidden")))
@interface LocalNotificationModelImplement : NSObject <LocalNotificationModelInterface>
{
}

- (BOOL)_isEarlierDate:(id)arg1 CompareDate:(id)arg2;
- (id)_getSolarTermsPushModelToday:(id)arg1 withSolarTermsModel:(id)arg2;
- (id)_getSolarTermsPushModelPreDays:(id)arg1 withSolarTermsModel:(id)arg2;
- (id)_getSolarTermsPushModelPreThreeDays:(id)arg1 withSolarTermsModel:(id)arg2;
- (id)getSolarTermsSongs:(id)arg1 inObjects:(id)arg2;
- (id)getSortdSolarTermsWithYear:(id)arg1;
- (id)getPushFireDateArray:(id)arg1;
- (id)getSolarTermsModelWithCount:(int)arg1;

@end

