//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NdApKSDownloadItem.h"

@class NSString;

@interface NdApSoftItem : NSObject <NdApKSDownloadItem>
{
    int appId;
    NSString *identifier;
    NSString *localVersion;
    NSString *localShortVersion;
    NSString *version;
    NSString *shortVersion;
    NSString *iconPath;
    NSString *softName;
    NSString *defaultIconPath;
    long timeStamp;
    NSString *savePath;
    NSString *fileName;
    NSString *url;
    int downloadStatus;
    long downloadedLen;
    long totalLen;
    int installStatus;
}

+ (id)itemWithAppId:(int)arg1 softName:(id)arg2;
@property(readonly, nonatomic) NSString *primaryKey;
- (id)init;
- (BOOL)hasIcon;
- (void)dealloc;
- (id)defaultIcon;
- (id)absoluteSavePath;
- (void)generateSaveName;
- (id)absoluteFilePath;
- (id)iconUrl;
- (id)placeholderIconUrl;
- (id)appIdString;
- (BOOL)fileExist;
- (float)downloadPercent;
- (long)localFileLength;
@property(nonatomic) int installStatus; // @synthesize installStatus;
@property(nonatomic) long totalLen; // @synthesize totalLen;
@property(nonatomic) long downloadedLen; // @synthesize downloadedLen;
@property(nonatomic) int downloadStatus; // @synthesize downloadStatus;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName;
@property(retain, nonatomic) NSString *savePath; // @synthesize savePath;
@property(nonatomic) long timeStamp; // @synthesize timeStamp;
@property(retain, nonatomic) NSString *defaultIconPath; // @synthesize defaultIconPath;
@property(retain, nonatomic) NSString *softName; // @synthesize softName;
@property(retain, nonatomic) NSString *iconPath; // @synthesize iconPath;
@property(retain, nonatomic) NSString *shortVersion; // @synthesize shortVersion;
@property(retain, nonatomic) NSString *version; // @synthesize version;
@property(retain, nonatomic) NSString *localShortVersion; // @synthesize localShortVersion;
@property(retain, nonatomic) NSString *localVersion; // @synthesize localVersion;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier;
@property(nonatomic) int appId; // @synthesize appId;

@end

