//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NdCPServerOperation.h"

@class NSString;

@interface NdCPServerOperationCheckVirtualBalance : NdCPServerOperation
{
    NSString *balance;
    BOOL needCheckPayPassword;
    BOOL hasSetPassword;
}

@property(nonatomic) BOOL hasSetPassword; // @synthesize hasSetPassword;
@property(nonatomic) BOOL needCheckPayPassword; // @synthesize needCheckPayPassword;
@property(retain, nonatomic) NSString *balance; // @synthesize balance;
- (void)generateResponse:(id)arg1;
- (int)operation;
- (void)dealloc;
- (id)init;

@end

