//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NdCPServerOperation.h"

@class NSString;

@interface NdCPServerOperationVGGetPromotion : NdCPServerOperation
{
    int nAppId;
    NSString *strPromotion;
}

@property(retain, nonatomic) NSString *strPromotion; // @synthesize strPromotion;
@property(nonatomic) int nAppId; // @synthesize nAppId;
- (void)generateResponse:(id)arg1;
- (int)operation;
- (void)dealloc;
- (id)init;

@end

