//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NdPayRecord : NSObject
{
    NSString *cooOrderSerial;
    NSString *buyTime;
    NSString *productName;
    unsigned int productCount;
    float pay91Bean;
    NSString *appName;
}

@property(retain, nonatomic) NSString *appName; // @synthesize appName;
@property(nonatomic) float pay91Bean; // @synthesize pay91Bean;
@property(nonatomic) unsigned int productCount; // @synthesize productCount;
@property(retain, nonatomic) NSString *productName; // @synthesize productName;
@property(retain, nonatomic) NSString *buyTime; // @synthesize buyTime;
@property(retain, nonatomic) NSString *cooOrderSerial; // @synthesize cooOrderSerial;
- (void)dealloc;
- (id)init;

@end

