//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PickerContentViewDelegate.h"
#import "PickerTypeDelegate.h"

@class DateTypeController;

__attribute__((visibility("hidden")))
@interface PickerSolarYearMonth : UIViewController <PickerTypeDelegate, PickerContentViewDelegate>
{
    DateTypeController *picker;
    int nCurYear;
    int nCurMonth;
    id <PickerDelegate> delegate;
}

+ (id)createPickerSolarYearMonthWithDelegate:(id)arg1;
+ (void)showPickerSolarYearMonthWithYear:(int)arg1 WithMonth:(int)arg2 WithDelegate:(id)arg3;
@property(retain, nonatomic) DateTypeController *picker; // @synthesize picker;
@property int nCurMonth; // @synthesize nCurMonth;
@property int nCurYear; // @synthesize nCurYear;
@property(nonatomic) id <PickerDelegate> delegate; // @synthesize delegate;
- (void)PickerContentViewTouchEvent:(int)arg1;
- (void)pickerType:(id)arg1 didChangeDataWithNewData:(id)arg2;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)loadView;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)reloadPicker;
- (void)showPickerWithYear:(int)arg1 WithMonth:(int)arg2;
- (void)pressSetMonth:(id)arg1;
- (void)pressCurMonth:(id)arg1;
- (void)returnBtnPress:(id)arg1;

@end

