//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TAAutoResetEvent, TACommHttp;

@interface TACommHttpTimeoutChecker : NSObject
{
    TACommHttp *checkDest;
    unsigned int timeout;
    BOOL bCommOnMainThread;
    TAAutoResetEvent *thrdQuit;
}

- (void)start;
- (void)timeoutCheckThrdFunc:(id)arg1;
- (void)waitCheckThreadQuit;
- (void)dealloc;
- (id)initWithCommObj:(id)arg1 timeoutSeconds:(unsigned int)arg2 commOnMainThread:(BOOL)arg3;

@end

