//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TodayWeatherParser : NSObject
{
}

+ (id)parseNightBackgroundImageName:(id)arg1;
+ (id)parseBackgroundImageName:(id)arg1;
+ (id)parseLimitLine:(id)arg1;
+ (id)parseNightImageFileName:(id)arg1;
+ (id)parseDayImageFileName:(id)arg1;
+ (id)parseUltravioletRays:(id)arg1;
+ (id)parseTemperature:(id)arg1;
+ (id)parseWind:(id)arg1;
+ (id)parseWeather:(id)arg1;
+ (id)parse:(id)arg1;
+ (BOOL)isValidity:(id)arg1;

@end

