//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol UACProtocol <NSObject>
- (void)operation:(id)arg1 uacDidFinish:(id)arg2 actionType:(int)arg3 points:(int)arg4 pointDesc:(id)arg5;
@end

