//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface UISettingDateEditView : UIView
{
    UITextField *_txt4DateName;
    UILabel *_lbl4FeastTitle;
    UILabel *_lbl4DateTitle;
    UILabel *_lbl4Tip;
    UIButton *_btnDate;
    UIButton *_btn4OK;
    UIButton *_btn4Cancel;
    id <UISettingDateEditViewDelegate> DateEditViewDelegate;
}

@property(nonatomic) id <UISettingDateEditViewDelegate> DateEditViewDelegate; // @synthesize DateEditViewDelegate;
@property(retain, nonatomic) UIButton *btn4OK; // @synthesize btn4OK=_btn4OK;
@property(retain, nonatomic) UIButton *btn4Cancel; // @synthesize btn4Cancel=_btn4Cancel;
@property(retain, nonatomic) UIButton *btn4Date; // @synthesize btn4Date=_btnDate;
@property(retain, nonatomic) UILabel *lbl4Tip; // @synthesize lbl4Tip=_lbl4Tip;
@property(retain, nonatomic) UILabel *lbl4DateTitle; // @synthesize lbl4DateTitle=_lbl4DateTitle;
@property(retain, nonatomic) UILabel *lbl4FeastTitle; // @synthesize lbl4FeastTitle=_lbl4FeastTitle;
@property(retain, nonatomic) UITextField *txt4DateName; // @synthesize txt4DateName=_txt4DateName;
- (void)layoutSubviews;
- (void)setLayoutID:(id)arg1;
- (void)onDaySet:(id)arg1;
- (void)onCancelClick:(id)arg1;
- (void)onOKClick:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

