//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ThemeManager, UITrendHistogram;

__attribute__((visibility("hidden")))
@interface UITrendHistogramBar : UIView
{
    UITrendHistogram *trendView;
    ThemeManager *themeManager;
}

@property(nonatomic) UITrendHistogram *trendView; // @synthesize trendView;
- (void)Refresh;
- (void)DrawFaceIcon:(struct CGContext *)arg1 JX:(int)arg2 BarPos:(struct CGRect)arg3;
- (float)calcHisBarYHeight:(int)arg1;
- (void)DrawHistrogram:(struct CGContext *)arg1;
- (void)DrawXAxleTitle:(struct CGContext *)arg1;
- (void)calcHisBarArea:(struct CGRect *)arg1;
- (void)DrawBkGrid:(struct CGContext *)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrameAndParent:(struct CGRect)arg1 ParentView:(id)arg2;

@end

