//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITabBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class LiveIndex, NSMutableArray, NSString, UITableView;

__attribute__((visibility("hidden")))
@interface UIVCLiveIndexMore : BaseViewController <UITabBarDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UITableView *tableView;
    NSMutableArray *arrLiveIndexObject;
    NSString *cityName;
    LiveIndex *todayLiveIndex;
}

@property(retain, nonatomic) LiveIndex *todayLiveIndex; // @synthesize todayLiveIndex;
@property(copy, nonatomic) NSString *cityName; // @synthesize cityName;
@property(retain, nonatomic) NSMutableArray *arrLiveIndexObject; // @synthesize arrLiveIndexObject;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)updateTheme;
- (void)setupContentView;
- (void)setupNavigationBar;
- (void)setupBackground;
- (void)returnBtnPress:(id)arg1;
- (void)addItem:(id)arg1 type:(id)arg2 state:(id)arg3 detail:(id)arg4;
- (void)dealloc;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

