//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "AppTabItemSelectViewDataSource.h"
#import "AppTabItemSelectViewDelegate.h"
#import "ApplicationLifeCycle.h"
#import "UIScrollViewDelegate.h"

@class AppTabItemSelectView, NSArray, NdAPGameCenter, UIScrollView;

__attribute__((visibility("hidden")))
@interface UIVCAppPresent : BaseViewController <AppTabItemSelectViewDataSource, AppTabItemSelectViewDelegate, UIScrollViewDelegate, ApplicationLifeCycle>
{
    NdAPGameCenter *appGameView;
    AppTabItemSelectView *_selectView;
    UIScrollView *_scrollView;
    NSArray *prototypes;
    BOOL gameRecommendStop;
    int AppselectedType;
}

@property(nonatomic) int AppselectedType; // @synthesize AppselectedType;
@property(nonatomic) BOOL gameRecommendStop; // @synthesize gameRecommendStop;
@property(retain, nonatomic) NSArray *prototypes; // @synthesize prototypes;
- (void)reloadAppPresent;
- (void)setupPrototypes;
- (id)getPrototypeWithOrigin:(float)arg1;
- (id)getPrototypeWithType:(int)arg1;
- (id)setupJailBreakPrototypes;
- (id)setupAppStoreAndPXLPrototypes;
- (void)showAppViewByType:(int)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (id)init;
- (void)updateTheme;
- (void)setupContentView;
- (void)setupBackground;
- (id)TitleName;
- (id)ImageOverName;
- (id)ImageSelectName;
- (id)ImageName;
- (void)receiveApplicationEnterForeground:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)selectView:(id)arg1 selectedAppType:(int)arg2;
- (int)selectViewTag:(id)arg1 forIndex:(int)arg2;
- (id)selectViewTitle:(id)arg1 forIndex:(int)arg2;
- (int)selectViewTotalCount:(id)arg1;

@end

