//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "MBProgressHUDDelegate.h"

@class MBProgressHUD, NSMutableData, NSString, UIAlertView, UILabel, UITextView;

__attribute__((visibility("hidden")))
@interface UIVCSettingAbout : BaseViewController <MBProgressHUDDelegate>
{
    UILabel *lbCurVer;
    NSMutableData *responseData;
    UIAlertView *waitAlert;
    UITextView *txtNote;
    NSString *sDownUrl;
    unsigned int versionResult;
    MBProgressHUD *HUD;
}

@property(retain, nonatomic) UITextView *txtNote; // @synthesize txtNote;
@property(retain, nonatomic) UILabel *lbCurVer; // @synthesize lbCurVer;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setupNavigationBar;
- (void)setupBackground;
- (void)doOpenMainUrl:(id)arg1;
- (void)hudWasHidden:(id)arg1;
- (void)getNewVersion:(id)arg1;
- (void)CheckNewVersion;

@end

