//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSData, NSMutableData, NSMutableURLRequest, NSURL, NSURLConnection, NSURLResponse;

@interface UMUFPDataLoadJob : NSOperation
{
    NSURL *_imageURL;
    NSURLResponse *_response;
    NSMutableData *_responseData;
    NSURLConnection *_connection;
    double _timeoutInterval;
    NSMutableURLRequest *_request;
    BOOL boolIsFinished;
    id <UMDataLoadJobDelegate> _delegate;
    int dataType;
}

@property(nonatomic) int dataType; // @synthesize dataType;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(nonatomic) id <UMDataLoadJobDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void)dealloc;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
@property(readonly, nonatomic) NSData *responseData;
- (void)main;
- (id)initWithImageURL:(id)arg1 delegate:(id)arg2;

@end

