//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WeatherFrame.h"

__attribute__((visibility("hidden")))
@interface WeatherFrame : NSObject <WeatherFrame>
{
}

- (struct CGRect)forecastSplitLineFrame;
- (struct CGRect)forecastWeatherFrame;
- (struct CGRect)forecastTemperatureFrame;
- (struct CGRect)forecastDayFrame;
- (struct CGRect)forecastImageFrame;
- (struct CGRect)forecastContentFrameAtIndex:(int)arg1;
- (struct CGRect)forecastViewFrame;
- (struct CGRect)pmViewFrame;
- (struct CGRect)appViewFrame;
- (struct CGRect)helpLabelFrame;
- (struct CGRect)calendarButtonFrame;
- (struct CGRect)almanacButtonFrame;
- (struct CGRect)liveIndexButtonFrame;
- (struct CGRect)avoidFrame;
- (struct CGRect)lineImageFrame;
- (struct CGRect)avoidImageFrame;
- (struct CGRect)appropriateFrame;
- (struct CGRect)appropriateImageFrame;
- (struct CGRect)solarTermsFrame;
- (struct CGRect)lunarDayFrame;
- (struct CGRect)humidityFrame;
- (struct CGRect)carLimitFrame;
- (struct CGRect)windFrame;
- (struct CGRect)ultravioletRaysFrame;
- (struct CGRect)bottomAreaFrame;
- (struct CGRect)warningButtonFrame;
- (struct CGRect)warningLabelFrame;
- (struct CGPoint)warningImageCenter;
- (struct CGRect)warningImageFrame;
- (struct CGRect)warningViewFrame;
- (struct CGRect)releaseTimeFrame;
- (struct CGRect)weatherFrame;
- (struct CGRect)temperatureVariationFrame;
- (struct CGRect)refreshButtonFrame;
- (struct CGRect)weatherImageFrame;
- (struct CGRect)refreshImageFrame;
- (struct CGRect)temperatureDegreeFrame;
- (struct CGRect)temperatureFrame;
- (struct CGRect)topAreaFrame;
- (struct CGRect)addCityImageFrame;
- (struct CGRect)cityFrame;
- (struct CGRect)autoCityImageFrame;
- (struct CGRect)cityIndexFrame;
- (struct CGRect)shareFrame;
- (struct CGRect)liveIndexFrame;
- (struct CGRect)weatherTendencyFrame;
- (struct CGRect)headerAreaFrame;
- (struct CGSize)scrollViewContentSize;
- (struct CGRect)rightViewFrame;
- (struct CGRect)centerViewFrame;
- (struct CGRect)leftViewFrame;
- (struct CGRect)viewFrame;

@end

