//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (Instagram)
+ (id)mediumInstagramTitleFontOfSize:(float)arg1;
+ (id)boldInstagramFontOfSize:(float)arg1;
+ (id)semiboldInstagramFontOfSize:(float)arg1;
+ (id)instagramTitleFontOfSize:(float)arg1;
+ (id)instagramFontOfSize:(float)arg1;
+ (id)lightInstagramFontOfSize:(float)arg1;
@end

