//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AHAlertView;

@interface AHAlertViewController : UIViewController
{
    AHAlertView *_alertView;
}

@property(retain, nonatomic) AHAlertView *alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;
- (BOOL)prefersStatusBarHidden;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)loadView;

@end

