//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GMGridViewLayoutStrategyBase : NSObject
{
    int _type;
    struct CGSize _itemSize;
    int _itemSpacing;
    struct UIEdgeInsets _minEdgeInsets;
    BOOL _centeredGrid;
    int _itemCount;
    struct UIEdgeInsets _edgeInsets;
    struct CGRect _gridBounds;
    struct CGSize _contentSize;
}

@property(readonly, nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(readonly, nonatomic) struct CGRect gridBounds; // @synthesize gridBounds=_gridBounds;
@property(readonly, nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(readonly, nonatomic) int itemCount; // @synthesize itemCount=_itemCount;
@property(readonly, nonatomic) BOOL centeredGrid; // @synthesize centeredGrid=_centeredGrid;
@property(readonly, nonatomic) struct UIEdgeInsets minEdgeInsets; // @synthesize minEdgeInsets=_minEdgeInsets;
@property(readonly, nonatomic) int itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(readonly, nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
- (void)setEdgeAndContentSizeFromAbsoluteContentSize:(struct CGSize)arg1;
- (void)setupItemSize:(struct CGSize)arg1 andItemSpacing:(int)arg2 withMinEdgeInsets:(struct UIEdgeInsets)arg3 andCenteredGrid:(BOOL)arg4;

@end

