//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WQAnimation : NSObject
{
}

+ (id)makeHeadshakeAnimationWithPoint:(struct CGPoint)arg1 repeatTime:(double)arg2 Range:(struct _NSRange)arg3;
+ (void)showTakePictureAnimation:(id)arg1 withDelegate:(id)arg2;
+ (void)showCameraCloseEffectAnimation:(id)arg1 withDelegate:(id)arg2;
+ (void)showCameraOpenEffectAnimation:(id)arg1 withDelegate:(id)arg2;
+ (void)showRippleEffect:(id)arg1 withDelegate:(id)arg2;
+ (void)showRotationYAnimation:(id)arg1 withDelegate:(id)arg2;
+ (void)showFocusAnimation:(id)arg1 withDelegate:(id)arg2;
+ (void)showSnowAnimation:(id)arg1;
+ (void)showFadeAnimation:(id)arg1;
+ (void)showCubeAnimation:(id)arg1 isFromRight:(BOOL)arg2;

@end

