//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AddressBookUtils : NSObject
{
}

+ (BOOL)isNumerics:(id)arg1;
+ (id)getPhoneNumMD5:(id)arg1;
+ (id)getRightNum:(id)arg1;
+ (void *)getPersonByPhone:(id)arg1 addressBook:(void *)arg2;
+ (id)getPersonNameByPhone:(id)arg1 addressBook:(void *)arg2;
+ (BOOL)addImage:(void *)arg1 image:(id)arg2;
+ (BOOL)addAddress:(void *)arg1 street:(id)arg2;
+ (BOOL)addPhone:(void *)arg1 phone:(id)arg2;
+ (id)getShortName:(void *)arg1;
+ (BOOL)hasImageByPerson:(void *)arg1;
+ (id)getImageByPerson:(void *)arg1;
+ (id)getFirstEmail:(void *)arg1;
+ (id)getEmails:(void *)arg1;
+ (id)getEmailsWithAddressBook:(int)arg1 addressBook:(void *)arg2;
+ (id)getPhones:(void *)arg1;
+ (BOOL)hasEmails:(void *)arg1;
+ (id)getFirstCellPhoneNum:(void *)arg1;
+ (BOOL)hasCellPhones:(void *)arg1;
+ (BOOL)isCellPhoneNum:(id)arg1;
+ (BOOL)hasPhones:(void *)arg1;
+ (id)getPhonesWithAddressBook:(int)arg1 addressBook:(void *)arg2;
+ (id)getFullName:(void *)arg1;
+ (id)getFullName:(void *)arg1 personId:(int)arg2;
+ (id)copyModificationDate:(void *)arg1;
+ (id)getPhoneLabel:(void *)arg1 index:(int)arg2;
+ (id)getLastUpdateTime;
+ (id)getAllContactsMD5;
+ (id)getAllContactsWithPhone;
+ (id)SortAllContacts:(void *)arg1;
+ (id)getAllContacts;

@end

