//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIColor;

@interface AriderSegmentControl : UIView
{
    int _preSelectedSegment;
    BOOL _isShowIndicator;
    BOOL _isIndicatorShowBelow;
    BOOL _isShowIndicatorAnimation;
    UIView *_indicatorView;
    UIColor *_indicatorColor;
    UIView *_backgroundView;
    NSArray *_items;
    int _selectedSegmentIndex;
    id <AriderSegmentControlDelegate> _delegate;
    id _userInfo;
    double _animationDuration;
}

@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) id <AriderSegmentControlDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int selectedSegmentIndex; // @synthesize selectedSegmentIndex=_selectedSegmentIndex;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) BOOL isShowIndicatorAnimation; // @synthesize isShowIndicatorAnimation=_isShowIndicatorAnimation;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(nonatomic) BOOL isIndicatorShowBelow; // @synthesize isIndicatorShowBelow=_isIndicatorShowBelow;
@property(retain, nonatomic) UIColor *indicatorColor; // @synthesize indicatorColor=_indicatorColor;
@property(nonatomic) BOOL isShowIndicator; // @synthesize isShowIndicator=_isShowIndicator;
@property(retain, nonatomic) UIView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (void).cxx_destruct;
- (void)didSelectItem:(id)arg1;
- (void)updateIndicatorPositionFromItem:(id)arg1 toItem:(id)arg2;
- (void)showSegmentItemViews;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2;
- (id)initWithItems:(id)arg1;

@end

