//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ATCMTOPService.h"

@interface ATCGetCircleOfStarService : ATCMTOPService
{
}

+ (id)serviceWithStarUserId:(id)arg1 UserNick:(id)arg2 DistX:(id)arg3 DistY:(id)arg4 Type:(int)arg5 Result:(CDUnknownBlockType)arg6;

@end

