//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ATCLanLanInterestItem : NSObject
{
    BOOL isServerInterset;
    NSString *interestId;
    NSString *interestTitle;
    NSString *_interestNnusual;
}

+ (id)randItem;
@property(retain, nonatomic) NSString *interestNnusual; // @synthesize interestNnusual=_interestNnusual;
@property(nonatomic) BOOL isServerInterset; // @synthesize isServerInterset;
@property(retain, nonatomic) NSString *interestTitle; // @synthesize interestTitle;
@property(retain, nonatomic) NSString *interestId; // @synthesize interestId;
- (void).cxx_destruct;
- (id)description;

@end

