//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ATCModel.h"

@class NSArray, NSString;

@interface ATCTrendModel : ATCModel
{
    NSString *_pic;
    NSString *_publisherID;
    NSString *_publisherNick;
    NSString *_publisherHeadImage;
    NSString *_postTime;
    NSString *_postTimeStr;
    NSString *_appID;
    NSString *_trendTitle;
    NSString *_trendID;
    NSString *_trendPic;
    NSString *_shopID;
    NSString *_source;
    NSString *_type;
    NSArray *_shopItems;
}

+ (id)modelWithJSON:(id)arg1;
@property(retain, nonatomic) NSArray *shopItems; // @synthesize shopItems=_shopItems;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *shopID; // @synthesize shopID=_shopID;
@property(retain, nonatomic) NSString *trendPic; // @synthesize trendPic=_trendPic;
@property(retain, nonatomic) NSString *trendID; // @synthesize trendID=_trendID;
@property(retain, nonatomic) NSString *trendTitle; // @synthesize trendTitle=_trendTitle;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(retain, nonatomic) NSString *postTimeStr; // @synthesize postTimeStr=_postTimeStr;
@property(retain, nonatomic) NSString *postTime; // @synthesize postTime=_postTime;
@property(retain, nonatomic) NSString *publisherHeadImage; // @synthesize publisherHeadImage=_publisherHeadImage;
@property(retain, nonatomic) NSString *publisherNick; // @synthesize publisherNick=_publisherNick;
@property(retain, nonatomic) NSString *publisherID; // @synthesize publisherID=_publisherID;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
- (void).cxx_destruct;
- (void)setFromDictionary:(id)arg1;

@end

