//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError;

@protocol AVCamCaptureManager_HYDelegate

@optional
- (void)showPreview;
- (void)hidePreview;
- (void)processPreview:(struct opaqueCMSampleBuffer *)arg1;
- (void)handleCaptureData:(struct opaqueCMSampleBuffer *)arg1;
- (void)deviceCountChanged;
- (void)recordingFinished;
- (void)recordingBegan;
- (void)someOtherError:(NSError *)arg1;
- (void)acquiringDeviceLockFailedWithError:(NSError *)arg1;
- (void)captureStillImageFailedWithError:(NSError *)arg1;
@end

