//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UITapGestureRecognizer;

@interface AVCamPreviewView : UIView
{
    id <AVCamPreviewViewDelegate> _delegate;
    UITapGestureRecognizer *_tapGR;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGR; // @synthesize tapGR=_tapGR;
@property(nonatomic) id <AVCamPreviewViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)tapped:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

