//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseService.h"

@interface BindCardSetting : BaseService
{
}

+ (id)share;
- (void)testView:(id)arg1;
- (void)showError:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showError:(id)arg1;
- (void)closeWhenCancel;
- (void)bindCardRequestModelWithAction:(id)arg1 RequestParams:(id)arg2 ClassName:(id)arg3 ResultBlock:(CDUnknownBlockType)arg4;
- (void)enterMiniPayWithModel:(id)arg1;
- (void)controlBindCardProcess:(id)arg1 Params:(id)arg2 CompletionBlock:(CDUnknownBlockType)arg3 StatusBlock:(CDUnknownBlockType)arg4;
- (void)generateBindCardSettingViewControllerWithInfo:(id)arg1 CompletionBlock:(CDUnknownBlockType)arg2;

@end

