//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CPCheckBoxDelegate.h"

@class NSMutableArray;

@interface CPCheckBoxGroup : UIView <CPCheckBoxDelegate>
{
    NSMutableArray *_itemArray;
    BOOL _singleSelect;
    id <CPCheckBoxGroupDelegate> _delegate;
}

@property(nonatomic) id <CPCheckBoxGroupDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL singleSelect; // @synthesize singleSelect=_singleSelect;
@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
- (void).cxx_destruct;
- (id)getChoice;
- (void)checkBoxStateChange:(id)arg1;
- (void)layoutSubviews;
- (void)setSelectIndex:(int)arg1;
- (BOOL)clearSelectBut:(id)arg1;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

