//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CPK3BettingItemView;

@protocol CPK3BettingItemViewDelegate <NSObject>

@optional
- (void)CPK3BettingItemView:(CPK3BettingItemView *)arg1 didSelectWithIndex:(unsigned int)arg2;
- (BOOL)CPK3BettingItemView:(CPK3BettingItemView *)arg1 shouldSelectWithIndex:(unsigned int)arg2;
- (void)CPK3BettingItemView:(CPK3BettingItemView *)arg1 willSelectWithIndex:(unsigned int)arg2;
@end

