//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CPK3MachineSelectView, NSIndexPath;

@protocol CPK3MachineSelectViewDelegate <NSObject>

@optional
- (void)CPK3MachineSelectView:(CPK3MachineSelectView *)arg1 resultDidDeselectAt:(NSIndexPath *)arg2;
- (void)CPK3MachineSelectView:(CPK3MachineSelectView *)arg1 resultDidSelectAt:(NSIndexPath *)arg2;
@end

