//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImage;

@interface CPPresentChangeLotteryButton : UIButton
{
    int _lotteryType;
    BOOL _isSelected;
    UIImage *_selectedImage;
}

@property(nonatomic) BOOL isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) int lotteryType; // @synthesize lotteryType=_lotteryType;
- (void).cxx_destruct;
- (void)changeButtonSelectedState:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;

@end

