//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray;

@interface DLGridView : UIScrollView <UIScrollViewDelegate>
{
    struct CGSize lineSize;
    struct CGSize gapSize;
    NSMutableArray *cellTagArray;
    NSMutableArray *reuseGridCellQueue;
    struct CGSize itemSize;
    struct UIEdgeInsets edgeInsets;
    int orientation;
    id <DLGridViewDatasource> theDataSource;
    id <DLGridViewDelegate> theDelegate;
}

@property id <DLGridViewDelegate> theDelegate; // @synthesize theDelegate;
@property id <DLGridViewDatasource> theDataSource; // @synthesize theDataSource;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets;
@property(nonatomic) int orientation; // @synthesize orientation;
@property(retain, nonatomic) NSMutableArray *cellTagArray; // @synthesize cellTagArray;
@property(nonatomic) struct CGSize lineSize; // @synthesize lineSize;
@property(nonatomic) struct CGSize gapSize; // @synthesize gapSize;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)calcItemSize;
- (void)calcContentSize;
- (void)deletelocalDataAtIndex:(int)arg1;
- (void)layoutSubviews;
- (id)dequeueReusableCellWithIdentifier;
- (void)deleteCellAtIndex:(int)arg1;
- (int)indexOfGridViewCell:(id)arg1;
- (id)cellForGridAtIndex:(int)arg1;
- (void)launchGridCells;
- (id)init;

@end

