//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "kkStyleViewController.h"

@class NSString, UIButton, UIImageView, UILabel;

@interface kkBarcodeErrorViewController : kkStyleViewController
{
    NSString *_errTitleStr;
    NSString *_titleStr;
    NSString *_description;
    UIImageView *_image;
    UIImageView *_imageArrow;
    UILabel *_errTitleLabel;
    UILabel *_resultLabel;
    UIButton *_searchButton;
}

@property(retain, nonatomic) UIButton *searchButton; // @synthesize searchButton=_searchButton;
@property(retain, nonatomic) UILabel *resultLabel; // @synthesize resultLabel=_resultLabel;
@property(retain, nonatomic) UILabel *errTitleLabel; // @synthesize errTitleLabel=_errTitleLabel;
@property(retain, nonatomic) UIImageView *imageArrow; // @synthesize imageArrow=_imageArrow;
@property(retain, nonatomic) UIImageView *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *description; // @synthesize description=_description;
@property(retain, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
@property(retain, nonatomic) NSString *errTitleStr; // @synthesize errTitleStr=_errTitleStr;
- (void)onSearch:(id)arg1;
- (void)updateData;
- (void)dealloc;

@end

