//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface LQMemoryCache : NSObject
{
    unsigned int _costLimit;
    unsigned int _totalCost;
    CDUnknownBlockType _didReceiveMemortyWarningBlock;
    CDUnknownBlockType _didEnterBackgroundBlock;
    struct dispatch_queue_s *_queue;
    NSMutableDictionary *_cacheDic;
    NSMutableDictionary *_datesDic;
    NSMutableDictionary *_costsDic;
    double _timeLimit;
}

+ (id)sharedCache;
@property(retain, nonatomic) NSMutableDictionary *costsDic; // @synthesize costsDic=_costsDic;
@property(retain, nonatomic) NSMutableDictionary *datesDic; // @synthesize datesDic=_datesDic;
@property(retain, nonatomic) NSMutableDictionary *cacheDic; // @synthesize cacheDic=_cacheDic;
@property(nonatomic) struct dispatch_queue_s *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType didEnterBackgroundBlock; // @synthesize didEnterBackgroundBlock=_didEnterBackgroundBlock;
@property(copy, nonatomic) CDUnknownBlockType didReceiveMemortyWarningBlock; // @synthesize didReceiveMemortyWarningBlock=_didReceiveMemortyWarningBlock;
- (void).cxx_destruct;
@property(readonly) unsigned int totalCost; // @synthesize totalCost=_totalCost;
@property(nonatomic) double timeLimit; // @synthesize timeLimit=_timeLimit;
@property(nonatomic) unsigned int costLimit; // @synthesize costLimit=_costLimit;
- (void)removeAllObjects:(CDUnknownBlockType)arg1;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 withCost:(unsigned int)arg3 block:(CDUnknownBlockType)arg4;
- (void)setObject:(id)arg1 forKey:(id)arg2 withCost:(unsigned int)arg3;
- (void)setObject:(id)arg1 forKey:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)objectForKey:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)objectForKey:(id)arg1;
- (void)removeObjectAndExecuteBlocksForKey:(id)arg1;
- (void)trimCacheToDate:(id)arg1;
- (void)trimCacheByTimeLimitRecursively;
- (void)trimCacheToLimit:(unsigned int)arg1;
- (void)didObserveApplicationNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

