//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMPPayInfo : NSObject
{
    NSString *_payName;
    NSString *_payValue;
    NSString *_payKey;
    NSString *_payType;
}

@property(retain, nonatomic) NSString *payType; // @synthesize payType=_payType;
@property(retain, nonatomic) NSString *payKey; // @synthesize payKey=_payKey;
@property(retain, nonatomic) NSString *payValue; // @synthesize payValue=_payValue;
@property(retain, nonatomic) NSString *payName; // @synthesize payName=_payName;
- (void).cxx_destruct;

@end

