//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTopDataRequestDelegate.h"

@class NSMutableDictionary;

@interface MTopHttpRequestManager : NSObject <MTopDataRequestDelegate>
{
    NSMutableDictionary *_dicDelegateMap;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *dicDelegateMap; // @synthesize dicDelegateMap=_dicDelegateMap;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)requestDidFinish:(id)arg1;
- (void)requestDidStart:(id)arg1;
- (void)doResponsePubAccountAfterFeedListRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePublicAccountFeedListRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountFollowedListRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountAideListRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountFollowRemoveRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountFollowAddRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountInfoByWWIDRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountInfoRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountRecommendsRequest:(id)arg1 withError:(id)arg2;
- (void)doResponsePubAccountAutoCreateRequest:(id)arg1 withError:(id)arg2;
- (void)doResponseQueryOrderListRequest:(id)arg1 withError:(id)arg2;
- (void)doResponseQueryOrderDetailRequest:(id)arg1 withError:(id)arg2;
- (void)doResponseMTopRequest:(id)arg1 withError:(id)arg2;
- (void)requestPubAccountAfterFeedListWithSNSId:(id)arg1 pagination:(id)arg2 delegate:(id)arg3;
- (void)requestPublicAccountFirstFeedList:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountRecommendsWithOrder:(id)arg1 pagination:(id)arg2 delegate:(id)arg3;
- (void)requestPubAccountFollowedList:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountAideList:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountFollowRemove:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountFollowAdd:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountInfoByWWID:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountInfo:(id)arg1 delegate:(id)arg2;
- (void)requestPubAccountAutoCreate:(id)arg1;
- (void)requestQueryOrderList:(id)arg1 delegate:(id)arg2;
- (void)requestQueryOrderDetail:(id)arg1 delegate:(id)arg2;
- (void)dealloc;
- (void)removeDelegateForRequest:(id)arg1;
- (id)getDelegateWithRequest:(id)arg1;
- (void)insertDelegate:(id)arg1 andRequest:(id)arg2;
- (id)init;

@end

