//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TMMTOPRequest.h"

@class NSString;

@interface MTOPQueryTradeBuyRequestEX : TMMTOPRequest
{
    NSString *address;
    BOOL includeDeliver;
    BOOL includeCheckCode;
    NSString *skuId;
    unsigned int quantity;
    NSString *tgKey;
    NSString *itemId;
    NSString *sellerId;
    NSString *appKey;
    NSString *pid;
    NSString *strPid;
    NSString *unionId;
}

@property(retain, nonatomic) NSString *unionId; // @synthesize unionId;
@property(retain, nonatomic) NSString *strPid; // @synthesize strPid;
@property(retain, nonatomic) NSString *pid; // @synthesize pid;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey;
@property(retain, nonatomic) NSString *sellerId; // @synthesize sellerId;
@property(retain, nonatomic) NSString *tgKey; // @synthesize tgKey;
@property(nonatomic) unsigned int quantity; // @synthesize quantity;
@property(retain, nonatomic) NSString *skuId; // @synthesize skuId;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId;
@property(nonatomic) BOOL includeCheckCode; // @synthesize includeCheckCode;
@property(nonatomic) BOOL includeDeliver; // @synthesize includeDeliver;
@property(retain, nonatomic) NSString *address; // @synthesize address;
- (void).cxx_destruct;
- (id)buildResult;
- (void)sendRequest;
- (void)queryAddressWithDeliverId:(id)arg1;
- (void)queryAllAddress;
- (void)queryDefaultAddress;
- (id)init;

@end

