//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MtopDetailUnit.h"

@class NSString;

@interface MtopItemSku : MtopDetailUnit
{
    NSString *_skuId;
    NSString *_ppath;
}

@property(retain, nonatomic) NSString *ppath; // @synthesize ppath=_ppath;
@property(retain, nonatomic) NSString *skuId; // @synthesize skuId=_skuId;
- (void).cxx_destruct;
- (int)quantityCount;

@end

