//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (Information)
- (void)showAlertWithDefMsg:(id)arg1;
- (void)showAlertWithDic:(id)arg1;
- (id)messageByErrorCode:(int)arg1;
@end

