//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TBRichButton, UIImageView, UILabel;

@interface OrderListShopCell : UITableViewCell
{
    UILabel *_sellerTitleLabel;
    UILabel *_sellerNameLabel;
    TBRichButton *_sellerWangwangButton;
    TBRichButton *_sellerPhoneButton;
    UIImageView *_sellerAvatarBackgroundImageView;
}

+ (id)orderListShopCell;
@property(nonatomic) UIImageView *sellerAvatarBackgroundImageView; // @synthesize sellerAvatarBackgroundImageView=_sellerAvatarBackgroundImageView;
@property(nonatomic) TBRichButton *sellerPhoneButton; // @synthesize sellerPhoneButton=_sellerPhoneButton;
@property(nonatomic) TBRichButton *sellerWangwangButton; // @synthesize sellerWangwangButton=_sellerWangwangButton;
@property(nonatomic) UILabel *sellerNameLabel; // @synthesize sellerNameLabel=_sellerNameLabel;
@property(nonatomic) UILabel *sellerTitleLabel; // @synthesize sellerTitleLabel=_sellerTitleLabel;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

