//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface PWToast : UIView
{
    float _duration;
    NSString *_text;
    UILabel *_textLabel;
    UIImageView *_backGroudView;
    UIView *_parentView;
}

+ (void)cancelAllToastInView:(id)arg1;
+ (void)showToastInView:(id)arg1 text:(id)arg2 duration:(float)arg3;
+ (void)showToastInView:(id)arg1 text:(id)arg2;
@property(nonatomic) float duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)removeSelf;
- (void)hideToast;
- (void)showToastInView:(id)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

