//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface RowElementPeriodicBuy : NSObject
{
    int _totalItemCount;
    int _periodicity;
    int _frequency;
    NSArray *_firstArrivalTimes;
    NSArray *_cyclesInfo;
}

@property(retain, nonatomic) NSArray *cyclesInfo; // @synthesize cyclesInfo=_cyclesInfo;
@property(retain, nonatomic) NSArray *firstArrivalTimes; // @synthesize firstArrivalTimes=_firstArrivalTimes;
@property(nonatomic) int frequency; // @synthesize frequency=_frequency;
@property(nonatomic) int periodicity; // @synthesize periodicity=_periodicity;
@property(nonatomic) int totalItemCount; // @synthesize totalItemCount=_totalItemCount;
- (void).cxx_destruct;
- (id)firstArrivalTimesAsDates;

@end

