//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@protocol ShareRequestDelegate <NSObject>

@optional
- (void)shareCancelledSending:(id)arg1;
- (void)shareFailed:(id)arg1 withError:(NSError *)arg2;
- (void)shareFinishedSending:(id)arg1;
- (void)shareStartedSending:(id)arg1;
@end

