//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBAPICache : NSObject
{
}

+ (id)getCachedDataWithCachedKey:(id)arg1 wayOfCache:(BOOL)arg2;
+ (void)addCachedData:(id)arg1 cachedKey:(id)arg2 validTimestamp:(double)arg3 wayOfCache:(BOOL)arg4;
+ (id)cachedDictionary;

@end

