//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BettingItemObserver.h"
#import "ButtonGroupDelegate.h"
#import "UIAccelerometerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class AVAudioPlayer, BettingHelperBase, ButtonGroupView, CPBettingView, StakeInfoBase, TBBottomBar, TBTimerView, UIAcceleration, UIAlertView, UIImage, UIImageView, UIScrollView, UIView;

@interface TBBettingViewController : UIViewController <UIAccelerometerDelegate, UIAlertViewDelegate, ButtonGroupDelegate, BettingItemObserver, UIScrollViewDelegate>
{
    int _lotteryType;
    TBTimerView *_timeView;
    TBBottomBar *_bottomBar;
    UIScrollView *scrollView;
    UIView *_promptBar;
    CPBettingView *_bettingView;
    BettingHelperBase *_bettingHelper;
    UIImageView *arrowInTiltle;
    UIImage *arrowUp;
    UIImage *arrowDown;
    BOOL _histeresisExcited;
    UIAcceleration *_lastAcceleration;
    BOOL _isAddManualStake;
    StakeInfoBase *_editStake;
    BOOL _isFromPresent;
    UIAlertView *_lotteryHallBackAalert;
    AVAudioPlayer *_shakeSoundPlayer;
    ButtonGroupView *_btnGroup;
    UIView *_customView;
}

@property(retain, nonatomic) UIAcceleration *lastAcceleration; // @synthesize lastAcceleration=_lastAcceleration;
@property(retain, nonatomic) TBTimerView *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) TBBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) BettingHelperBase *bettingHelper; // @synthesize bettingHelper=_bettingHelper;
@property int lotteryType; // @synthesize lotteryType=_lotteryType;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)bettingItemChanged;
- (void)bottomBarTap:(id)arg1;
- (void)accelerometer:(id)arg1 didAccelerate:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)adjustViewToFitBtnGroup:(id)arg1;
- (void)buttonGroupDisappear:(id)arg1;
- (void)buttonGroupSelect:(id)arg1;
- (void)btnGroupViewWillDisapper:(id)arg1;
- (void)middleTitleClick:(id)arg1;
- (void)goBetting;
- (void)goBackToPresent;
- (void)goBackToList;
- (void)goStakelistController;
- (void)popBettingViewController;
- (void)goLotteryHall;
- (void)resetSelectedStatus;
- (void)showHelpOfLottery;
- (void)updateWithStake:(id)arg1;
- (void)updateBottomBar;
- (void)addBottomBar;
- (void)addScrollView;
- (void)setNavWithlotteryType;
- (void)updateBettingArea:(BOOL)arg1;
- (void)updateTitle;
- (BOOL)backPanGestureRecoginzed;
- (void)setupToolbarItems;
- (void)lotteryBackItemClicked:(id)arg1;
- (void)backItemClicked:(id)arg1;
- (id)dataForUserTrack;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)loadSound;
- (void)tapGestureAction;
- (void)viewDidLoad;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (id)initForManaulAdd:(int)arg1;
- (id)initForEditStakeFromPresent:(id)arg1;
- (id)initForEditStake:(id)arg1;
- (id)initForNormal:(int)arg1;
- (id)init:(int)arg1 andPlayMethod:(int)arg2;
- (void)loadBtnsBarForManaulAddStake;
- (void)cancelEdit;
- (void)loadBtnsForEditStake;

@end

