//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TBModelStatusDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, TBFavoriteService, TBModelStatusHandler;

__attribute__((visibility("hidden")))
@interface TBBookmarkCategoryService : NSObject <TBModelStatusDelegate, UITableViewDataSource, UITableViewDelegate>
{
    TBModelStatusHandler *_statusHandler;
    TBFavoriteService *_favoriteService;
    id <TBBookmarkCategoryServiceDelegate> _delegate;
    CDUnknownBlockType _categoryTableviewBlock;
    NSMutableArray *_itemList;
}

@property(retain, nonatomic) NSMutableArray *itemList; // @synthesize itemList=_itemList;
@property(copy, nonatomic) CDUnknownBlockType categoryTableviewBlock; // @synthesize categoryTableviewBlock=_categoryTableviewBlock;
@property(nonatomic) id <TBBookmarkCategoryServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) TBFavoriteService *favoriteService; // @synthesize favoriteService=_favoriteService;
- (void).cxx_destruct;
- (SEL)selectorForEmpty;
- (SEL)selectorForError:(id)arg1;
- (void)loadData;
@property(readonly, nonatomic) TBModelStatusHandler *statusHandler;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)reset;
- (void)loadDataInView:(id)arg1;
- (void)updateItems:(id)arg1;
- (id)init;

@end

