//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel, UIView;

@interface TBCabinInfoCell : UITableViewCell
{
    UILabel *price;
    UILabel *discount;
    UIButton *cabinType;
    UIButton *lessTickets;
    UILabel *agentName;
    UIButton *buyButton;
    UILabel *shipFlag;
    UIButton *xiehuiImage;
    UIButton *baozhangImage;
    UIButton *chapiaoImage;
    UIButton *orderBtn;
    UIButton *_promotionButton;
    UIButton *_fenRunButton;
    UIView *_bottomLine;
    UIView *_cabinbackgroundView;
}

+ (float)getHeightWithCabinInfo:(id)arg1;
@property(retain, nonatomic) UIView *cabinbackgroundView; // @synthesize cabinbackgroundView=_cabinbackgroundView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIButton *fenRunButton; // @synthesize fenRunButton=_fenRunButton;
@property(retain, nonatomic) UIButton *promotionButton; // @synthesize promotionButton=_promotionButton;
@property(retain, nonatomic) UIButton *orderBtn; // @synthesize orderBtn;
@property(retain, nonatomic) UIButton *chapiaoImage; // @synthesize chapiaoImage;
@property(retain, nonatomic) UIButton *baozhangImage; // @synthesize baozhangImage;
@property(retain, nonatomic) UIButton *xiehuiImage; // @synthesize xiehuiImage;
@property(retain, nonatomic) UILabel *shipFlag; // @synthesize shipFlag;
@property(retain, nonatomic) UIButton *buyButton; // @synthesize buyButton;
@property(retain, nonatomic) UILabel *agentName; // @synthesize agentName;
@property(retain, nonatomic) UIButton *lessTickets; // @synthesize lessTickets;
@property(retain, nonatomic) UIButton *cabinType; // @synthesize cabinType;
@property(retain, nonatomic) UILabel *discount; // @synthesize discount;
@property(retain, nonatomic) UILabel *price; // @synthesize price;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setButtonPosition:(id)arg1 ButtonSize:(struct CGSize)arg2 LeftButton:(id)arg3 RectLimitTo:(struct CGRect)arg4 MarginHorizon:(int)arg5 MarginVertical:(int)arg6;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)getLabelWithTextColor:(id)arg1 font:(id)arg2 frame:(struct CGRect)arg3;

@end

