//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class CALayer;

@interface TBChatNavigationBar : UINavigationBar
{
    CALayer *_colorLayer;
    CALayer *_lineLayer;
}

@property(retain, nonatomic) CALayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(retain, nonatomic) CALayer *colorLayer; // @synthesize colorLayer=_colorLayer;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setBarTintColor:(id)arg1;
- (void)setTintColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

