//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "UITableViewDataSource.h"

@class NSIndexPath;

@protocol TBChatListDataSource <NSObject, UITableViewDataSource>
@property(nonatomic) id <TBChatListDataSourceDelegate> delegate;
- (BOOL)objectAtIndexPathIsVirtual:(NSIndexPath *)arg1;
- (id)objectAtIndexPath:(NSIndexPath *)arg1;
- (id)initWithDelegate:(id <TBChatListDataSourceDelegate>)arg1;
@end

