//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBCityViewUtil : NSObject
{
}

+ (id)bottomBarNormalRoundButton:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)bottomBarRoundButton:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (void)drawLine:(struct CGRect)arg1 onView:(id)arg2 color:(id)arg3;
+ (BOOL)isRetina;
+ (id)simpleLabel:(struct CGRect)arg1 bf:(int)arg2 tc:(id)arg3 t:(id)arg4;
+ (id)simpleLabel:(struct CGRect)arg1 f:(int)arg2 tc:(id)arg3 t:(id)arg4;
+ (void)addShadow:(id)arg1;
+ (void)addShadow:(id)arg1 radius:(float)arg2;
+ (id)imageWithColor:(id)arg1 andSize:(struct CGSize)arg2;
+ (id)createStarView:(id)arg1 emptyImage:(id)arg2 harfImage:(id)arg3 maxNum:(int)arg4 starFloatNum:(float)arg5 starCellSize:(struct CGSize)arg6 w:(float)arg7 harfLowStarNum:(float)arg8;
+ (id)createStarView:(id)arg1 emptyImage:(id)arg2 starIntNum:(int)arg3 maxNum:(int)arg4 starCellSize:(struct CGSize)arg5 w:(float)arg6;

@end

