//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCitySDKRequestModel.h"

@class TBCityMyStorePayInfoItem;

@interface TBCityMyStorePayInfoModel : TBCitySDKRequestModel
{
    TBCityMyStorePayInfoItem *_myStorePayInfo;
}

@property(retain, nonatomic) TBCityMyStorePayInfoItem *myStorePayInfo; // @synthesize myStorePayInfo=_myStorePayInfo;
- (void).cxx_destruct;
- (void)requestDidLoadFailed:(id)arg1;
- (void)requestDidFinishLoad:(id)arg1;
- (void)getMyStorePayInfo:(id)arg1 localStoreId:(id)arg2;

@end

