//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TBCityMenuAdderView, UIImageView, UILabel;

@interface TBCityMenuPreviewCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_countLabel;
    UILabel *_priceLabel;
    TBCityMenuAdderView *_adderView;
    UIImageView *_adderBgView;
    BOOL _select;
    id <TBCityMenuAdderViewDelegate> _delegate;
}

@property(nonatomic) id <TBCityMenuAdderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setName:(id)arg1 count:(int)arg2 itemUnit:(id)arg3 price:(float)arg4;
- (void)showAdderView:(BOOL)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

