//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCityViewController.h"

#import "UIActionSheetDelegate.h"

@class NSString, TBBarButtonItem, TBCityMyTakeoutOrderDetailService, TBCityMyTakeoutOrderItem, TBCityTakeoutOrderDetailView, UIButton, UILabel;

@interface TBCityTakeoutOrderDetailViewController : TBCityViewController <UIActionSheetDelegate>
{
    BOOL _isLoadingData;
    NSString *_orderId;
    TBCityTakeoutOrderDetailView *_orderView;
    UIButton *_navigationBtn;
    UILabel *_navigationStatusLabel;
    TBCityMyTakeoutOrderDetailService *_takeoutOrderDetailService;
    TBCityMyTakeoutOrderItem *_orderItem;
    TBBarButtonItem *_btnPay;
    TBBarButtonItem *_btnCancelOrder;
    TBBarButtonItem *_btnReceiveOrder;
    TBBarButtonItem *_btnRefundOrder;
    TBBarButtonItem *_btnReviewOrder;
}

@property(retain, nonatomic) TBBarButtonItem *btnReviewOrder; // @synthesize btnReviewOrder=_btnReviewOrder;
@property(retain, nonatomic) TBBarButtonItem *btnRefundOrder; // @synthesize btnRefundOrder=_btnRefundOrder;
@property(retain, nonatomic) TBBarButtonItem *btnReceiveOrder; // @synthesize btnReceiveOrder=_btnReceiveOrder;
@property(retain, nonatomic) TBBarButtonItem *btnCancelOrder; // @synthesize btnCancelOrder=_btnCancelOrder;
@property(retain, nonatomic) TBBarButtonItem *btnPay; // @synthesize btnPay=_btnPay;
@property(retain, nonatomic) TBCityMyTakeoutOrderItem *orderItem; // @synthesize orderItem=_orderItem;
@property(retain, nonatomic) TBCityMyTakeoutOrderDetailService *takeoutOrderDetailService; // @synthesize takeoutOrderDetailService=_takeoutOrderDetailService;
@property(retain, nonatomic) UILabel *navigationStatusLabel; // @synthesize navigationStatusLabel=_navigationStatusLabel;
@property(retain, nonatomic) UIButton *navigationBtn; // @synthesize navigationBtn=_navigationBtn;
@property(nonatomic) BOOL isLoadingData; // @synthesize isLoadingData=_isLoadingData;
@property(retain, nonatomic) TBCityTakeoutOrderDetailView *orderView; // @synthesize orderView=_orderView;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
- (void).cxx_destruct;
- (SEL)selectorForEmpty;
- (SEL)selectorForError:(id)arg1;
- (void)reloadController;
- (id)statusHandler;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)pushToShopMenu;
- (void)callComplaints;
- (void)callPhone;
- (void)addClickEvent;
- (void)refundOrder;
- (void)popViewController;
- (void)receiveOrder;
- (void)cancelOrder;
- (void)doPayFinishAction:(int)arg1;
- (void)pay;
- (void)reviewOrder;
- (id)createNavigationBtn:(id)arg1 action:(SEL)arg2 type:(int)arg3;
- (void)setupToolBarItemButton:(id)arg1;
- (void)setupToolBarItem;
- (void)setupTitleLabel;
- (void)setupNavgationBar;
- (void)loadOrderView;
- (void)requestOrderDetailData;
- (id)initWithOrderId:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;

@end

