//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TBCityButtonTagDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSTimer, RTLabel, TBCityButtonTagView, TBCityTicketItem, TBCityUserEvouchersItems, UIButton, UIImageView, UILabel, UIScrollView, UITableView;

@interface TBCityCouponView : UIView <UITableViewDelegate, UITableViewDataSource, TBCityButtonTagDelegate>
{
    TBCityTicketItem *_couponDetail;
    NSMutableArray *_cashDetailArray;
    UITableView *_tableView;
    float _tableHeight;
    UILabel *_cashInfoLeft;
    UILabel *_cashInfoRight;
    UIImageView *_imageView;
    UIScrollView *_scrollView;
    BOOL _supportOpenStatus;
    UIImageView *_headImageView;
    UIView *_headView;
    UIView *_headEntryView;
    UILabel *_couponTitleLabel;
    UILabel *_couponValueLabel;
    UIImageView *_couponValueImageView;
    RTLabel *_deadLineLabel;
    UIImageView *_buyImageView;
    UILabel *_buyLabel;
    UILabel *_selledLabel;
    UILabel *_sellingLabel;
    NSTimer *_timer;
    NSTimer *_showTimer;
    UIView *_detailView;
    UILabel *_couponInfoLabel;
    UIView *_supportShopBgView;
    UILabel *_supportShopLabel;
    UIView *_supportShopView;
    TBCityButtonTagView *_buttonTagView;
    UIButton *_supportArrowBtn;
    TBCityUserEvouchersItems *_userCouponItem;
    UIImageView *_supportArrowImageView;
    id <TBCityCouponDelegate> _delegate;
    UIImageView *_couponTitleImageView;
    int _nowTime;
    int _publishendTime;
    int _showbeginTime;
    int _publishTime;
}

@property(nonatomic) int publishTime; // @synthesize publishTime=_publishTime;
@property(nonatomic) int showbeginTime; // @synthesize showbeginTime=_showbeginTime;
@property(nonatomic) int publishendTime; // @synthesize publishendTime=_publishendTime;
@property(nonatomic) int nowTime; // @synthesize nowTime=_nowTime;
@property(retain, nonatomic) UIImageView *couponTitleImageView; // @synthesize couponTitleImageView=_couponTitleImageView;
@property(nonatomic) id <TBCityCouponDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *supportArrowImageView; // @synthesize supportArrowImageView=_supportArrowImageView;
@property(retain, nonatomic) TBCityUserEvouchersItems *userCouponItem; // @synthesize userCouponItem=_userCouponItem;
@property(retain, nonatomic) UIButton *supportArrowBtn; // @synthesize supportArrowBtn=_supportArrowBtn;
@property(retain, nonatomic) TBCityButtonTagView *buttonTagView; // @synthesize buttonTagView=_buttonTagView;
@property(retain, nonatomic) UIView *supportShopView; // @synthesize supportShopView=_supportShopView;
@property(retain, nonatomic) UILabel *supportShopLabel; // @synthesize supportShopLabel=_supportShopLabel;
@property(retain, nonatomic) UIView *supportShopBgView; // @synthesize supportShopBgView=_supportShopBgView;
@property(retain, nonatomic) UILabel *couponInfoLabel; // @synthesize couponInfoLabel=_couponInfoLabel;
@property(retain, nonatomic) UIView *detailView; // @synthesize detailView=_detailView;
@property(retain, nonatomic) NSTimer *showTimer; // @synthesize showTimer=_showTimer;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *sellingLabel; // @synthesize sellingLabel=_sellingLabel;
@property(retain, nonatomic) UILabel *selledLabel; // @synthesize selledLabel=_selledLabel;
@property(retain, nonatomic) UILabel *buyLabel; // @synthesize buyLabel=_buyLabel;
@property(retain, nonatomic) UIImageView *buyImageView; // @synthesize buyImageView=_buyImageView;
@property(retain, nonatomic) RTLabel *deadLineLabel; // @synthesize deadLineLabel=_deadLineLabel;
@property(retain, nonatomic) UIImageView *couponValueImageView; // @synthesize couponValueImageView=_couponValueImageView;
@property(retain, nonatomic) UILabel *couponValueLabel; // @synthesize couponValueLabel=_couponValueLabel;
@property(retain, nonatomic) UILabel *couponTitleLabel; // @synthesize couponTitleLabel=_couponTitleLabel;
@property(retain, nonatomic) UIView *headEntryView; // @synthesize headEntryView=_headEntryView;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)openSupportView;
- (void)doBuyOrGetFree;
- (void)didSelectButton:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)optimumTextSize:(id)arg1;
- (void)showTimerMethod:(id)arg1;
- (void)timerFireMethod:(id)arg1;
- (void)addCouponHeadView;
- (void)sizeToFit;
- (void)setSupportView:(BOOL)arg1;
- (void)addSupportShop;
- (void)setImageView;
- (void)setupTableData;
- (void)setupView:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

