//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCityModel.h"

@class NSDictionary, NSString;

@interface TBCityScanItem : TBCityModel
{
    NSString *_type;
    NSString *_needLogin;
    NSString *_targetUrl;
    NSDictionary *_data;
}

@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) NSString *targetUrl; // @synthesize targetUrl=_targetUrl;
@property(retain, nonatomic) NSString *needLogin; // @synthesize needLogin=_needLogin;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)setFromDictionary:(id)arg1;

@end

