//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ButtonGroupDelegate.h"
#import "CPEGORefreshTableHeaderDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CPEGORefreshTableHeaderView, MKNetworkOperation, NSArray, NSMutableArray, NSString, TBBottomBar, UIAlertView, UIImage, UITableView, UIView;

@interface TBCompeteBettingController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate, CPEGORefreshTableHeaderDelegate, ButtonGroupDelegate>
{
    int lottryType;
    UITableView *_tableView;
    int _tableHeight;
    NSMutableArray *_itemData;
    TBBottomBar *_bottomBar;
    MKNetworkOperation *_currencyOperation;
    BOOL _isManualAddStack;
    BOOL _reLoading;
    CPEGORefreshTableHeaderView *_refreshHeaderView;
    UIAlertView *_lotteryHallBackAalert;
    BOOL _isFilterResult;
    UIImage *_sectionDownImage;
    UIImage *_sectionUpImage;
    NSString *_connectTime;
    UIView *_noDataView;
    UIView *_customView;
}

@property(nonatomic) BOOL isFilterResult; // @synthesize isFilterResult=_isFilterResult;
@property(retain, nonatomic) NSString *connectTime; // @synthesize connectTime=_connectTime;
@property(nonatomic) BOOL reLoading; // @synthesize reLoading=_reLoading;
@property(retain, nonatomic) CPEGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
@property(retain, nonatomic) MKNetworkOperation *currencyOperation; // @synthesize currencyOperation=_currencyOperation;
@property(retain, nonatomic) TBBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) NSArray *ItemData; // @synthesize ItemData=_itemData;
@property(nonatomic) int tableHeight; // @synthesize tableHeight=_tableHeight;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)updateTitle;
- (void)tapGestureAction;
- (void)adjustViewToFitBtnGroup:(id)arg1;
- (void)buttonGroupSelect:(id)arg1;
- (void)btnGroupViewWillDisapper:(id)arg1;
- (void)middleTitleClick:(id)arg1;
- (void)bottomBarTap:(id)arg1;
- (void)setCellExpand:(BOOL)arg1 WithIndexPath:(id)arg2;
- (void)refreshDataFinished;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)egoRefreshTableHeaderDataSourceLastUpdated:(id)arg1;
- (BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)showNoDataPage;
- (void)showHelper;
- (void)getCompeteFootBallMatchHasLoading:(BOOL)arg1;
- (void)showFilterCompete;
- (void)popBettingViewController;
- (void)goStakelistController;
- (void)resetSelectedStatus;
- (void)goBetting;
- (void)goLotteryHall;
- (void)cancleManaulAddMatchs;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)goLotteryHallCommit;
- (void)viewDidLayoutSubviews;
- (void)updateBottomBar;
- (void)loadImage;
- (void)sectionTitleClicked:(id)arg1;
- (void)selectMatchChanged:(id)arg1;
- (float)cellHeightWithIndex:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (BOOL)backPanGestureRecoginzed;
- (void)setupToolbarItems;
- (void)lotteryBackItemClicked:(id)arg1;
- (id)dataForUserTrack;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)backItemClicked:(id)arg1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)addTableViewFooter;
- (void)initTitle;
- (void)initTableView;
- (void)setNavWithlotteryType;
- (id)initForManualAddStackWithLotteryType:(int)arg1;
- (void)addBottomBar;
- (void)navRightButton;
- (void)loadNavigationBar;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (id)initWithLotteryType:(int)arg1;
- (void)stopNetRequset;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

