//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSKUPOPViewController.h"

#import "TBDetailDescPanelDelegate.h"
#import "TBModelStatusDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HUDActivityView, MTOPGetItemDetailDynamicResult, MTOPGetItemDetailOtherResult, MTOPGetItemDetailResult, MTOPGetItemDetailStaticResult, MTOPItemDescxModel, NSArray, NSMutableArray, NSMutableDictionary, NSString, NSTimer, SimplePhotoBrowserController, TBDetailDescPanel, TBDetailDescWebView, TBDetailHeaderView, TBDetailRatePanel, TBDetailRelatedView, TBGetDescInfoService, TBSeckillOrderService, TBSeckillQuestionModel, TBServiceContext, TBSkuView, TBWapItem, UIButton, UIImageView, UILabel, UIPageControl, UIScrollView, UITableView, UIView;

@interface TBDetailDescriptionViewController : TBSKUPOPViewController <TBDetailDescPanelDelegate, UIAlertViewDelegate, UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate, TBModelStatusDelegate, UIActionSheetDelegate>
{
    TBSeckillOrderService *_orderService;
    TBServiceContext *_serviceContext;
    TBSeckillQuestionModel *_questionModel;
    NSString *_listType;
    NSString *_listParam;
    BOOL _needClearAll;
    BOOL _fromEtao;
    BOOL _isSeckill;
    BOOL _isSeckillLoading;
    BOOL _contentSizeChanged;
    BOOL _scrollManually;
    BOOL _isloadOtherHeaderPics;
    BOOL _needH5Jump;
    BOOL _hasLoadDescImages;
    BOOL _hasLoadRates;
    BOOL _hasLoadRelationItems;
    BOOL _hasPop;
    BOOL _needLoadLiteDetail;
    BOOL _haveRelationItems;
    BOOL _needStopAutio;
    BOOL _allRequestReceivedAndReload;
    UIView *_maskView;
    UIScrollView *_scrollView;
    UIScrollView *_contentScrollView;
    MTOPGetItemDetailResult *_result;
    UILabel *_skuSumaryLabel;
    UILabel *_areaLabel;
    NSString *_itemId;
    HUDActivityView *_hudLoadingView;
    NSTimer *_seckillTimer;
    int _indexType;
    MTOPItemDescxModel *_descModel;
    SimplePhotoBrowserController *_simpleBrower;
    int _contentScrollIndex;
    TBDetailHeaderView *_headerView;
    UIScrollView *_headerScrollView;
    UIPageControl *_pageController;
    UIButton *_shareButton;
    UIButton *_collectButton;
    UILabel *_itemTitle;
    UILabel *_collectButtonLabel;
    UIImageView *_activeImageView;
    UIView *_segmentBar;
    UIView *_headerContainer;
    UIButton *_segmentMask;
    UIButton *_segmentBtn1;
    UIButton *_segmentBtn2;
    UIButton *_segmentBtn3;
    UIButton *_segmentBtnSelect;
    TBDetailDescPanel *_content1;
    UITableView *_content3;
    TBDetailRatePanel *_content2;
    UIView *_content4;
    NSArray *_relatedItems;
    HUDActivityView *_hudLogining;
    int _collectStatus;
    TBWapItem *_preloadItem;
    TBDetailDescWebView *_descWebView;
    NSMutableArray *_imageLoadingPool;
    NSMutableDictionary *_descImageDict;
    UIView *_maskHeaderView;
    TBDetailRelatedView *_relatedView;
    NSString *_isvStr;
    UIView *_allView;
    TBGetDescInfoService *_getDescInfoService;
    NSMutableArray *_relationItems;
    struct CGPoint _segmentOriginPoint;
}

@property(nonatomic) BOOL allRequestReceivedAndReload; // @synthesize allRequestReceivedAndReload=_allRequestReceivedAndReload;
@property(retain, nonatomic) NSMutableArray *relationItems; // @synthesize relationItems=_relationItems;
@property(nonatomic) BOOL needStopAutio; // @synthesize needStopAutio=_needStopAutio;
@property(nonatomic) BOOL haveRelationItems; // @synthesize haveRelationItems=_haveRelationItems;
@property(retain, nonatomic) TBGetDescInfoService *getDescInfoService; // @synthesize getDescInfoService=_getDescInfoService;
@property(retain, nonatomic) UIView *allView; // @synthesize allView=_allView;
@property(nonatomic) BOOL needLoadLiteDetail; // @synthesize needLoadLiteDetail=_needLoadLiteDetail;
@property(retain, nonatomic) NSString *isvStr; // @synthesize isvStr=_isvStr;
@property(nonatomic) BOOL hasPop; // @synthesize hasPop=_hasPop;
@property(nonatomic) BOOL hasLoadRelationItems; // @synthesize hasLoadRelationItems=_hasLoadRelationItems;
@property(nonatomic) BOOL hasLoadRates; // @synthesize hasLoadRates=_hasLoadRates;
@property(nonatomic) BOOL hasLoadDescImages; // @synthesize hasLoadDescImages=_hasLoadDescImages;
@property(retain, nonatomic) TBDetailRelatedView *relatedView; // @synthesize relatedView=_relatedView;
@property(retain, nonatomic) UIView *maskHeaderView; // @synthesize maskHeaderView=_maskHeaderView;
@property(retain, nonatomic) NSMutableDictionary *descImageDict; // @synthesize descImageDict=_descImageDict;
@property(retain, nonatomic) NSMutableArray *imageLoadingPool; // @synthesize imageLoadingPool=_imageLoadingPool;
@property(retain, nonatomic) TBDetailDescWebView *descWebView; // @synthesize descWebView=_descWebView;
@property(retain, nonatomic) TBWapItem *preloadItem; // @synthesize preloadItem=_preloadItem;
@property(nonatomic) BOOL needH5Jump; // @synthesize needH5Jump=_needH5Jump;
@property(nonatomic) int collectStatus; // @synthesize collectStatus=_collectStatus;
@property(retain, nonatomic) HUDActivityView *hudLogining; // @synthesize hudLogining=_hudLogining;
@property(retain, nonatomic) NSArray *relatedItems; // @synthesize relatedItems=_relatedItems;
@property(retain, nonatomic) UIView *content4; // @synthesize content4=_content4;
@property(retain, nonatomic) TBDetailRatePanel *content2; // @synthesize content2=_content2;
@property(retain, nonatomic) UITableView *content3; // @synthesize content3=_content3;
@property(retain, nonatomic) TBDetailDescPanel *content1; // @synthesize content1=_content1;
@property(retain, nonatomic) UIButton *segmentBtnSelect; // @synthesize segmentBtnSelect=_segmentBtnSelect;
@property(retain, nonatomic) UIButton *segmentBtn3; // @synthesize segmentBtn3=_segmentBtn3;
@property(retain, nonatomic) UIButton *segmentBtn2; // @synthesize segmentBtn2=_segmentBtn2;
@property(retain, nonatomic) UIButton *segmentBtn1; // @synthesize segmentBtn1=_segmentBtn1;
@property(nonatomic) struct CGPoint segmentOriginPoint; // @synthesize segmentOriginPoint=_segmentOriginPoint;
@property(retain, nonatomic) UIButton *segmentMask; // @synthesize segmentMask=_segmentMask;
@property(retain, nonatomic) UIView *headerContainer; // @synthesize headerContainer=_headerContainer;
@property(retain, nonatomic) UIView *segmentBar; // @synthesize segmentBar=_segmentBar;
@property(retain, nonatomic) UIImageView *activeImageView; // @synthesize activeImageView=_activeImageView;
@property(retain, nonatomic) UILabel *collectButtonLabel; // @synthesize collectButtonLabel=_collectButtonLabel;
@property(retain, nonatomic) UILabel *itemTitle; // @synthesize itemTitle=_itemTitle;
@property(retain, nonatomic) UIButton *collectButton; // @synthesize collectButton=_collectButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIPageControl *pageController; // @synthesize pageController=_pageController;
@property(retain, nonatomic) UIScrollView *headerScrollView; // @synthesize headerScrollView=_headerScrollView;
@property(retain, nonatomic) TBDetailHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) BOOL isloadOtherHeaderPics; // @synthesize isloadOtherHeaderPics=_isloadOtherHeaderPics;
@property(nonatomic) BOOL scrollManually; // @synthesize scrollManually=_scrollManually;
@property(nonatomic) BOOL contentSizeChanged; // @synthesize contentSizeChanged=_contentSizeChanged;
@property(nonatomic) int contentScrollIndex; // @synthesize contentScrollIndex=_contentScrollIndex;
@property(retain, nonatomic) SimplePhotoBrowserController *simpleBrower; // @synthesize simpleBrower=_simpleBrower;
@property(nonatomic) MTOPItemDescxModel *descModel; // @synthesize descModel=_descModel;
@property(nonatomic) int indexType; // @synthesize indexType=_indexType;
@property(nonatomic) BOOL isSeckillLoading; // @synthesize isSeckillLoading=_isSeckillLoading;
@property(retain, nonatomic) NSTimer *seckillTimer; // @synthesize seckillTimer=_seckillTimer;
@property(nonatomic) BOOL isSeckill; // @synthesize isSeckill=_isSeckill;
@property(nonatomic) BOOL fromEtao; // @synthesize fromEtao=_fromEtao;
@property(retain, nonatomic) HUDActivityView *hudLoadingView; // @synthesize hudLoadingView=_hudLoadingView;
@property(nonatomic) BOOL needClearAll; // @synthesize needClearAll=_needClearAll;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(retain, nonatomic) UILabel *areaLabel; // @synthesize areaLabel=_areaLabel;
@property(retain, nonatomic) UILabel *skuSumaryLabel; // @synthesize skuSumaryLabel=_skuSumaryLabel;
@property(retain, nonatomic) MTOPGetItemDetailResult *result; // @synthesize result=_result;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)needUpdateControllerViewSize;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (id)rateText;
- (id)secKillShareBaseURL;
- (void)shareItemClicked:(id)arg1;
- (void)clickRelatedItem:(id)arg1;
- (id)getEmptyView:(id)arg1 msg:(id)arg2;
- (void)appendToContentView:(id)arg1 add:(id)arg2;
- (void)resizeScrollView:(id)arg1;
- (void)clickLookItemDetail:(id)arg1;
- (void)usableCheck;
- (void)waitForAllRequestReceivedAndReload;
- (id)creatAppraiseView:(id)arg1;
- (id)creatVoiceAndAppraiseView;
- (void)onSegmentSelect:(id)arg1;
- (void)loadRelationItems;
- (void)generateContentScrollViewArea;
- (void)appendToScrollView:(id)arg1;
- (void)generateUnsupportHint;
- (void)generateTabArea;
- (id)seckillWattingTime;
- (void)updateJhsInfo;
- (void)popSkuWithComletion:(CDUnknownBlockType)arg1;
- (void)popSku;
- (void)popSkuFromMoreButton;
- (void)generateSkuBarArea;
- (void)startBuy;
- (void)buyAction;
- (void)buyButtonClicked:(id)arg1;
- (void)addtoCartClick:(id)arg1;
- (void)addToCartAction;
- (BOOL)needPopUp;
- (void)itemTypeBuySupport;
- (BOOL)canAddToCart;
- (BOOL)canBuy;
- (id)buyItem;
- (id)cartItem;
- (void)backItemClicked:(id)arg1;
- (id)backButtonItem;
- (void)reloadView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(retain, nonatomic) MTOPGetItemDetailDynamicResult *dynamicResult;
@property(retain, nonatomic) MTOPGetItemDetailOtherResult *otherResult;
@property(retain, nonatomic) TBSkuView *skuview;
@property(retain, nonatomic) MTOPGetItemDetailStaticResult *staticResult;

@end

