//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TBDoPayResult : NSObject
{
    BOOL _canPay;
    BOOL _securityPay;
    NSArray *_orderOutIds;
    NSArray *_orderIds;
    NSString *_alipayUrl;
    NSArray *_payPhaseIds;
    double _price;
}

@property(nonatomic) BOOL securityPay; // @synthesize securityPay=_securityPay;
@property(retain, nonatomic) NSArray *payPhaseIds; // @synthesize payPhaseIds=_payPhaseIds;
@property(retain, nonatomic) NSString *alipayUrl; // @synthesize alipayUrl=_alipayUrl;
@property(retain, nonatomic) NSArray *orderIds; // @synthesize orderIds=_orderIds;
@property(nonatomic) BOOL canPay; // @synthesize canPay=_canPay;
@property(retain, nonatomic) NSArray *orderOutIds; // @synthesize orderOutIds=_orderOutIds;
@property(nonatomic) double price; // @synthesize price=_price;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

