//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TBHttpEngineDataDelegate.h"

@interface TBFlightOrderDetailRequest : NSObject <TBHttpEngineDataDelegate>
{
    id <TBFlightOrderDetailRequestDelegate> delegate;
}

@property(nonatomic) id <TBFlightOrderDetailRequestDelegate> delegate; // @synthesize delegate;
- (void)httpEngineDidReceiveDataSuccessWithResponse:(id)arg1;
- (void)getFlightOrderDetail:(id)arg1;
- (id)parseFlightOrderDetail:(id)arg1;
- (id)parseFlightOrderActivity:(id)arg1;
- (id)parseFlightOrderAvaliables:(id)arg1;
- (id)parseFlightOrderPromotions:(id)arg1;
- (id)parseFlightOrderPromotion:(id)arg1;

@end

