//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBTripBaseViewController.h"

@class UILabel, UIScrollView;

@interface TBFlightActivityDetailController : TBTripBaseViewController
{
    UILabel *_subTitleView;
    UIScrollView *_contentScrollview;
}

- (void).cxx_destruct;
- (void)configureDetailContent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

