//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TBCounterLabelDelegate.h"
#import "TBCycleScrollViewDatasource.h"
#import "TBCycleScrollViewDelegate.h"
#import "TBGridMenuViewDelegate.h"
#import "TBRequestModelDelegate.h"

@class NSArray, NSMutableArray, TBALLHomePageContentItem, TBCounterLabel, TBCycleScrollView, TBGridMenuView, TBHomeGridMenuView, TBHomePageGuideItem, TBNewHomeViewController, UILabel;

__attribute__((visibility("hidden")))
@interface TBHomeGuideView : UIView <TBCycleScrollViewDatasource, TBCycleScrollViewDelegate, TBRequestModelDelegate, TBGridMenuViewDelegate, TBCounterLabelDelegate>
{
    TBALLHomePageContentItem *_pageContentItem;
    TBNewHomeViewController *_homeViewController;
    TBCycleScrollView *_bannerView;
    NSMutableArray *_bannerItems;
    NSMutableArray *_adListModelArray;
    NSMutableArray *_panicBuyModelArray;
    TBHomeGridMenuView *_menuView;
    TBCycleScrollView *_secondBannerView;
    TBHomePageGuideItem *_pageGuideItem;
    NSArray *_navi;
    TBGridMenuView *_secondBannerGridMenuView;
    TBCounterLabel *_countLabel;
    UILabel *_enterCheckMoreLabel;
}

@property(retain, nonatomic) UILabel *enterCheckMoreLabel; // @synthesize enterCheckMoreLabel=_enterCheckMoreLabel;
@property(retain, nonatomic) TBCounterLabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) TBGridMenuView *secondBannerGridMenuView; // @synthesize secondBannerGridMenuView=_secondBannerGridMenuView;
@property(retain, nonatomic) NSArray *navi; // @synthesize navi=_navi;
@property(retain, nonatomic) TBHomePageGuideItem *pageGuideItem; // @synthesize pageGuideItem=_pageGuideItem;
@property(retain, nonatomic) TBCycleScrollView *secondBannerView; // @synthesize secondBannerView=_secondBannerView;
@property(retain, nonatomic) TBHomeGridMenuView *menuView; // @synthesize menuView=_menuView;
@property(retain, nonatomic) NSMutableArray *panicBuyModelArray; // @synthesize panicBuyModelArray=_panicBuyModelArray;
@property(retain, nonatomic) NSMutableArray *adListModelArray; // @synthesize adListModelArray=_adListModelArray;
@property(retain, nonatomic) NSMutableArray *bannerItems; // @synthesize bannerItems=_bannerItems;
@property(retain, nonatomic) TBCycleScrollView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) TBNewHomeViewController *homeViewController; // @synthesize homeViewController=_homeViewController;
@property(retain, nonatomic) TBALLHomePageContentItem *pageContentItem; // @synthesize pageContentItem=_pageContentItem;
- (void).cxx_destruct;
- (void)countdownDidEnd;
- (void)gridMenuView:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (id)gridMenuView:(id)arg1 ItemViewForRowAtIndex:(int)arg2;
- (unsigned int)gridMenuViewNumberOfItems:(id)arg1;
- (void)modelDidCancelLoad:(id)arg1;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
- (id)csView:(id)arg1 pageAtIndex:(int)arg2;
- (int)numberOfPages:(id)arg1;
- (void)didClickPage:(id)arg1 atIndex:(int)arg2;
- (void)secondBannerViewClick:(id)arg1;
- (void)reloadSecondBannerData;
- (void)reloadSecondNewBannerData;
- (void)reloadTypeQiangGou;
- (void)reloadMenuData;
- (void)reloadBannerData;
- (void)reloadTypeZuanZhan;
- (void)reloadData:(BOOL)arg1;
- (id)utParam:(id)arg1 keyName:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

