//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBMBasePullTableViewController.h"

#import "TBMLocationDelegate.h"
#import "TBMMovieListTableViewCellDelegate.h"
#import "TBMOperationTableViewCellDelegate.h"
#import "UIViewControllerTBNavigator.h"

@class NSString, TBMCity, TBMHTTPRequest, TBMLocation, TBMOperation, UIAlertView, UIButton, UILabel;

@interface TBMMovieListViewController : TBMBasePullTableViewController <TBMMovieListTableViewCellDelegate, TBMLocationDelegate, TBMOperationTableViewCellDelegate, UIViewControllerTBNavigator>
{
    BOOL _needAskChangeCity;
    BOOL _hasLoadedMovieList;
    BOOL _needShowCityConfig;
    UIButton *_cityButton;
    UILabel *_cityLabel;
    NSString *_cityName;
    TBMLocation *_location;
    TBMCity *_currentReverseCity;
    TBMHTTPRequest *_operationRequest;
    TBMOperation *_operation;
    UIAlertView *_alertview;
    UIButton *_movieButton;
    UIButton *_couponButton;
    UIButton *_userButton;
}

+ (void)load;
@property(retain, nonatomic) UIButton *userButton; // @synthesize userButton=_userButton;
@property(retain, nonatomic) UIButton *couponButton; // @synthesize couponButton=_couponButton;
@property(retain, nonatomic) UIButton *movieButton; // @synthesize movieButton=_movieButton;
@property(nonatomic) BOOL needShowCityConfig; // @synthesize needShowCityConfig=_needShowCityConfig;
@property(retain, nonatomic) UIAlertView *alertview; // @synthesize alertview=_alertview;
@property(nonatomic) BOOL hasLoadedMovieList; // @synthesize hasLoadedMovieList=_hasLoadedMovieList;
@property(retain, nonatomic) TBMOperation *operation; // @synthesize operation=_operation;
@property(retain, nonatomic) TBMHTTPRequest *operationRequest; // @synthesize operationRequest=_operationRequest;
@property(retain, nonatomic) TBMCity *currentReverseCity; // @synthesize currentReverseCity=_currentReverseCity;
@property(retain, nonatomic) TBMLocation *location; // @synthesize location=_location;
@property(nonatomic) BOOL needAskChangeCity; // @synthesize needAskChangeCity=_needAskChangeCity;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(retain, nonatomic) UILabel *cityLabel; // @synthesize cityLabel=_cityLabel;
@property(retain, nonatomic) UIButton *cityButton; // @synthesize cityButton=_cityButton;
- (void)dealloc;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)reverseCityFailed:(id)arg1;
- (void)reverseCitySucc:(id)arg1;
- (void)getLoctionFailed:(id)arg1 isLocON:(BOOL)arg2;
- (void)getLoctionSucc:(id)arg1 oldLocation:(id)arg2;
- (void)operationTableViewCellDidSelectedClose:(id)arg1;
- (void)movieListCellDidSelectedBuy:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onUserLogOut:(id)arg1;
- (void)backItemClicked:(id)arg1;
- (void)switchToUserCentre;
- (void)gotoUserCenter:(id)arg1;
- (void)gotoCouponList:(id)arg1;
- (void)doChangeCity:(id)arg1;
- (id)resolveOperationRequestResult:(id)arg1;
- (void)operationDidFinishedLoadImg;
- (void)operationRequestDidCanceled:(id)arg1;
- (void)operationRequestDidFailed:(id)arg1;
- (void)operationRequestDidFinished:(id)arg1;
- (void)operationRequestDidStarted:(id)arg1;
- (void)requestDidCanceled:(id)arg1;
- (void)requestDidFailed:(id)arg1;
- (void)requestDidFinished:(id)arg1;
- (void)requestDidStarted:(id)arg1;
- (void)loadOperationData;
- (void)loadData;
- (void)doGetLocation;
- (void)checkLoc2ReloadClist;
- (void)saveDefaultCity;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)setupInitItems;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

