//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TBHttpEngineDataDelegate.h"

@class NSMutableDictionary;

@interface TBMoreTicketsRequest : NSObject <TBHttpEngineDataDelegate>
{
    NSMutableDictionary *extraData;
    id <TBMoreTicketsDelegate> delegate;
}

@property(nonatomic) id <TBMoreTicketsDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)httpEngineDidReceiveDataSuccessWithResponse:(id)arg1;
- (id)parseCabinInfoArrayFromDic:(id)arg1;
- (id)getWeatherString:(id)arg1;
- (id)parseCabinInfoFromDic:(id)arg1;
- (void)getMoreTickets:(id)arg1 includeOtherCabinType:(BOOL)arg2;

@end

