//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOBase.h"

@class NSString;

@interface TBMTopMiscDataGroupGetResultDataModel : DOBase
{
    NSString *_groupName;
    NSString *_dataKey;
    NSString *_dataValue;
    NSString *_dataType;
    NSString *_timeType;
    NSString *_success;
}

@property(retain, nonatomic) NSString *success; // @synthesize success=_success;
@property(retain, nonatomic) NSString *timeType; // @synthesize timeType=_timeType;
@property(retain, nonatomic) NSString *dataType; // @synthesize dataType=_dataType;
@property(retain, nonatomic) NSString *dataValue; // @synthesize dataValue=_dataValue;
@property(retain, nonatomic) NSString *dataKey; // @synthesize dataKey=_dataKey;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (void)dealloc;

@end

