//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBMTOPRequest.h"

@class NSString;

@interface TBMTopNewGetItemRequest : TBMTOPRequest
{
    id <TBTOPRequestDelegate> _privateDelegate;
    SEL _requestDidFinished;
    SEL _requestDidFail;
    NSString *_cid;
    NSString *_city;
    int _pageNo;
    int _count;
    int _itemType;
    NSString *_areaId;
    NSString *_posx;
    NSString *_posy;
    NSString *_distance;
    NSString *_order;
}

@property(retain, nonatomic) NSString *order; // @synthesize order=_order;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *posy; // @synthesize posy=_posy;
@property(retain, nonatomic) NSString *posx; // @synthesize posx=_posx;
@property(retain, nonatomic) NSString *areaId; // @synthesize areaId=_areaId;
@property(nonatomic) int itemType; // @synthesize itemType=_itemType;
@property(nonatomic) int count; // @synthesize count=_count;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
- (void)requestDidFailed:(id)arg1;
- (void)requestDidFinished:(id)arg1;
- (id)getItems;
- (id)mappingResponseJson:(id)arg1;
- (void)sendRequest;
- (void)customizeRequest:(id)arg1;
- (id)init;
- (void)dealloc;

@end

