//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TMModel.h"

@class NSString;

@interface TBPromotionEX : TMModel
{
    NSString *name;
    int type;
    NSString *description;
    NSString *price;
    NSString *key;
    NSString *promotionId;
    NSString *ext_remaining;
    NSString *ext_limit_count;
    NSString *ext_tjbNeed;
    NSString *ext_itemId;
}

@property(retain, nonatomic) NSString *ext_limit_count; // @synthesize ext_limit_count;
@property(retain, nonatomic) NSString *ext_remaining; // @synthesize ext_remaining;
@property(retain, nonatomic) NSString *ext_tjbNeed; // @synthesize ext_tjbNeed;
@property(retain, nonatomic) NSString *ext_itemId; // @synthesize ext_itemId;
@property(retain, nonatomic) NSString *promotionId; // @synthesize promotionId;
@property(retain, nonatomic) NSString *key; // @synthesize key;
@property(retain, nonatomic) NSString *price; // @synthesize price;
@property(retain, nonatomic) NSString *description; // @synthesize description;
@property(nonatomic) int type; // @synthesize type;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

