//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TBQGSourceView : UIView
{
    UILabel *_sourceName;
    UIImageView *_sourceArrow;
}

@property(retain, nonatomic) UIImageView *sourceArrow; // @synthesize sourceArrow=_sourceArrow;
@property(retain, nonatomic) UILabel *sourceName; // @synthesize sourceName=_sourceName;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

