//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBViewController.h"

#import "TBMenuViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, TBBarButtonItem, TBModelStatusHandler, TBOrderListCellItem, TBOrderService, UIButton, UITableView;

@interface TBRelatedOrderListViewController : TBViewController <UITableViewDataSource, UITableViewDelegate, TBMenuViewDelegate>
{
    BOOL _isArchivedOrder;
    UITableView *_relatedOrderTableView;
    NSMutableArray *_auctionArraysForActualShowing;
    TBOrderService *_tbOrderService;
    UIButton *_layerButton;
    TBBarButtonItem *_centerOperationBarButtonItem;
    TBOrderListCellItem *_mainOrderListCellItem;
    NSMutableArray *_relatedOrderItemArray;
    NSString *_operateName;
    TBModelStatusHandler *_statusHandler;
}

@property(nonatomic) BOOL isArchivedOrder; // @synthesize isArchivedOrder=_isArchivedOrder;
@property(retain, nonatomic) TBModelStatusHandler *statusHandler; // @synthesize statusHandler=_statusHandler;
@property(copy, nonatomic) NSString *operateName; // @synthesize operateName=_operateName;
@property(retain, nonatomic) NSMutableArray *relatedOrderItemArray; // @synthesize relatedOrderItemArray=_relatedOrderItemArray;
@property(retain, nonatomic) TBOrderListCellItem *mainOrderListCellItem; // @synthesize mainOrderListCellItem=_mainOrderListCellItem;
@property(retain, nonatomic) TBBarButtonItem *centerOperationBarButtonItem; // @synthesize centerOperationBarButtonItem=_centerOperationBarButtonItem;
@property(retain, nonatomic) UIButton *layerButton; // @synthesize layerButton=_layerButton;
@property(retain, nonatomic) TBOrderService *tbOrderService; // @synthesize tbOrderService=_tbOrderService;
@property(retain, nonatomic) NSMutableArray *auctionArraysForActualShowing; // @synthesize auctionArraysForActualShowing=_auctionArraysForActualShowing;
@property(retain, nonatomic) UITableView *relatedOrderTableView; // @synthesize relatedOrderTableView=_relatedOrderTableView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)TBMenuView:(id)arg1 didSelectedAtIndex:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)cancelOrderByOrderId:(id)arg1 andReasonId:(int)arg2;
- (void)helpPay:(id)arg1;
- (void)normalPay:(id)arg1;
- (void)stepPay:(id)arg1;
- (void)confirmDelivery:(id)arg1;
- (void)dismissCancelMenu:(id)arg1;
- (void)showCancelReasonMenu:(id)arg1;
- (void)cancelButtonClicked:(id)arg1;
- (void)setupToolbarView;
- (void)setupTableViewHeader;
- (id)toolbarButtonItemWithFrame:(struct CGRect)arg1 title:(id)arg2 action:(SEL)arg3 backgroundImage:(id)arg4;
- (id)makeSectionFooterCellInSection:(int)arg1;
- (id)item:(int)arg1 selector:(SEL)arg2;
- (void)layoutAuctionCell:(id)arg1 WithOrderListAuctionItem:(id)arg2;
- (void)fillArrayWithOrderItemForActualShowing:(id)arg1;
- (id)getMainOrderId;
- (void)prepareDataForDisplay;
- (void)didReceiveMemoryWarning;
- (void)gotoLastViewController;
- (void)viewDidLoad;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

