//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TBASRDelegate.h"
#import "TBSearchBarDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ASIHTTPRequest, NSMutableArray, TBItemSearchHelperService, TBSearchBar, UIButton, UIImageView, UITableView;

@interface TBSearchBusinessView : UIView <TBASRDelegate, UITableViewDataSource, UITableViewDelegate, TBSearchBarDelegate, UISearchBarDelegate, UIScrollViewDelegate>
{
    BOOL _isInitiativeSearch;
    UITableView *_searchMenuTableView;
    UIImageView *_searchMenuView;
    BOOL _isSearchMenuShowing;
    NSMutableArray *_searchHistoryArray;
    NSMutableArray *_suggestioinArray;
    NSMutableArray *_searchOptionArray;
    UIButton *_fullScreenLayerButton;
    unsigned long m_sound_src_id_pool[2];
    BOOL m_asr_entrance_has_been_init;
    float m_current_ios_float_version;
    BOOL p_is_tbasr_downgraded;
    BOOL p_is_tbasr_entrance_available;
    BOOL _isSearching;
    BOOL _isSearchSuggestionNeeded;
    BOOL _isClickEvent;
    UIView *p_asr_entrance_view;
    TBSearchBar *_searchBar;
    UITableView *_suggestionTableView;
    int _style;
    id <TBSearchBusinessViewDelegate> _delegate;
    TBItemSearchHelperService *_itemSearchHelperService;
    int _searchType;
    UIButton *_transparentLayerButton;
    int _suggestionstyle;
    NSMutableArray *_historyList;
    UIView *_suggestionFooterView;
    UIView *_emptyHistoryFooterView;
    NSMutableArray *_hotKeysArray;
    UIView *_searchBarBackground;
    UIView *_controlView;
    UIButton *_button1;
    UIButton *_button2;
    UIButton *_changeButton;
    ASIHTTPRequest *_httpRequest;
    NSMutableArray *_cells;
    struct CGRect _frameRect;
}

@property(retain, nonatomic) NSMutableArray *cells; // @synthesize cells=_cells;
@property(retain, nonatomic) ASIHTTPRequest *httpRequest; // @synthesize httpRequest=_httpRequest;
@property(retain, nonatomic) UIButton *changeButton; // @synthesize changeButton=_changeButton;
@property(retain, nonatomic) UIButton *button2; // @synthesize button2=_button2;
@property(retain, nonatomic) UIButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) UIView *controlView; // @synthesize controlView=_controlView;
@property(retain, nonatomic) UIView *searchBarBackground; // @synthesize searchBarBackground=_searchBarBackground;
@property(retain, nonatomic) NSMutableArray *hotKeysArray; // @synthesize hotKeysArray=_hotKeysArray;
@property(retain, nonatomic) UIView *emptyHistoryFooterView; // @synthesize emptyHistoryFooterView=_emptyHistoryFooterView;
@property(retain, nonatomic) UIView *suggestionFooterView; // @synthesize suggestionFooterView=_suggestionFooterView;
@property(retain, nonatomic) NSMutableArray *historyList; // @synthesize historyList=_historyList;
@property(nonatomic) struct CGRect frameRect; // @synthesize frameRect=_frameRect;
@property(nonatomic) BOOL isClickEvent; // @synthesize isClickEvent=_isClickEvent;
@property(nonatomic) int suggestionstyle; // @synthesize suggestionstyle=_suggestionstyle;
@property(retain, nonatomic) UIButton *transparentLayerButton; // @synthesize transparentLayerButton=_transparentLayerButton;
@property(nonatomic) BOOL isSearchSuggestionNeeded; // @synthesize isSearchSuggestionNeeded=_isSearchSuggestionNeeded;
@property(nonatomic) int searchType; // @synthesize searchType=_searchType;
@property(retain, nonatomic, setter=setTBItemSearchHelperService:) TBItemSearchHelperService *itemSearchHelperService; // @synthesize itemSearchHelperService=_itemSearchHelperService;
@property(nonatomic) BOOL isSearching; // @synthesize isSearching=_isSearching;
@property(nonatomic) id <TBSearchBusinessViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, setter=setStyle:) int style; // @synthesize style=_style;
@property(retain, nonatomic) UITableView *suggestionTableView; // @synthesize suggestionTableView=_suggestionTableView;
@property(retain, nonatomic) TBSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) BOOL isInitiativeSearch; // @synthesize isInitiativeSearch=_isInitiativeSearch;
@property(nonatomic) BOOL p_is_tbasr_entrance_available; // @synthesize p_is_tbasr_entrance_available;
@property(retain, nonatomic) UIView *p_asr_entrance_view; // @synthesize p_asr_entrance_view;
@property(nonatomic) BOOL p_is_tbasr_downgraded; // @synthesize p_is_tbasr_downgraded;
- (void).cxx_destruct;
- (int)searchWithASR:(id)arg1:(int)arg2:(id)arg3;
- (void)tbasr_entrancebtn_ontapped:(id)arg1;
- (void)showSearchBarBackground:(BOOL)arg1;
- (void)updateSearchHistory;
- (void)updateSearchHistory:(id)arg1;
- (void)SearchOptionCellTouchCancel:(id)arg1;
- (void)SearchOptionCellTouchDown:(id)arg1;
- (void)clearHistory;
- (void)loadHistorySearch;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidCancelLoad:(id)arg1;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidStartLoad:(id)arg1;
- (BOOL)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)cancelButtonClick;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (BOOL)searchBarShouldBeginEditing:(id)arg1;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)cancelObservingForKeyboardNotification;
- (void)observeForKeybordShowNotification;
- (void)setSearchOption:(id)arg1;
- (void)adjustSearchBarHeight:(float)arg1;
- (void)dismissSearchMenu:(id)arg1;
- (void)addTransparentLayerButton;
- (BOOL)deleteSearchKeyword:(id)arg1;
- (void)getSearchHistroyBySearchType:(int)arg1;
- (void)optionMenuButtonClicked;
- (void)showSearchOptionList:(BOOL)arg1;
- (void)searchWithkeyWord:(id)arg1 CatID:(id)arg2 IsWeiTao:(BOOL)arg3 orginInput:(id)arg4 suggIndex:(id)arg5 isOrgin:(BOOL)arg6 WithStyle:(int)arg7;
- (void)updateSearchSuggtionOption:(id)arg1 suggIndex:(id)arg2 isOrgin:(BOOL)arg3 keyWord:(id)arg4 WithStyle:(int)arg5;
- (void)showRightHInt:(BOOL)arg1;
- (void)dealloc;
- (void)hotwordClicked:(id)arg1;
- (void)splitWordsByLine;
- (void)getHotKeysData;
- (void)setSelectedIndex:(int)arg1;
- (void)clickSegment:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initTBASRModuleEntrance;
- (id)init;

@end

