//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSeckillBaseService.h"

@interface TBSeckillDetailService : TBSeckillBaseService
{
}

+ (id)parse:(id)arg1 error:(id *)arg2;
+ (void)getDynamicWithItemId:(id)arg1 Success:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
+ (void)getStaticWithItemId:(id)arg1 Success:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
+ (id)cdnStaticBaseURL;
+ (id)cdnDynamicBaseURL;

@end

