//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBViewController.h"

#import "PageStaticScrollerDelegate.h"
#import "TBExpandOrContractScrollViewDelegate.h"
#import "TBSearchBusinessViewDelegate.h"
#import "TBSegmentedControlDelegate.h"
#import "TBShopSearchCategoryServiceDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, NSTimer, PageStaticScroller, TBBarButtonItem, TBButton, TBExpandOrContractScrollViewDelegateObject, TBModelStatusHandler, TBMoreDataTableViewCell, TBSearchBusinessView, TBSearchComposeHeaderView, TBServiceContext, TBShopHomeCategoryViewController, TBShopSearchCategoryService, TBShopSearchFilterViewController, TBShopService, UIButton, UIScrollViewSpeed, UITableView, UITextField;

__attribute__((visibility("hidden")))
@interface TBShopSearchComposeViewController : TBViewController <TBExpandOrContractScrollViewDelegate, PageStaticScrollerDelegate, TBSearchBusinessViewDelegate, TBShopSearchCategoryServiceDelegate, UITableViewDataSource, UITableViewDelegate, TBSegmentedControlDelegate>
{
    BOOL _needForceReload;
    BOOL _isSearchBusinessViewShowing;
    struct CGPoint lastOpenedPos;
    BOOL _isReceivingMemoryWarning;
    BOOL _isPromotion;
    BOOL _isEmpty;
    BOOL _isFailed;
    BOOL _isScrolling;
    BOOL _loadCateforyView;
    UITableView *_tableView;
    TBSearchComposeHeaderView *_headerView;
    TBSearchBusinessView *_searchBusinessView;
    CDUnknownBlockType _leftMenuButtonActionBlock;
    CDUnknownBlockType _rightMenuButtonActionBlock;
    int _layoutStyle;
    NSString *_keyword;
    int _searchStyle;
    NSString *_userTrackIdentifier;
    NSString *_shopId;
    NSString *_sellerId;
    int _orderType;
    int _startPrice;
    int _endPrice;
    NSString *_categoryID;
    CDUnknownBlockType _dataSourceBlock;
    CDUnknownBlockType _refreshActionBlock;
    CDUnknownBlockType _loadMoreActionBlock;
    CDUnknownBlockType _segmentControlDataSourceBlock;
    CDUnknownBlockType _segmentControlDidChangedBlock;
    CDUnknownBlockType _willSearchBlock;
    TBModelStatusHandler *_searchFailStatusHandler;
    TBServiceContext *_serviceContext;
    TBServiceContext *_loadMoreserviceContext;
    NSString *_isvStr;
    TBExpandOrContractScrollViewDelegateObject *_expandOrContractScrollViewDelegateObject;
    TBButton *_leftMenuButton;
    TBButton *_rightMenuButton;
    TBBarButtonItem *_layoutItem;
    PageStaticScroller *_pageScroller;
    TBMoreDataTableViewCell *_moreDataTableViewCell;
    UIScrollViewSpeed *_scrollViewSpeed;
    NSTimer *_scrollTimer;
    TBShopService *_itemSearchService;
    TBShopSearchCategoryService *_searchCategoryService;
    TBShopHomeCategoryViewController *_shopCategoryViewController;
    TBShopSearchFilterViewController *_shopSearchFilterViewController;
    TBServiceContext *_categoryServiceContext;
    UIButton *_searchButton;
    UITextField *_searchTextField;
}

@property(retain, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(retain, nonatomic) UIButton *searchButton; // @synthesize searchButton=_searchButton;
@property(nonatomic) BOOL loadCateforyView; // @synthesize loadCateforyView=_loadCateforyView;
@property(retain, nonatomic) TBServiceContext *categoryServiceContext; // @synthesize categoryServiceContext=_categoryServiceContext;
@property(retain, nonatomic) TBShopSearchFilterViewController *shopSearchFilterViewController; // @synthesize shopSearchFilterViewController=_shopSearchFilterViewController;
@property(retain, nonatomic) TBShopHomeCategoryViewController *shopCategoryViewController; // @synthesize shopCategoryViewController=_shopCategoryViewController;
@property(retain, nonatomic) TBShopSearchCategoryService *searchCategoryService; // @synthesize searchCategoryService=_searchCategoryService;
@property(retain, nonatomic) TBShopService *itemSearchService; // @synthesize itemSearchService=_itemSearchService;
@property(nonatomic) BOOL isScrolling; // @synthesize isScrolling=_isScrolling;
@property(retain, nonatomic) NSTimer *scrollTimer; // @synthesize scrollTimer=_scrollTimer;
@property(retain, nonatomic) UIScrollViewSpeed *scrollViewSpeed; // @synthesize scrollViewSpeed=_scrollViewSpeed;
@property(retain, nonatomic) TBMoreDataTableViewCell *moreDataTableViewCell; // @synthesize moreDataTableViewCell=_moreDataTableViewCell;
@property(retain, nonatomic) PageStaticScroller *pageScroller; // @synthesize pageScroller=_pageScroller;
@property(retain, nonatomic) TBBarButtonItem *layoutItem; // @synthesize layoutItem=_layoutItem;
@property(nonatomic) BOOL isFailed; // @synthesize isFailed=_isFailed;
@property(nonatomic) BOOL isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) TBButton *rightMenuButton; // @synthesize rightMenuButton=_rightMenuButton;
@property(nonatomic) TBButton *leftMenuButton; // @synthesize leftMenuButton=_leftMenuButton;
@property(retain, nonatomic) TBExpandOrContractScrollViewDelegateObject *expandOrContractScrollViewDelegateObject; // @synthesize expandOrContractScrollViewDelegateObject=_expandOrContractScrollViewDelegateObject;
@property(retain, nonatomic) NSString *isvStr; // @synthesize isvStr=_isvStr;
@property(retain, nonatomic) TBServiceContext *loadMoreserviceContext; // @synthesize loadMoreserviceContext=_loadMoreserviceContext;
@property(retain, nonatomic) TBServiceContext *serviceContext; // @synthesize serviceContext=_serviceContext;
@property(retain, nonatomic) TBModelStatusHandler *searchFailStatusHandler; // @synthesize searchFailStatusHandler=_searchFailStatusHandler;
@property(copy, nonatomic) CDUnknownBlockType willSearchBlock; // @synthesize willSearchBlock=_willSearchBlock;
@property(copy, nonatomic) CDUnknownBlockType segmentControlDidChangedBlock; // @synthesize segmentControlDidChangedBlock=_segmentControlDidChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType segmentControlDataSourceBlock; // @synthesize segmentControlDataSourceBlock=_segmentControlDataSourceBlock;
@property(copy, nonatomic) CDUnknownBlockType loadMoreActionBlock; // @synthesize loadMoreActionBlock=_loadMoreActionBlock;
@property(copy, nonatomic) CDUnknownBlockType refreshActionBlock; // @synthesize refreshActionBlock=_refreshActionBlock;
@property(copy, nonatomic) CDUnknownBlockType dataSourceBlock; // @synthesize dataSourceBlock=_dataSourceBlock;
@property(copy, nonatomic) NSString *categoryID; // @synthesize categoryID=_categoryID;
@property(nonatomic) int endPrice; // @synthesize endPrice=_endPrice;
@property(nonatomic) int startPrice; // @synthesize startPrice=_startPrice;
@property(nonatomic) int orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *sellerId; // @synthesize sellerId=_sellerId;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
@property(copy, nonatomic) NSString *userTrackIdentifier; // @synthesize userTrackIdentifier=_userTrackIdentifier;
@property(nonatomic) BOOL isPromotion; // @synthesize isPromotion=_isPromotion;
@property(nonatomic) int searchStyle; // @synthesize searchStyle=_searchStyle;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(nonatomic) int layoutStyle; // @synthesize layoutStyle=_layoutStyle;
@property(copy, nonatomic) CDUnknownBlockType rightMenuButtonActionBlock; // @synthesize rightMenuButtonActionBlock=_rightMenuButtonActionBlock;
@property(copy, nonatomic) CDUnknownBlockType leftMenuButtonActionBlock; // @synthesize leftMenuButtonActionBlock=_leftMenuButtonActionBlock;
@property(retain, nonatomic) TBSearchBusinessView *searchBusinessView; // @synthesize searchBusinessView=_searchBusinessView;
@property(retain, nonatomic) TBSearchComposeHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)searchCategoryService:(id)arg1 selectedWithString:(id)arg2;
- (void)searchFilterConfirm;
- (void)searchAuctionInShop:(int)arg1 context:(id)arg2;
- (void)refreshCategoryData;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setOrdertypeWithOrderString:(id)arg1;
- (id)dataForUserTrack;
- (id)userTrackArgsForNextPage;
- (void)dealloc;
- (void)scrollTimerCallback:(id)arg1;
- (id)pageNumberForIndexPath:(id)arg1;
- (void)updatePageScrollerState;
- (void)tapRightMenuButton:(id)arg1;
- (void)tapLeftMenuButton:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)adjustPosition;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)restartTimer;
- (void)safeContract;
- (void)scrollViewShouldContact:(id)arg1;
- (void)scrollViewShouldExpand:(id)arg1;
- (void)contract;
- (void)expand;
- (void)hideHeader:(BOOL)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refreshUI;
- (void)segmentedControlSelectionChanged:(id)arg1 withButton:(id)arg2;
- (void)searchBarDidEndEditing;
- (void)searchDidCanceled;
- (void)willSearchWithKeyWord:(id)arg1 AndType:(int)arg2;
- (void)setShowsSearchBusinessView:(BOOL)arg1;
- (void)showSearchBusinessView:(id)arg1;
- (void)initSearchBusinessView;
- (void)loadHeader;
- (void)didReceiveMemoryWarning;
- (void)refreshSegmentedControl;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)adjustTableViewOffset;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)downloadImageForVisiableCells;
- (void)layoutButtonClicked:(id)arg1;
- (void)backItemClicked:(id)arg1;
- (void)configToolbarItems;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (void)viewDidAppearAtFirstTime;
- (void)viewDidLoad;

@end

