//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBViewController.h"

#import "UIActionSheetDelegate.h"

@class HUDActivityView, NSString, TBRichButton, TBShopInfoItem, TBShopService, UIActionSheet, UIImageView, UILabel, UITextView, UIView;

__attribute__((visibility("hidden")))
@interface TBShopHomeShopInfoViewController : TBViewController <UIActionSheetDelegate>
{
    BOOL _isLoadFailed;
    NSString *_sellerId;
    NSString *_shopId;
    TBShopInfoItem *_item;
    UITextView *_phoneTextView;
    UIImageView *_tmallImageView;
    UIView *_contentView;
    UIImageView *_picUrlImageView;
    UILabel *_titleLabel;
    UILabel *_cityLabel;
    UILabel *_goodPercentLabel;
    UILabel *_collectCountLabel;
    UILabel *_startsLabel;
    UILabel *_mgLabel;
    UILabel *_sgLabel;
    UILabel *_cgLabel;
    UILabel *_mgPLabel;
    UILabel *_sgPLabel;
    UILabel *_cgPLabel;
    UILabel *_startspLabel;
    UILabel *_collectionpLabel;
    UILabel *_goodPersentpLabel;
    UILabel *_citypLabel;
    TBRichButton *_callSellerButton;
    TBRichButton *_contactButton;
    UIView *_goodRateView;
    TBShopService *_shopService;
    HUDActivityView *_hudLoginWangwangView;
    HUDActivityView *_hudFavView;
    UIActionSheet *_callSellerActionSheet;
    UILabel *_sellerNickPLabel;
    UILabel *_sellerPhonepLabel;
    UILabel *_sellerNickLabel;
    UILabel *_sellerPhoneLabel;
    UIImageView *_wangwangImageView;
    UIImageView *_phoneImageView;
    UIImageView *_seperator1;
    UIImageView *_seperator3;
    UIImageView *_seperator2;
}

@property(nonatomic) UIImageView *seperator2; // @synthesize seperator2=_seperator2;
@property(nonatomic) UIImageView *seperator3; // @synthesize seperator3=_seperator3;
@property(nonatomic) UIImageView *seperator1; // @synthesize seperator1=_seperator1;
@property(retain, nonatomic) UIImageView *phoneImageView; // @synthesize phoneImageView=_phoneImageView;
@property(retain, nonatomic) UIImageView *wangwangImageView; // @synthesize wangwangImageView=_wangwangImageView;
@property(retain, nonatomic) UILabel *sellerPhoneLabel; // @synthesize sellerPhoneLabel=_sellerPhoneLabel;
@property(retain, nonatomic) UILabel *sellerNickLabel; // @synthesize sellerNickLabel=_sellerNickLabel;
@property(nonatomic) UILabel *sellerPhonepLabel; // @synthesize sellerPhonepLabel=_sellerPhonepLabel;
@property(nonatomic) UILabel *sellerNickPLabel; // @synthesize sellerNickPLabel=_sellerNickPLabel;
@property(retain, nonatomic) UIActionSheet *callSellerActionSheet; // @synthesize callSellerActionSheet=_callSellerActionSheet;
@property(retain, nonatomic) HUDActivityView *hudFavView; // @synthesize hudFavView=_hudFavView;
@property(retain, nonatomic) HUDActivityView *hudLoginWangwangView; // @synthesize hudLoginWangwangView=_hudLoginWangwangView;
@property(nonatomic) BOOL isLoadFailed; // @synthesize isLoadFailed=_isLoadFailed;
@property(retain, nonatomic) TBShopService *shopService; // @synthesize shopService=_shopService;
@property(nonatomic) UIView *goodRateView; // @synthesize goodRateView=_goodRateView;
@property(nonatomic) TBRichButton *contactButton; // @synthesize contactButton=_contactButton;
@property(nonatomic) TBRichButton *callSellerButton; // @synthesize callSellerButton=_callSellerButton;
@property(nonatomic) UILabel *citypLabel; // @synthesize citypLabel=_citypLabel;
@property(nonatomic) UILabel *goodPersentpLabel; // @synthesize goodPersentpLabel=_goodPersentpLabel;
@property(nonatomic) UILabel *collectionpLabel; // @synthesize collectionpLabel=_collectionpLabel;
@property(nonatomic) UILabel *startspLabel; // @synthesize startspLabel=_startspLabel;
@property(nonatomic) UILabel *cgPLabel; // @synthesize cgPLabel=_cgPLabel;
@property(nonatomic) UILabel *sgPLabel; // @synthesize sgPLabel=_sgPLabel;
@property(nonatomic) UILabel *mgPLabel; // @synthesize mgPLabel=_mgPLabel;
@property(nonatomic) UILabel *cgLabel; // @synthesize cgLabel=_cgLabel;
@property(nonatomic) UILabel *sgLabel; // @synthesize sgLabel=_sgLabel;
@property(nonatomic) UILabel *mgLabel; // @synthesize mgLabel=_mgLabel;
@property(nonatomic) UILabel *startsLabel; // @synthesize startsLabel=_startsLabel;
@property(nonatomic) UILabel *collectCountLabel; // @synthesize collectCountLabel=_collectCountLabel;
@property(nonatomic) UILabel *goodPercentLabel; // @synthesize goodPercentLabel=_goodPercentLabel;
@property(nonatomic) UILabel *cityLabel; // @synthesize cityLabel=_cityLabel;
@property(nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) UIImageView *picUrlImageView; // @synthesize picUrlImageView=_picUrlImageView;
@property(nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) UIImageView *tmallImageView; // @synthesize tmallImageView=_tmallImageView;
@property(nonatomic) UITextView *phoneTextView; // @synthesize phoneTextView=_phoneTextView;
@property(retain, nonatomic) TBShopInfoItem *item; // @synthesize item=_item;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
@property(retain, nonatomic) NSString *sellerId; // @synthesize sellerId=_sellerId;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)configLabel:(id)arg1 forScore:(id)arg2 andScoreGrade:(id)arg3;
- (void)removeLoading;
- (void)hideFavLoading;
- (void)showFavLoading;
- (id)dataForUserTrack;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)triggerRefresh;
- (void)refreshView;
- (void)configView;
- (void)contactSeller:(id)arg1;
- (void)callSeller:(id)arg1;
- (void)viewDidAppearAtFirstTime;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

