//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "TBSNSAccountListViewDelegate.h"

@class CALayer, TBSNSAccountListView, TBSNSNewAccountCenterHeadView, TBSNSNewAccountItem, TBSNSNewCardView, TBSNSNewCardViewOption, TBSNSRecentContactsListView;

@interface TBSNSNewAccountCenterView : UIScrollView <TBSNSAccountListViewDelegate>
{
    int _msgCount;
    float _scrollHeight;
    CALayer *_unReadMessageCircle;
    id <TBSNSNewAccountCenterViewDelgate> _centerViewDelegate;
    TBSNSNewAccountItem *_accountItem;
    TBSNSNewAccountCenterHeadView *_headView;
    TBSNSNewCardViewOption *_cardViewOption;
    TBSNSAccountListView *_accountListView;
    TBSNSRecentContactsListView *_recentListView;
    TBSNSNewCardView *_cardView0;
    TBSNSNewCardView *_cardView1;
    TBSNSNewCardView *_cardView2;
    id <TBSNSNewCardViewDelegate> _cardViewDelegate;
    id <TBSNSNewAccountCenterHeadViewDelegate> _headViewDelegate;
}

@property(retain, nonatomic) id <TBSNSNewAccountCenterHeadViewDelegate> headViewDelegate; // @synthesize headViewDelegate=_headViewDelegate;
@property(retain, nonatomic) id <TBSNSNewCardViewDelegate> cardViewDelegate; // @synthesize cardViewDelegate=_cardViewDelegate;
@property(retain, nonatomic) TBSNSNewCardView *cardView2; // @synthesize cardView2=_cardView2;
@property(retain, nonatomic) TBSNSNewCardView *cardView1; // @synthesize cardView1=_cardView1;
@property(retain, nonatomic) TBSNSNewCardView *cardView0; // @synthesize cardView0=_cardView0;
@property(retain, nonatomic) TBSNSRecentContactsListView *recentListView; // @synthesize recentListView=_recentListView;
@property(retain, nonatomic) TBSNSAccountListView *accountListView; // @synthesize accountListView=_accountListView;
@property(retain, nonatomic) TBSNSNewCardViewOption *cardViewOption; // @synthesize cardViewOption=_cardViewOption;
@property(retain, nonatomic) TBSNSNewAccountCenterHeadView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) TBSNSNewAccountItem *accountItem; // @synthesize accountItem=_accountItem;
@property(retain, nonatomic) id <TBSNSNewAccountCenterViewDelgate> centerViewDelegate; // @synthesize centerViewDelegate=_centerViewDelegate;
- (void).cxx_destruct;
- (void)completeLoadDataWithRecentContactsCount:(int)arg1 forRecentContactsListView:(id)arg2;
- (void)selectedItem:(int)arg1 forRecentContactsListView:(id)arg2;
- (id)headerViewForRecentContactsListView:(id)arg1;
- (void)selectedItem:(int)arg1 forAccountListView:(id)arg2;
- (id)serviceParametersForAccountListView:(id)arg1;
- (id)configureForAccountListView:(id)arg1;
- (id)headerViewForAccountListView:(id)arg1;
- (id)getCardItemViewWithSection:(int)arg1 row:(int)arg2;
- (void)removeDotView;
- (void)addDotView;
- (void)updateFavourCounts:(BOOL)arg1;
- (void)updateFollowCounts:(BOOL)arg1;
- (void)cleanNumberWithSection:(int)arg1 row:(int)arg2;
- (void)gotoFollowListByBottom:(id)arg1;
- (id)getDotView:(int)arg1;
- (id)getBottomView;
- (void)initTotalCardView;
- (void)initAccountList;
- (void)initCardView:(id)arg1 rectFrame:(struct CGRect)arg2 cardView:(id)arg3;
- (void)initUI;
- (void)initViewWithAccountItem:(id)arg1 msgCount:(int)arg2 delegate:(id)arg3;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

