//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TBShareManagerProtocol.h"

@class TBSNSActiveLotteryResultItem, UIButton, UIImageView;

@interface TBSNSLotteryAlertView : UIView <TBShareManagerProtocol>
{
    UIImageView *_faceImgView;
    UIButton *_btnLeft;
    UIButton *_btnRight;
    UIButton *_btnMiddle;
    TBSNSActiveLotteryResultItem *_dataItem;
}

@property(retain, nonatomic) TBSNSActiveLotteryResultItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) UIButton *btnMiddle; // @synthesize btnMiddle=_btnMiddle;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(retain, nonatomic) UIButton *btnLeft; // @synthesize btnLeft=_btnLeft;
@property(retain, nonatomic) UIImageView *faceImgView; // @synthesize faceImgView=_faceImgView;
- (void).cxx_destruct;
- (void)onHongBaoBtnTouched:(id)arg1;
- (void)onShareBtnTouched:(id)arg1;
- (void)onBgBtnTouched:(id)arg1;
- (void)setUpView;
- (id)initWithLotteryResult:(id)arg1;

@end

