//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSNSBasicViewController.h"

#import "TBModelStatusDelegate.h"
#import "TBSNSBasicServiceDelegate.h"
#import "TBShareManagerProtocol.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HUDActivityView, NSIndexPath, TBModelStatusHandler, TBSNSPagedList, TBSNSRelationService, dynamicHeadView;

@interface TBSNSBasicFeedListViewController : TBSNSBasicViewController <TBModelStatusDelegate, TBSNSBasicServiceDelegate, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate, TBShareManagerProtocol>
{
    NSIndexPath *_favoriteIndexPath;
    NSIndexPath *_followIndexPath;
    NSIndexPath *_praiseIndexPath;
    HUDActivityView *_hudLoadingView;
    TBSNSRelationService *_praiseOperationService;
    TBSNSRelationService *_accountOperationService;
    unsigned long long _feedId;
    unsigned long long _snsId;
    int _listType;
    TBSNSRelationService *_feedListService;
    TBSNSRelationService *_feedOperationService;
    TBSNSPagedList *_feedPagedList;
    TBModelStatusHandler *_statusHandler;
    dynamicHeadView *_dynamicHeadView;
}

+ (BOOL)tbNeedToolbar;
@property(retain, nonatomic) dynamicHeadView *dynamicHeadView; // @synthesize dynamicHeadView=_dynamicHeadView;
@property(retain, nonatomic) TBModelStatusHandler *statusHandler; // @synthesize statusHandler=_statusHandler;
@property(retain, nonatomic) TBSNSPagedList *feedPagedList; // @synthesize feedPagedList=_feedPagedList;
@property(retain, nonatomic) TBSNSRelationService *feedOperationService; // @synthesize feedOperationService=_feedOperationService;
@property(retain, nonatomic) TBSNSRelationService *feedListService; // @synthesize feedListService=_feedListService;
@property(nonatomic) int listType; // @synthesize listType=_listType;
- (void).cxx_destruct;
- (SEL)selectorForEmpty;
- (SEL)selectorForError:(id)arg1;
- (void)jumpToDetail:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForCellWithItem:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)loadImagesForOnscreenRows;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)resetShareContent:(id)arg1 type:(int)arg2;
- (BOOL)isNeedReset;
- (void)shareItemDidSelected:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)setCellActionSelector:(id)arg1;
- (id)tableView:(id)arg1 getCellForItem:(id)arg2;
- (id)tableView:(id)arg1 indexPathForObject:(id)arg2;
- (id)tableView:(id)arg1 itemAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)serviceDidFinishLoad:(id)arg1;
- (void)serviceDidCancelLoad:(id)arg1;
- (void)service:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)serviceDidStartLoad:(id)arg1;
- (id)getHeaderStr:(long)arg1;
- (void)getCacheFavoriteData;
- (void)loadFeedListData;
- (void)loadData;
- (void)setFavoriteStatus:(id)arg1 isLiked:(BOOL)arg2;
- (void)clearCache;
- (id)hudLoadingView;
- (void)favoriteLikedChangeWithFeedId:(id)arg1;
- (void)favoriteUnlikedChangeWithFeedId:(id)arg1;
- (void)favoriteStatusChangeWithFeedId:(unsigned long long)arg1 isLiked:(BOOL)arg2;
- (void)accountFollowOperation:(id)arg1;
- (void)feedPraiseOperationNotification:(id)arg1;
- (void)accountFavoriteOperationNotification:(id)arg1;
- (void)setPraiseButtonStatus:(id)arg1 isPraised:(BOOL)arg2;
- (void)setFollow:(BOOL)arg1;
- (void)commentButtonClicked:(id)arg1;
- (void)praiseButtonClicked:(id)arg1;
- (void)shareButtonClicked:(id)arg1;
- (void)accountFavoriteOperation:(id)arg1;
- (void)gotoDetailView:(id)arg1;
- (void)moreButtonClicked:(id)arg1;
- (void)followButtonClicked:(id)arg1;
- (void)backBtnClicked:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)initDataTable;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setupTBToolbarItems;
- (BOOL)needLoadingView;
- (void)setUpView;
- (void)nextPage;
- (void)refresh;
- (BOOL)needRefresh;
- (BOOL)needNextPage;

@end

