//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CALayer;

@interface TBSNSBasicListViewCell : UITableViewCell
{
    CDUnknownBlockType _prepareForReuseBlock;
    int _indexR;
    void *_extraD;
    CALayer *_myBackgroundLayer;
}

@property(retain, nonatomic) CALayer *myBackgroundLayer; // @synthesize myBackgroundLayer=_myBackgroundLayer;
@property(nonatomic) void *extraD; // @synthesize extraD=_extraD;
@property(nonatomic) int indexR; // @synthesize indexR=_indexR;
@property(copy, nonatomic) CDUnknownBlockType prepareForReuseBlock; // @synthesize prepareForReuseBlock=_prepareForReuseBlock;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)backgroundLayer;
- (void)setBackgroundLayer:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;

@end

