//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSNSBasicService.h"

@class NSString;

@interface TBSNSRelationService : TBSNSBasicService
{
    BOOL _isForceAddOperation;
    BOOL _isArrayOperation;
    BOOL _isFavoriteAction;
    BOOL _isFeedPraiseAction;
    BOOL _isPraiseAction;
    BOOL _isParentPraise;
    BOOL _isPushAction;
    BOOL _isFollowAction;
    int _opratiionType;
    NSString *_nick;
    unsigned long long _snsId;
    unsigned long long _feedId;
}

@property(retain, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(nonatomic) BOOL isFollowAction; // @synthesize isFollowAction=_isFollowAction;
@property(nonatomic) BOOL isPushAction; // @synthesize isPushAction=_isPushAction;
@property(nonatomic) BOOL isParentPraise; // @synthesize isParentPraise=_isParentPraise;
@property(nonatomic) BOOL isPraiseAction; // @synthesize isPraiseAction=_isPraiseAction;
@property(nonatomic) BOOL isFeedPraiseAction; // @synthesize isFeedPraiseAction=_isFeedPraiseAction;
@property(nonatomic) BOOL isFavoriteAction; // @synthesize isFavoriteAction=_isFavoriteAction;
@property(nonatomic) BOOL isArrayOperation; // @synthesize isArrayOperation=_isArrayOperation;
@property(nonatomic) BOOL isForceAddOperation; // @synthesize isForceAddOperation=_isForceAddOperation;
@property(nonatomic) unsigned long long feedId; // @synthesize feedId=_feedId;
@property(nonatomic) unsigned long long snsId; // @synthesize snsId=_snsId;
@property(nonatomic) int opratiionType; // @synthesize opratiionType=_opratiionType;
- (void).cxx_destruct;
- (void)dataUnique;
- (void)modelDidFinishLoad:(id)arg1;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidCancelLoad:(id)arg1;
- (void)cancelLogin;
- (void)delayAction;
- (void)useFeedItemClass;
- (void)useRectContactItemClass;
- (void)useDefaultItemClass;
- (void)loadOfferFeedsListWithPagination:(id)arg1;
- (BOOL)isOverDayOfGetRecommendAccountCard;
- (void)setDateOfGetRecommendAccountCard;
- (id)loadRecommendAccountCardWithPagination:(id)arg1;
- (void)loadMyCommendListWithPagination:(id)arg1 SnsId:(unsigned long long)arg2;
- (void)loadAccountFavoriteListWithPagination:(id)arg1;
- (void)getFollowCountWith:(long)arg1;
- (void)getFollowCount;
- (void)operationPushWithFollowSnsId:(unsigned long long)arg1 OpratiionType:(int)arg2;
- (void)operationPraiseWithFeedId:(unsigned long long)arg1 feedOwnerId:(unsigned long long)arg2 commentId:(unsigned long long)arg3 commenterSnsId:(unsigned long long)arg4 OpratiionType:(int)arg5;
- (void)operationFeedPraiseWithFeedId:(unsigned long long)arg1 SnsId:(unsigned long long)arg2 OpratiionType:(int)arg3;
- (void)operationFavoriteWithFeedId:(unsigned long long)arg1 SnsId:(unsigned long long)arg2 OpratiionType:(int)arg3;
- (void)operationFollowWithSnsIds:(id)arg1 OpratiionType:(int)arg2;
- (void)operationFollowWithSnsId:(unsigned long long)arg1 OpratiionType:(int)arg2;
- (void)operationFollowWithSid:(long)arg1 SnsId:(unsigned long long)arg2 OpratiionType:(int)arg3;
- (id)loadRecentContactsListWithPagination:(id)arg1;
- (id)loadMyFollowListWithPagination:(id)arg1;
- (id)loadHisFollowListWithSnsId:(long)arg1 Pagination:(id)arg2;
- (id)loadMyFollowListWithSid:(long)arg1 Pagination:(id)arg2;
- (void)dealloc;
- (id)init;

@end

