//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, TBBlurView, TBTabbarItem, UIColor, UIImage;

@interface TBTabbar : UIView
{
    NSArray *_items;
    TBTabbarItem *_selectedItem;
    UIColor *_tintColor;
    UIImage *_backgroundImage;
    id <TBTabbarDelegate> _delegate;
    NSMutableArray *_itemViews;
    TBBlurView *_backgroundView;
}

@property(retain, nonatomic) TBBlurView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(nonatomic) id <TBTabbarDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(nonatomic) TBTabbarItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)spaceViewWithWidth:(float)arg1;
- (void)buttonClicked:(id)arg1;
- (id)viewForItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

