//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ASIHTTPRequestDelegate.h"

@class NSArray, NSString, UIColor;

@interface TBTMSGlobalConfiguration : NSObject <ASIHTTPRequestDelegate>
{
    NSString *_markedString;
    UIColor *_markedColor;
    NSString *_markedFontName;
    float _markedFontSize;
    NSString *_markURL;
    NSString *_searchFilterURL;
    NSArray *_searchFilter;
    struct _NSRange _markedRange;
}

+ (id)Configuration;
@property(retain, nonatomic) NSArray *searchFilter; // @synthesize searchFilter=_searchFilter;
@property(retain, nonatomic) NSString *searchFilterURL; // @synthesize searchFilterURL=_searchFilterURL;
@property(retain, nonatomic) NSString *markURL; // @synthesize markURL=_markURL;
@property(nonatomic) float markedFontSize; // @synthesize markedFontSize=_markedFontSize;
@property(retain, nonatomic) NSString *markedFontName; // @synthesize markedFontName=_markedFontName;
@property(retain, nonatomic) UIColor *markedColor; // @synthesize markedColor=_markedColor;
@property(nonatomic) struct _NSRange markedRange; // @synthesize markedRange=_markedRange;
@property(retain, nonatomic) NSString *markedString; // @synthesize markedString=_markedString;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (id)getSearchFilterModel;
- (void)refreshConfiguration;
- (void)setTMSURLS:(id)arg1;
- (id)init;
- (void)configureTTTAttibutedLabel:(id)arg1 withText:(id)arg2;

@end

