//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBMTopResult.h"

@class TBTOPItemJuDetailList;

@interface TBTOPItemJuListDetailResult : TBMTopResult
{
    TBTOPItemJuDetailList *_ju_items_get_response;
    TBTOPItemJuDetailList *_ju_cityitems_get_response;
    TBTOPItemJuDetailList *_ju_todayitems_get_response;
    TBTOPItemJuDetailList *_data;
}

@property(retain, nonatomic) TBTOPItemJuDetailList *data; // @synthesize data=_data;
@property(retain, nonatomic) TBTOPItemJuDetailList *ju_todayitems_get_response; // @synthesize ju_todayitems_get_response=_ju_todayitems_get_response;
@property(retain, nonatomic) TBTOPItemJuDetailList *ju_cityitems_get_response; // @synthesize ju_cityitems_get_response=_ju_cityitems_get_response;
@property(retain, nonatomic) TBTOPItemJuDetailList *ju_items_get_response; // @synthesize ju_items_get_response=_ju_items_get_response;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)dealloc;

@end

