//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface TBTripListSegControl : UIView
{
    int index;
    int status;
    UIButton *timeBtn;
    UIButton *priceBtn;
}

@property(retain, nonatomic) UIButton *priceBtn; // @synthesize priceBtn;
@property(retain, nonatomic) UIButton *timeBtn; // @synthesize timeBtn;
@property(nonatomic) int status; // @synthesize status;
@property(nonatomic) int index; // @synthesize index;
- (void).cxx_destruct;
- (void)updateStatus:(int)arg1 sender:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)getCustomButtonWithIndex:(int)arg1 Rect:(struct CGRect)arg2;

@end

