//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface tdvIOConfiguration : NSObject
{
    BOOL _connectionSecured;
    int _sdkVersion;
    id <tdvUrlReqeustService> _requestService;
}

+ (id)secureURL:(id)arg1;
+ (id)downgradeURL:(id)arg1;
+ (BOOL)securedConnection;
+ (void)changeConnectionSecureStatus:(BOOL)arg1;
+ (id)requestService;
+ (void)setUrlRequestService:(id)arg1;
+ (int)sdkVersion;
+ (void)setSDKVersion:(int)arg1;
+ (id)serverURL;
+ (id)baseURL;
+ (id)pasteboardNamePrefix;
+ (id)deviceHashKey;
+ (id)selfSlotIndexKey;
+ (id)localUUIDKey;
+ (id)ioConfigurationSingleton;
@property(retain, nonatomic) id <tdvUrlReqeustService> requestService; // @synthesize requestService=_requestService;
@property int sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property BOOL connectionSecured; // @synthesize connectionSecured=_connectionSecured;
- (id)serverURLFromConfiguration;
- (id)baseURLFromConfiguration;
- (id)pasteboardNamePrefixFromConfiguration;
- (id)deviceHashKeyFromConfiguaration;
- (id)selfSlotIndexKeyFromConfiguration;
- (id)localUUIDKeyFromConfiguration;
- (id)init;
- (void)dealloc;

@end

