//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "tdvMetaAlgrithmCryptor.h"

@interface tdvMetaAlgrithm_AES128 : tdvMetaAlgrithmCryptor
{
}

- (unsigned int)algorithm;
- (unsigned long)blockSize;
- (unsigned long)keySizeWithKey:(id)arg1 initializationVector:(id)arg2;

@end

