//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APIBaseDelegate.h"
#import "TCLoginViewDelegate.h"
#import "TCWebViewKitDelegate.h"
#import "TencentRequestDelegate.h"
#import "TencentSessionDelegate.h"
#import "setHeadImageDelegate.h"

@class NSArray, NSDate, NSMutableDictionary, NSString, NSTimer, TCLoginViewKit, TCOSDKReachability, TCUiKit, TencentRequest;

@interface TencentOAuth : NSObject <TencentRequestDelegate, TCWebViewKitDelegate, TCLoginViewDelegate, setHeadImageDelegate, TencentSessionDelegate, APIBaseDelegate>
{
    NSMutableDictionary *_apiRequests;
    NSString *_accessToken;
    NSDate *_expirationDate;
    id <TencentSessionDelegate> _sessionDelegate;
    NSString *_localAppId;
    NSString *_openId;
    NSString *_redirectURI;
    NSArray *_permissions;
    TencentRequest *_request;
    TCLoginViewKit *_loginViewKit;
    NSString *_userNick;
    BOOL _userGetUserInfo;
    TCOSDKReachability *_reachHost;
    NSTimer *_timer;
    NSString *_appId;
    NSMutableDictionary *_loginDict;
    NSString *_encryToken;
    NSMutableDictionary *_openIdDict;
    TCUiKit *_tcUiKit;
}

+ (id)getTencentAppInstallUrl:(unsigned int)arg1;
+ (unsigned int)sendRespMessageToTencentApp:(id)arg1;
+ (BOOL)HandleOpenURL:(id)arg1;
+ (BOOL)CanHandleOpenURL:(id)arg1;
@property(retain, nonatomic) TCUiKit *tcUiKit; // @synthesize tcUiKit=_tcUiKit;
@property(retain, nonatomic) NSMutableDictionary *openIdDict; // @synthesize openIdDict=_openIdDict;
@property(retain, nonatomic) NSString *userNick; // @synthesize userNick=_userNick;
@property(readonly, nonatomic) NSString *encryToken; // @synthesize encryToken=_encryToken;
@property(retain, nonatomic) NSMutableDictionary *loginDict; // @synthesize loginDict=_loginDict;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) TCOSDKReachability *reachHost; // @synthesize reachHost=_reachHost;
@property(copy, nonatomic) NSString *redirectURI; // @synthesize redirectURI=_redirectURI;
@property(copy, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(copy, nonatomic) NSString *localAppId; // @synthesize localAppId=_localAppId;
@property(retain, nonatomic) NSArray *permissions; // @synthesize permissions=_permissions;
@property(nonatomic) id <TencentSessionDelegate> sessionDelegate; // @synthesize sessionDelegate=_sessionDelegate;
@property(copy, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void)apiBase:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
- (BOOL)webViewKit:(id)arg1 shouldAutorotateToInterfaceOrientation:(int)arg2;
- (BOOL)webViewKit:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)webViewKit:(id)arg1 didLoadWithNetworkError:(id)arg2;
- (void)webViewKit:(id)arg1 didLoadWithContentError:(id)arg2;
- (void)webViewKit:(id)arg1 didFinishedWithError:(id)arg2;
- (id)stringByTCOSDKReplacingHtmlEscapes:(id)arg1;
- (id)JSONValue:(id)arg1;
- (id)encrytoken;
- (void)request:(id)arg1 didLoad:(id)arg2 dat:(id)arg3;
- (void)request:(id)arg1 didReceiveResponse:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)getIntimateFriendsResponse:(id)arg1;
- (void)matchNickTipsResponse:(id)arg1;
- (void)getVipRichInfoResponse:(id)arg1;
- (void)getVipInfoResponse:(id)arg1;
- (void)setUserHeadpicResponse:(id)arg1;
- (void)addTopicResponse:(id)arg1;
- (void)addOneBlogResponse:(id)arg1;
- (void)checkPageFansResponse:(id)arg1;
- (void)uploadPicResponse:(id)arg1;
- (void)addAlbumResponse:(id)arg1;
- (void)addShareResponse:(id)arg1;
- (void)getListPhotoResponse:(id)arg1;
- (void)getListAlbumResponse:(id)arg1;
- (void)getUserInfoNotUserResponse:(id)arg1;
- (void)getUserInfoResponse:(id)arg1;
- (BOOL)tencentNeedPerformReAuth:(id)arg1;
- (BOOL)tencentNeedPerformIncrAuth:(id)arg1 withPermissions:(id)arg2;
- (void)tencentFailedUpdate:(int)arg1;
- (void)tencentDidUpdate:(id)arg1;
- (void)tencentDidNotNetWork;
- (void)tencentDidNotLogin:(BOOL)arg1;
- (void)tencentDidLogin;
- (void)onCGIRequestDidResponse:(id)arg1;
- (BOOL)sendAPIRequest:(id)arg1 callback:(id)arg2;
- (id)cgiRequestWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 callback:(id)arg4;
- (BOOL)cancel:(id)arg1;
- (BOOL)checkSendStoryParam:(id)arg1 fopenIdArray:(id)arg2;
- (BOOL)sendStory:(id)arg1 friendList:(id)arg2;
- (BOOL)getIntimateFriends:(id)arg1;
- (BOOL)matchNickTips:(id)arg1;
- (BOOL)getVipRichInfo;
- (BOOL)getVipInfo;
- (void)onTimerCloseTcWindow;
- (BOOL)didCancelled:(int)arg1;
- (int)didFinishedSetUserLocalPic:(id)arg1 image:(id)arg2 fileName:(id)arg3;
- (BOOL)setUserHeadpic:(id)arg1 andViewController:(id *)arg2;
- (BOOL)setUserHeadpic:(id)arg1;
- (BOOL)addTopicWithParams:(id)arg1;
- (BOOL)checkPageFansWithParams:(id)arg1;
- (BOOL)addOneBlogWithParams:(id)arg1;
- (BOOL)addAlbumWithParams:(id)arg1;
- (BOOL)uploadPicWithParams:(id)arg1;
- (BOOL)addShareWithParams:(id)arg1;
- (BOOL)getListPhotoWithParams:(id)arg1;
- (BOOL)getListAlbum;
- (BOOL)getUserInfo;
- (void)setEncryToken:(id)arg1;
- (BOOL)handleOpenURL:(id)arg1;
- (BOOL)oldCanhandleOpenURL:(id)arg1;
- (BOOL)isOpenIdValid;
- (BOOL)isSessionValid;
- (id)requestWithGraphPath:(id)arg1 andParams:(id)arg2 andHttpMethod:(id)arg3 andDelegate:(id)arg4;
- (id)requestWithGraphPath:(id)arg1 andParams:(id)arg2 andDelegate:(id)arg3;
- (id)requestWithGraphPath:(id)arg1 andDelegate:(id)arg2;
- (id)requestWithMethodName:(id)arg1 andParams:(id)arg2 andHttpMethod:(id)arg3 andDelegate:(id)arg4;
- (id)requestWithParams:(id)arg1 andDelegate:(id)arg2;
- (void)logout:(id)arg1;
- (BOOL)authorizeWithPermissions:(id)arg1 andExtraParams:(id)arg2 delegate:(id)arg3 inSafari:(BOOL)arg4;
- (BOOL)authorize:(id)arg1 localAppId:(id)arg2 inSafari:(BOOL)arg3;
- (BOOL)authorize:(id)arg1 inSafari:(BOOL)arg2;
- (BOOL)reauthorizeWithPermissions:(id)arg1;
- (BOOL)incrAuthWithPermissions:(id)arg1;
- (id)parseURLParams:(id)arg1;
- (void)onTimer;
- (void)reachabilityChanged:(id)arg1;
- (void)StopNotifyNetWork;
- (BOOL)StartNotifyNetWork;
- (void)tencentDialogLogin:(id)arg1 expirationDate:(id)arg2;
- (void)loginViewKit:(id)arg1 didFailuredWithError:(id)arg2 serial:(id)arg3;
- (void)loginViewKitDidSucceedLogin:(id)arg1 serial:(id)arg2;
- (BOOL)authorizeWithTencentAppAuthInSafari:(BOOL)arg1 permissions:(id)arg2 delegate:(id)arg3;
- (BOOL)authorizeWithTencentAppAuthInSafari:(BOOL)arg1 permissions:(id)arg2 andExtraParams:(id)arg3 delegate:(id)arg4;
- (id)getOwnBaseUrl;
- (id)openUrl:(id)arg1 params:(id)arg2 httpMethod:(id)arg3 delegate:(id)arg4;
- (void)dealloc;
- (id)initWithAppId:(id)arg1 andDelegate:(id)arg2;
- (void)deleteAPIRequestBySeq:(id)arg1;
- (void)cancelWithRequestKey:(id)arg1;

@end

