//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ASIHTTPRequest.h"

@interface TMImageRequest : ASIHTTPRequest
{
    int _status;
    id _responseDelegate;
    id _exteralInfo;
}

@property(retain) id exteralInfo; // @synthesize exteralInfo=_exteralInfo;
@property id responseDelegate; // @synthesize responseDelegate=_responseDelegate;
@property int status; // @synthesize status=_status;
- (void)dealloc;
- (void)clearDelegatesAndCancel;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (id)initWithURL:(id)arg1;

@end

