//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TMGridViewDataSource.h"
#import "TMGridViewDelegate.h"
#import "TMImageDownloaderDelegate.h"

@class NSArray, TMGridView;

@interface TMIntlBrandFolder : UIView <TMGridViewDataSource, TMGridViewDelegate, TMImageDownloaderDelegate>
{
    TMGridView *_gridView;
    id <TMIntlBrandFolderDelegate> _delegate;
    NSArray *_intlBrands;
}

@property(retain, nonatomic) NSArray *intlBrands; // @synthesize intlBrands=_intlBrands;
@property(nonatomic) id <TMIntlBrandFolderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TMGridView *gridView; // @synthesize gridView=_gridView;
- (void).cxx_destruct;
- (void)setIntlBrandFolderData:(id)arg1;
- (void)dealloc;
- (void)tmImageDownloaderSuccess:(id)arg1 request:(id)arg2 data:(id)arg3;
- (void)requestThemeImage:(id)arg1 andWidth:(int)arg2 andHeight:(int)arg3 withUserInfo:(id)arg4;
- (void)gridView:(id)arg1 didSelectedItemAtIndexPath:(id)arg2;
- (id)gridView:(id)arg1 itemForColumnAtIndexPath:(id)arg2;
- (float)gridView:(id)arg1 heightOfItemAtIndexPath:(id)arg2;
- (float)gridView:(id)arg1 widthOfItemAtIndexPath:(id)arg2;
- (int)gridView:(id)arg1 numberOfColumnInRow:(int)arg2;
- (int)numberOfRowAtGridView:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

