//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TMMTOPRequest.h"

@class NSString;

@interface TMMTOPGetShopInfoByDomainEx : TMMTOPRequest
{
    NSString *domain;
}

@property(retain, nonatomic) NSString *domain; // @synthesize domain;
- (void).cxx_destruct;
- (void)sendRequest;
- (id)init;

@end

