//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TMOrderNormalView.h"

@class NSString;

@interface TMOrderNormalTipView : TMOrderNormalView
{
    NSString *_tip;
}

+ (float)calculateHeight:(id)arg1;
@property(retain, nonatomic) NSString *tip; // @synthesize tip=_tip;
- (void).cxx_destruct;
- (float)drawContent:(struct CGContext *)arg1;

@end

