//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, TMRefreshTableHeaderView;

@protocol TMRefreshTableHeaderDelegate <NSObject>
- (BOOL)tmRefreshTableHeaderDataSourceIsLoading:(TMRefreshTableHeaderView *)arg1;
- (void)tmRefreshTableHeaderDidTriggerRefresh:(TMRefreshTableHeaderView *)arg1;

@optional
- (NSDate *)tmRefreshTableHeaderDataSourceLastUpdated:(TMRefreshTableHeaderView *)arg1;
@end

