//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOBase.h"

@class NSString;

@interface TopResult : DOBase
{
    NSString *_content;
}

+ (id)mapping:(id)arg1;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (BOOL)isRetContain:(id)arg1;
- (BOOL)isSessionInvalid;
- (BOOL)isGeneralFailure;
- (BOOL)isCheckCodeError;
- (BOOL)isDoubleRequest;
- (BOOL)isNotSupportForMobile;
- (BOOL)isFail;
- (BOOL)isSuccess;
- (BOOL)isResultMatchToString:(id)arg1;
- (void)dealloc;

@end

