//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString;

@interface TribeMessage : NSObject
{
    NSNumber *msgId;
    int msgType;
    NSString *tribeId;
    NSString *fromUid;
    NSDate *dtime;
    NSString *content;
    int contentType;
    int flag;
    int msgstate;
    int index;
}

@property(nonatomic) int index; // @synthesize index;
@property(nonatomic) int msgstate; // @synthesize msgstate;
@property(nonatomic) int flag; // @synthesize flag;
@property(nonatomic) int contentType; // @synthesize contentType;
@property(copy, nonatomic) NSString *content; // @synthesize content;
@property(retain, nonatomic) NSDate *dtime; // @synthesize dtime;
@property(copy, nonatomic) NSString *fromUid; // @synthesize fromUid;
@property(copy, nonatomic) NSString *tribeId; // @synthesize tribeId;
@property(nonatomic) int msgType; // @synthesize msgType;
@property(copy, nonatomic) NSNumber *msgId; // @synthesize msgId;
- (void)dealloc;

@end

