//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class TBNavigationItem;

@interface UIViewController (TBNaviBar)
+ (BOOL)tbNeedNavibar;
- (void)setTbNavigationItem:(id)arg1;
- (id)tbNavibar;
- (BOOL)isShowMoreBadge;
- (void)setTbBottomLineHidden:(BOOL)arg1;
- (void)setTBNaviBarBlurViewHidden:(BOOL)arg1;
- (void)moreItemClicked:(id)arg1;
- (void)backItemClicked:(id)arg1;
- (id)moreButtonItem;
- (id)backButtonItem;
- (void)setTbNavibarHidden:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) unsigned int tbNavibarHeight;
@property(nonatomic) BOOL tbNavibarHidden;
@property(readonly, nonatomic) TBNavigationItem *tbNavigationItem;
@end

