//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

#import "YYZPluginProtocol.h"

@interface UIWebView (YYZUIWebView) <YYZPluginProtocol>
+ (id)instance;
- (void)autoCheckAndDoUpdate;
- (BOOL)checkIsLocalFileProtocol:(id)arg1;
- (id)removeTagOfLoadingPage:(id)arg1;
- (BOOL)checkIshveParam:(id)arg1 withParamValue:(id)arg2;
- (void)load404PageHtml:(id)arg1;
- (void)loadWaittingHtml:(id)arg1;
- (void)loadHtml:(id)arg1 withLoadUrl:(id)arg2;
- (id)replaceString:(id)arg1 withSrc:(id)arg2 withTarget:(id)arg3;
- (id)removeHeaderCode:(id)arg1;
- (void)updateLstModifiedTime:(id)arg1;
- (void)doSave:(id)arg1 withName:(id)arg2;
- (void)saveHtmlToFile:(id)arg1 withName:(id)arg2 withIsSvImg:(BOOL)arg3;
- (id)tagImageForNSURLCacheInHtml:(id)arg1 withMaxCount:(int)arg2;
- (id)getTimerKeyForSelf;
- (void)removeTimer;
- (void)holdTimer:(id)arg1;
- (id)getTimer;
- (void)stopListenRequest;
- (void)startListenRequest;
- (id)getRequestKeyForSelf;
- (void)removeRequest;
- (void)holdRequest:(id)arg1;
- (id)getRequest;
- (void)cancleReqeust;
- (void)doFailedListenRequest;
- (id)getUrlKeyForCache:(id)arg1;
- (id)readHtmlFromCache:(id)arg1 withCacheStrage:(int)arg2 withExpiredTime:(float)arg3;
- (BOOL)isYYZRequest:(id)arg1;
- (BOOL)loadRequestWithOption:(id)arg1 setIsCountPV:(BOOL)arg2 withCacheOption:(struct YYZCacheOption)arg3 withIsYYZRequest:(BOOL)arg4 withCacheStrage:(int)arg5;
- (id)addDefaultParamForURL:(id)arg1;
- (BOOL)loadBySystemDefault:(id)arg1 withUrl:(id)arg2;
- (BOOL)beforeLoadRequestProcess:(id)arg1 withIsYYZ:(BOOL)arg2;
- (void)requestFailed:(id)arg1;
- (void)loadUrl:(id)arg1 isPost:(BOOL)arg2;
- (void)load404:(id)arg1;
- (void)loading:(id)arg1;
- (void)loading;
- (BOOL)isLoadingPage:(id)arg1;
- (id)getRequestUrl;
- (BOOL)loadRequest:(id)arg1 withCacheOption:(struct YYZCacheOption)arg2 setIsCountPV:(BOOL)arg3;
- (BOOL)loadRequest:(id)arg1 isYYZPageRequest:(int)arg2 setCacheStrage:(int)arg3 setIsCountPV:(BOOL)arg4;
- (void)initYYZModule;
@end

