//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UserDetailReq : NSObject
{
    NSString *_realName;
    NSString *_identifyCard;
    NSString *_phoneNumber;
    BOOL _isCreateUser;
    int _protectQuestionId;
    NSString *_protectQuestionAnswer;
}

@property(retain, nonatomic) NSString *protectQuestionAnswer; // @synthesize protectQuestionAnswer=_protectQuestionAnswer;
@property(nonatomic) int protectQuestionId; // @synthesize protectQuestionId=_protectQuestionId;
@property(nonatomic) BOOL isCreateUser; // @synthesize isCreateUser=_isCreateUser;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *identifyCard; // @synthesize identifyCard=_identifyCard;
@property(retain, nonatomic) NSString *realName; // @synthesize realName=_realName;
- (void).cxx_destruct;

@end

