//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WVUserConfig : NSObject
{
    BOOL _useSafeSecert;
    BOOL _openLog;
    NSString *_appKey;
    NSString *_appSecrect;
    NSString *_wvTTid;
    int _environment;
    NSString *_sid;
    NSString *_eCode;
}

+ (BOOL)isOpenWindVaneLog;
+ (void)openWindVaneLog;
+ (id)eCode;
+ (void)setEcode:(id)arg1;
+ (id)sid;
+ (void)setSid:(id)arg1;
+ (int)environment;
+ (void)setEnvironment:(int)arg1;
+ (BOOL)isUseSafeSecert;
+ (void)useSafeSecert:(BOOL)arg1;
+ (id)ttid;
+ (void)setTTid:(id)arg1;
+ (id)appSecrect;
+ (id)appKey;
+ (void)setAppKey:(id)arg1 secrect:(id)arg2;
+ (id)instance;
@property(nonatomic) BOOL openLog; // @synthesize openLog=_openLog;
@property(retain, nonatomic) NSString *eCode; // @synthesize eCode=_eCode;
@property(retain, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(nonatomic) int environment; // @synthesize environment=_environment;
@property(nonatomic) BOOL useSafeSecert; // @synthesize useSafeSecert=_useSafeSecert;
@property(retain, nonatomic) NSString *wvTTid; // @synthesize wvTTid=_wvTTid;
@property(retain, nonatomic) NSString *appSecrect; // @synthesize appSecrect=_appSecrect;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
- (void).cxx_destruct;

@end

