//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MAZeroingWeakRef, NSArray, NSMutableDictionary, NSNumber, NSString;

@interface WXRoamingRequest : NSObject
{
    MAZeroingWeakRef *_weakRefDelegate;
    BOOL _isDoingSubRequest;
    BOOL _isProcessingData;
    BOOL _isSlice;
    BOOL _resultNeedAESDecode;
    id <WXRoamingKitDelegate> _delegate;
    int _reqType;
    int _reqStatus;
    int _reqResultCode;
    NSNumber *_sliceDate;
    NSString *_targetId;
    NSMutableDictionary *_dicReqParam;
    NSArray *_arySubRequests;
    NSString *_keyForAES;
    NSMutableDictionary *_dicResultParam;
}

@property(retain, nonatomic) NSMutableDictionary *dicResultParam; // @synthesize dicResultParam=_dicResultParam;
@property(copy, nonatomic) NSString *keyForAES; // @synthesize keyForAES=_keyForAES;
@property(nonatomic) BOOL resultNeedAESDecode; // @synthesize resultNeedAESDecode=_resultNeedAESDecode;
@property(retain, nonatomic) NSArray *arySubRequests; // @synthesize arySubRequests=_arySubRequests;
@property(retain, nonatomic) NSMutableDictionary *dicReqParam; // @synthesize dicReqParam=_dicReqParam;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(retain, nonatomic) NSNumber *sliceDate; // @synthesize sliceDate=_sliceDate;
@property(nonatomic) BOOL isSlice; // @synthesize isSlice=_isSlice;
@property(nonatomic) BOOL isProcessingData; // @synthesize isProcessingData=_isProcessingData;
@property(nonatomic) BOOL isDoingSubRequest; // @synthesize isDoingSubRequest=_isDoingSubRequest;
@property(nonatomic) int reqResultCode; // @synthesize reqResultCode=_reqResultCode;
@property(nonatomic) int reqStatus; // @synthesize reqStatus=_reqStatus;
@property(nonatomic) int reqType; // @synthesize reqType=_reqType;
@property(nonatomic) id <WXRoamingKitDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;

@end

