/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface PFCloud : XXUnknownSuperclass {
}
+(id)callFunction:(id)function withParameters:(id)parameters error:(id*)error;
+(id)callFunction:(id)function withParameters:(id)parameters;
+(void)callFunctionInBackground:(id)background withParameters:(id)parameters block:(id)block;
+(void)callFunctionInBackground:(id)background withParameters:(id)parameters target:(id)target selector:(SEL)selector;
+(id)callFunctionAsync:(id)async withParameters:(id)parameters;
@end

