/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"
#import "DamnVulnerableIOSApp-Structs.h"

@class PFSignUpViewController, PF_MBProgressHUD, NSArray, PFLogInView;
@protocol PFLogInViewControllerDelegate;

@interface PFLogInViewController : XXUnknownSuperclass <UITextFieldDelegate> {
	PF_MBProgressHUD* hud;
	int fields;
	PFLogInView* logInView;
	id<PFLogInViewControllerDelegate> delegate;
	NSArray* facebookPermissions;
	PFSignUpViewController* signUpController;
}
@property(retain, nonatomic) PFSignUpViewController* signUpController;
@property(retain, nonatomic) NSArray* facebookPermissions;
@property(assign, nonatomic) id<PFLogInViewControllerDelegate> delegate;
@property(readonly, assign, nonatomic) PFLogInView* logInView;
@property(assign, nonatomic) int fields;
-(void).cxx_destruct;
-(void)cancelLogIn;
-(void)showDefaultLoginError:(id)error title:(id)title message:(id)message;
-(void)failLogInWithError:(id)error title:(id)title message:(id)message;
-(void)failLogInWithError:(id)error;
-(void)failLogInNoConnection;
-(void)succeedLogInUser:(id)user;
-(void)signUp;
-(void)logIn;
-(void)logInUsingTwitter;
-(void)logInUsingFacebook;
-(void)requestPasswordReset:(id)reset;
-(void)displayEmailRequestDialog;
-(void)dismissKeyboard;
-(void)dismiss;
-(void)setupHandlers;
-(void)setup;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
-(BOOL)textFieldShouldReturn:(id)textField;
-(int)preferredStatusBarStyle;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)loadView;
-(id)initWithCoder:(id)coder;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)init;
@end

