/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface PFMemoryMappedFile : XXUnknownSuperclass {
	int fileHandle;
	unsigned long fileSize;
	void* mappedAddress;
}
-(id)data;
-(void)dealloc;
-(id)initWithContentsAtPath:(id)path;
@end

