/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface PFMulticastDelegate : XXUnknownSuperclass {
	NSMutableArray* callbacks;
}
-(void)dealloc;
-(void)clear;
-(void)invoke:(id)invoke error:(id)error;
-(void)unsubscribe:(id)unsubscribe;
-(void)subscribe:(id)subscribe;
-(id)init;
@end

