/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UITextField, NSString;

__attribute__((visibility("hidden")))
@interface RuntimeManipulationDetailsVC : XXUnknownSuperclass {
	UITextField* _usernameTextField;
	UITextField* _passwordTextField;
	NSString* _urlToLoad;
}
@property(retain, nonatomic) NSString* urlToLoad;
@property(retain, nonatomic) UITextField* passwordTextField;
@property(retain, nonatomic) UITextField* usernameTextField;
-(void).cxx_destruct;
-(void)readTutorialTapped:(id)tapped;
-(void)showLoginFailureAlert;
-(void)pushSuccessPage;
-(BOOL)isLoginValidated;
-(void)loginMethod2Tapped:(id)tapped;
-(void)loginMethod1Tapped:(id)tapped;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

