/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIImageView, UILabel;
@protocol NSObject;

@interface _HistorySectionView : XXUnknownSuperclass {
@private
	BOOL _expand;
	UILabel* _titleLabel;
	UIView* _labelView;
	UIImageView* _lineView;
	UIImageView* _arrowImageView;
	id<NSObject> _touchHandler;
	SEL _selector;
}
@property(assign, nonatomic) SEL selector;
@property(assign, nonatomic) __weak id<NSObject> touchHandler;
@property(assign, nonatomic) BOOL expand;
@property(retain, nonatomic) UIImageView* arrowImageView;
@property(retain, nonatomic) UIImageView* lineView;
@property(retain, nonatomic) UIView* labelView;
@property(retain, nonatomic) UILabel* titleLabel;
-(void).cxx_destruct;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)addTouchHandler:(id)handler selector:(SEL)selector;
-(void)setSectionExpand:(BOOL)expand animated:(BOOL)animated;
-(id)initWithFrame:(CGRect)frame;
-(void)_createSubview;
@end

