/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "Portal-Structs.h"
#import "UITableViewDelegate.h"
#import "ACPRepaymentButtonDelegate.h"
#import "AssetsBaseController.h"

@class ACPRepaymentButtonView, ALPTableView;

@interface ACPHomePageViewController : AssetsBaseController <UITableViewDelegate, UITableViewDataSource, ACPRepaymentButtonDelegate> {
@private
	ACPRepaymentButtonView* _payButton;
	ALPTableView* _tableView;
}
@property(retain, nonatomic) ALPTableView* tableView;
@property(retain, nonatomic) ACPRepaymentButtonView* payButton;
-(void).cxx_destruct;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)initSecSectionTableCell:(id)cell withIndex:(int)index;
-(void)initOPSectionCell:(id)cell;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)payButtonClicked;
-(void)billButtonClicked;
-(void)back;
-(void)initPayButton;
-(void)initTableView;
-(void)setPayButtonHidden;
-(void)queryInfo;
-(void)viewWillAppear:(BOOL)view;
-(void)updateData:(id)data;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

