/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ALPPassGuider.h"

@class UIImageView;

@interface ALPBoardingPassGuider : ALPPassGuider {
@private
	BOOL _firstTapping;
	UIImageView* _introduceImageView;
}
@property(retain, nonatomic) UIImageView* introduceImageView;
-(void).cxx_destruct;
-(void)queryRPCPassListDataComplete:(id)complete error:(id)error;
-(void)queryPassListFromRPC;
-(void)queryPassListFromCache;
-(void)addTravelClicked;
-(void)reloadData;
-(id)cellForRowAtIndex:(id)index;
-(void)startWebApp;
-(void)selectRowAtIndexPath:(id)indexPath;
-(void)handleTap:(id)tap;
-(id)createIntroductView;
-(id)createGuideView;
-(void)start;
-(id)init;
@end

