/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "Portal-Structs.h"
#import "UITableViewDelegate.h"
#import "AssetsBaseController.h"

@class ALPTableView, UIView;

@interface ALPCreditOpenSuccessViewController : AssetsBaseController <UITableViewDataSource, UITableViewDelegate> {
	ALPTableView* _tableView;
	UIView* _titleView;
}
-(void).cxx_destruct;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)fillDisplayCell:(id)cell row:(int)row;
-(void)initResultCell:(id)cell;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)managerBtnClicked;
-(void)didReceiveMemoryWarning;
-(void)initTableView;
-(void)initTitleView;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

