/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import "CPTPlotSpaceAnnotation.h"

@class UIImage;

@interface ALPFundAnnotation : CPTPlotSpaceAnnotation {
	UIImage* _leftImage;
	UIImage* _rightImage;
@private
	BOOL _isLeft;
}
@property(assign, nonatomic) BOOL isLeft;
-(void).cxx_destruct;
-(void)positionContentLayer;
-(void)removeTriange;
-(void)dealloc;
@end

