/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AssetsBaseController.h"

@class ALPFundManagerViewController;

@interface ALPFundMiddleViewController : AssetsBaseController {
	BOOL _hasGotoNextPage;
@private
	ALPFundManagerViewController* _fundManagerController;
}
-(void).cxx_destruct;
-(void)didReceiveMemoryWarning;
-(void)gotoAndPopSelf:(id)aSelf;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)backAction;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

