/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ALPFundScrollCellProtocol.h"
#import "ALPTextDelegate.h"
#import "ALPCell.h"

@class NSNumberFormatter, ALPCountingLabel;
@protocol ALPCellDidClick;

@interface ALPFundCommonCell : ALPCell <ALPFundScrollCellProtocol, ALPTextDelegate> {
	NSNumberFormatter* _rateFormatter;
@private
	ALPCountingLabel* _accmuAmountLabel;
	ALPCountingLabel* _sevenDaysRatLabel;
	ALPCountingLabel* _sevenDaysIncomeLabel;
	ALPCountingLabel* _monthIncomeLabel;
	id<ALPCellDidClick> _clickDelegate;
}
@property(assign, nonatomic) __weak id<ALPCellDidClick> clickDelegate;
@property(retain, nonatomic) ALPCountingLabel* monthIncomeLabel;
@property(retain, nonatomic) ALPCountingLabel* sevenDaysIncomeLabel;
@property(retain, nonatomic) ALPCountingLabel* sevenDaysRatLabel;
@property(retain, nonatomic) ALPCountingLabel* accmuAmountLabel;
-(void).cxx_destruct;
-(void)handleTap:(id)tap;
-(float)cellHeight;
-(void)cellFinishAppear;
-(void)cellFinishDisappear;
-(void)cellStartToAppear:(id)appear;
-(id)formatNumber:(id)number number:(id)number2;
-(void)updateAmounts:(id)amounts sevenRat:(id)rat sevenDays:(id)days month:(id)month;
-(id)init;
@end

