/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AMapRoute;

@interface AMapNavigationSearchResponse : XXUnknownSuperclass {
@private
	int _count;
	AMapRoute* _route;
}
@property(retain, nonatomic) AMapRoute* route;
@property(assign, nonatomic) int count;
-(void).cxx_destruct;
@end

