/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableData;

@interface AMapSearchRequest : XXUnknownSuperclass {
@private
	NSString* _url;
	NSString* _key;
	NSString* _method;
	NSMutableData* _postData;
	int _timeout;
}
@property(retain, nonatomic) NSString* key;
@property(assign, nonatomic) int timeout;
@property(retain, nonatomic) NSMutableData* postData;
@property(retain, nonatomic) NSString* method;
@property(retain, nonatomic) NSString* url;
-(void).cxx_destruct;
-(id)initWithPostData:(id)postData timeout:(int)timeout key:(id)key;
@end

