/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface AMapPhoto : XXUnknownSuperclass {
@private
	NSString* _url;
	NSString* _title;
	NSString* _provider;
}
@property(retain, nonatomic) NSString* provider;
@property(retain, nonatomic) NSString* url;
@property(retain, nonatomic) NSString* title;
+(id)photoWithTitle:(id)title url:(id)url provider:(id)provider;
-(void).cxx_destruct;
-(id)description;
@end

