/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AMapReGeocode;

@interface AMapReGeocodeSearchResponse : XXUnknownSuperclass {
@private
	AMapReGeocode* _regeocode;
}
@property(retain, nonatomic) AMapReGeocode* regeocode;
-(void).cxx_destruct;
@end

