/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Portal-Structs.h"

@class NSString, CustomStatusBar, UIWebView;

@interface AppLoader : XXUnknownSuperclass {
@private
	BOOL isLogin;
	NSString* tokenID;
	NSString* clientID;
	NSString* sessionID;
	CustomStatusBar* statusBar;
	UIWebView* currentWebView;
}
@property(retain, nonatomic) NSString* clientID;
@property(retain, nonatomic) NSString* sessionID;
@property(assign) BOOL isLogin;
@property(retain, nonatomic) NSString* tokenID;
@property(assign, nonatomic) UIWebView* currentWebView;
@property(retain, nonatomic) CustomStatusBar* statusBar;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedInstance;
-(id)autorelease;
-(oneway void)release;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
-(id)wrapProperty:(id)property;
-(void)loginNotify:(id)notify;
-(void)logoutNotify:(id)notify;
-(id)createProcessor:(id)processor withBundleLoader:(id)bundleLoader;
@end

