/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface APStyleBaseTableViewCell : XXUnknownSuperclass {
	NSDictionary* _data;
	int _height;
}
@property(retain, nonatomic) NSDictionary* data;
@property(assign, nonatomic) int height;
-(void)drawRect:(CGRect)rect;
-(void)loadData;
-(void)dealloc;
@end

