/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "Portal-Structs.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"


@protocol APStretchFieldDelegate <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
@optional
-(void)stretchField:(id)field willAdjustTableView:(id)view withRowNumber:(int)rowNumber;
-(void)stretchField:(id)field didCollapseTableView:(id)view fromControl:(id)control;
-(void)stretchField:(id)field willCollapseTableView:(id)view fromControl:(id)control;
-(void)stretchField:(id)field didExpandTableView:(id)view fromControl:(id)control;
-(void)stretchField:(id)field willExpandTableView:(id)view fromControl:(id)control;
-(void)stretchField:(id)field didBeTouchedFromControl:(id)control;
@end

