/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView;

@interface APTableLineView : XXUnknownSuperclass {
	NSString* charString;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) NSString* charString;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

