/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface APWidgetMsg : XXUnknownSuperclass {
@private
	NSString* _widgetId;
	int _temporary;
	int _persistence;
	NSString* _style;
}
@property(retain, nonatomic) NSString* style;
@property(assign, nonatomic) int persistence;
@property(assign, nonatomic) int temporary;
@property(retain, nonatomic) NSString* widgetId;
-(void).cxx_destruct;
@end

