/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ALPPickerDelegate.h"
#import "AssetsBaseController.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "Portal-Structs.h"
#import "UIActionSheetDelegate.h"

@class UIView, ALPPickerView, CardDetailFunctionManager, AssetBankCardItem, AssetsBaseTableView, UITableView;

@interface AssetBankCardDetailViewController : AssetsBaseController <UITableViewDataSource, UITableViewDelegate, UIActionSheetDelegate, UIAlertViewDelegate, ALPPickerDelegate> {
	AssetBankCardItem* _bankCardItem;
	AssetsBaseTableView* _tableView;
	ALPPickerView* _pickerView;
	UIView* _clipView;
	CardDetailFunctionManager* _detailManager;
@private
	BOOL _isCurrentController;
}
@property(readonly, assign, nonatomic) CardDetailFunctionManager* detailManager;
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(readonly, assign, nonatomic) AssetBankCardItem* bankCardItem;
-(void).cxx_destruct;
-(void)selectedPickerView:(id)view;
-(void)cancelPickerView:(id)view;
-(id)pickerView:(id)view titleForRow:(int)row forComponent:(int)component;
-(int)pickerView:(id)view numberOfRowsInComponent:(int)component;
-(int)numberOfComponentsInPickerView:(id)pickerView;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)gotoBankBillQuery;
-(void)gotoEmailBillQuery;
-(void)cellActionForItem:(id)item;
-(void)_bankMessageSendWithItem:(id)item;
-(void)_bankPhoneCallWithItem:(id)item;
-(void)_hidePicker;
-(void)_showPicker;
-(void)_goAddCard;
-(void)_goSearchMap;
-(void)_cardRepaymentWithItem:(id)item;
-(void)_cardChargeWithItem:(id)item;
-(void)_cardWithDrawWithItem:(id)item;
-(void)_queryCardBalanceWithItem:(id)item;
-(void)_queryCardBalanceWithPassword:(id)password;
-(void)_showQueryCardBalanceErrorAlertWithResponse:(id)response;
-(void)_showPasswordAlertView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)footStringInSection:(int)section;
-(void)alertValueDidChange:(id)alertValue;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)backAction:(id)action;
-(void)viewDidLoad;
-(id)initWithCardItem:(id)cardItem;
-(void)_readCacheAndUpdate;
-(BOOL)_hasHistoryLayout;
@end

