/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

@interface AssetTableViewRicherCell : XXUnknownSuperclass {
@private
	UILabel* _cellTitle;
	UILabel* _cellContent;
}
@property(retain, nonatomic) UILabel* cellContent;
@property(retain, nonatomic) UILabel* cellTitle;
-(void).cxx_destruct;
-(void)setContent:(id)content;
-(void)setTitle:(id)title;
-(float)cellHeight;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

