/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ALPTableView.h"
#import "Portal-Structs.h"


@interface AssetsBaseTableView : ALPTableView {
}
@property(assign, nonatomic) int tableViewStyle;
-(float)heightForHeaderInSectionSegment:(int)sectionSegment;
-(float)heightForHeaderInSectionDefault:(int)sectionDefault;
-(void)hideTailButton:(BOOL)button;
-(void)enableTailButton:(BOOL)button;
-(CGPoint)fitContentSizeFieldWillBeginEditing:(id)fitContentSizeField;
-(CGPoint)CGPointFromRectOrigin:(CGRect)rectOrigin;
-(void)setTableFooterView:(id)view;
-(void)layoutCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)initWithFrame:(CGRect)frame style:(int)style;
@end

