/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BCView : XXUnknownSuperclass {
}
-(void)layoutSubviews;
-(void)releaseUI;
-(void)initUI;
-(id)initWithFrame:(CGRect)frame;
@end

