/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, CALayer, ScoreView;

@interface BigSoreView : XXUnknownSuperclass {
@private
	CALayer* _ringLayer;
	ScoreView* _scoreView;
	UILabel* _textLabel;
	BOOL _errState;
}
@property(assign, nonatomic) BOOL errState;
-(void).cxx_destruct;
-(void)doAnimationResult;
-(void)setNumber:(id)number;
-(void)setIsErrState:(BOOL)state;
-(void)settCheckingText:(id)text;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(id)init;
@end

