/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PieChartDelegate.h"
#import "BLMLViewController.h"
#import "BLRefreshDelegate.h"

@class NSArray, BillPieData, BillPieTimeView, UIView, BillPieInfomationView, BillPieChartView, BillPieTitleView, BillPieTouchView, NSString, BLRefreshView, NSDateComponents, DTRpcAsyncCaller, UIButton, NSMutableArray;

@interface BillPieViewController : BLMLViewController <PieChartDelegate, BLRefreshDelegate> {
@private
	BOOL _bBackToBillList;
	BOOL _outIn;
	BOOL _bShouldShowBigIndicator;
	BOOL _supportRealtimeEbill;
	BOOL _jumpFromPushMonthFirst;
	BillPieTitleView* _billPieTitleView;
	BillPieTimeView* _billPieTimeView;
	UIView* _pieContainer;
	BillPieChartView* _pieChartView;
	BillPieInfomationView* _infomationView;
	BLRefreshView* _refreshView;
	BillPieTouchView* _contentView;
	UIView* _futureMonthTipView;
	UIButton* _tipButton;
	NSMutableArray* _outValueArray;
	NSMutableArray* _outColorArray;
	NSMutableArray* _inValueArray;
	NSMutableArray* _inColorArray;
	NSArray* _defaultColorArray;
	NSDateComponents* _currentDate;
	BillPieData* _billPieData;
	int _billStatus;
	int _userClickedType;
	int _selectIndex;
	int _redoYear;
	int _redoMonth;
	int _redoDay;
	int _redoIsFirst;
	DTRpcAsyncCaller* _networkCaller;
	int _curYear;
	int _curMonth;
	NSString* _jumpYear;
	NSString* _jumpMonth;
}
@property(assign, nonatomic) BOOL jumpFromPushMonthFirst;
@property(retain, nonatomic) NSString* jumpMonth;
@property(retain, nonatomic) NSString* jumpYear;
@property(assign, nonatomic) int curMonth;
@property(assign, nonatomic) int curYear;
@property(assign, nonatomic) BOOL supportRealtimeEbill;
@property(retain, nonatomic) DTRpcAsyncCaller* networkCaller;
@property(assign, nonatomic) BOOL bShouldShowBigIndicator;
@property(assign, nonatomic) int redoIsFirst;
@property(assign, nonatomic) int redoDay;
@property(assign, nonatomic) int redoMonth;
@property(assign, nonatomic) int redoYear;
@property(assign, nonatomic) int selectIndex;
@property(assign, nonatomic) int userClickedType;
@property(assign, nonatomic) BOOL outIn;
@property(assign, nonatomic) int billStatus;
@property(retain, nonatomic) BillPieData* billPieData;
@property(retain, nonatomic) NSDateComponents* currentDate;
@property(retain, nonatomic) NSArray* defaultColorArray;
@property(retain, nonatomic) NSMutableArray* inColorArray;
@property(retain, nonatomic) NSMutableArray* inValueArray;
@property(retain, nonatomic) NSMutableArray* outColorArray;
@property(retain, nonatomic) NSMutableArray* outValueArray;
@property(retain, nonatomic) UIButton* tipButton;
@property(retain, nonatomic) UIView* futureMonthTipView;
@property(retain, nonatomic) BillPieTouchView* contentView;
@property(retain, nonatomic) BLRefreshView* refreshView;
@property(retain, nonatomic) BillPieInfomationView* infomationView;
@property(retain, nonatomic) BillPieChartView* pieChartView;
@property(retain, nonatomic) UIView* pieContainer;
@property(retain, nonatomic) BillPieTimeView* billPieTimeView;
@property(retain, nonatomic) BillPieTitleView* billPieTitleView;
@property(assign, nonatomic) BOOL bBackToBillList;
+(id)getDateComponentsFromDate:(id)date;
-(void).cxx_destruct;
-(void)renderAnimateFinish:(id)finish;
-(void)renderAnimateBegin:(id)begin;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onRefresh:(id)refresh;
-(void)onCenterClick:(id)click;
-(void)loadBillPieView:(BOOL)view;
-(void)selectedFinish:(id)finish index:(int)index percent:(float)percent;
-(void)viewWillDestroy;
-(void)billButtonOnClicked;
-(void)comfirmInfimum:(id)infimum;
-(void)consumeMannerButtonOnClicked;
-(void)changeArrayValue:(id)value setIndex:(int)index;
-(void)sortValueArr:(id)arr colorArr:(id)arr2 setsourceArray:(id)array;
-(void)makeBillPieData:(id)data;
-(void)showNetworkData:(id)data;
-(void)firstTimeRightButtonClicked;
-(void)getNetworkData:(int)data setMonth:(int)month setDay:(int)day setType:(BOOL)type;
-(void)networkRedo;
-(void)getDefaultNetworkData;
-(void)readShowDiskData:(BOOL)data;
-(void)buildCacheFilePath;
-(void)rightButtonClicked;
-(void)leftButtonClicked;
-(void)removeTipLable;
-(void)addTipLable;
-(void)infomationButtonClicked;
-(void)tipInfoDisappear;
-(void)tipsInfoButtonClicked;
-(void)createUIControl;
-(id)createTimeView:(int)view setMonth:(int)month;
-(void)addTimeView:(id)view;
-(void)saveSupportRealtimeEbillFromDisk;
-(void)getSupportRealtimeEbillFromDisk;
-(void)getPushJumpNetworkData;
-(void)viewDidLoad;
-(void)setJumpToYear:(id)year month:(id)month;
-(void)dealloc;
@end

