/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DTLauncherWidgetGroup.h"

@class NSString, BillAppRootController;
@protocol DTLauncher;

@interface BillAppWidget : XXUnknownSuperclass <DTLauncherWidgetGroup> {
@private
	id<DTLauncher> launcher;
	NSString* name;
	BillAppRootController* _rootViewController;
}
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) __weak id<DTLauncher> launcher;
@property(retain, nonatomic) BillAppRootController* rootViewController;
-(void).cxx_destruct;
-(void)refresh;
-(id)allWidgets;
-(id)indicatorView;
-(id)contentViewController;
-(void)createRootController;
-(id)init;
@end

