/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class NSDictionary, NSMutableArray, UIView;

@interface BLDetailAdapter : XXUnknownSuperclass <UIAlertViewDelegate> {
@private
	NSMutableArray* _detailList;
	NSDictionary* _requestInfo;
	UIView* _bindView;
	NSDictionary* _responseInfo;
}
@property(retain, nonatomic) NSDictionary* responseInfo;
@property(assign, nonatomic) __weak UIView* bindView;
@property(retain, nonatomic) NSDictionary* requestInfo;
@property(retain, nonatomic) NSMutableArray* detailList;
-(void).cxx_destruct;
-(id)templateList:(id)list;
-(BOOL)matchActionArr:(id)arr actionArr:(id)arr2;
-(id)actionInfo:(id)info;
-(void)helperFacade:(id)facade target:(id)target data:(id)data index:(int)index;
-(id)init;
-(void)dealloc;
@end

