/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BLLWImageStyle.h"
#import "NSObject.h"
#import "Portal-Structs.h"
#import "BLLWStyle.h"

@class UIColor;

@protocol BLLWImageStyle <NSObject>
@property(assign, nonatomic) BOOL clipToBounds;
@property(retain, nonatomic) UIColor* bgColor;
@property(assign, nonatomic) JMergePoint capInsets;
@property(assign, nonatomic) int contentMode;
@end

@interface BLLWImageStyle : BLLWStyle <BLLWImageStyle> {
@private
	BOOL _clipToBounds;
	int _contentMode;
	UIColor* _bgColor;
	JMergePoint _capInsets;
}
@property(assign, nonatomic) BOOL clipToBounds;
@property(retain, nonatomic) UIColor* bgColor;
@property(assign, nonatomic) JMergePoint capInsets;
@property(assign, nonatomic) int contentMode;
-(void).cxx_destruct;
-(void)defaultStyle;
-(id)initWithConfig:(id)config;
@end

