/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BLCell.h"

@class UILabel;

@interface BLPaymentCell : BLCell {
@private
	UILabel* typeLabel;
	UILabel* balanceLabel;
	UILabel* dateLabel;
	UILabel* moneyLabel;
}
@property(retain, nonatomic) UILabel* moneyLabel;
@property(retain, nonatomic) UILabel* dateLabel;
@property(retain, nonatomic) UILabel* balanceLabel;
@property(retain, nonatomic) UILabel* typeLabel;
-(void).cxx_destruct;
-(void)onLayout;
-(void)configData;
-(id)stringFromDate:(id)date;
-(id)dateFromString:(id)string;
-(void)releaseUI;
-(void)initUI;
@end

