/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCACActionView.h"

@class UIImageView;

@interface CCACFooterActionView : CCACActionView {
@private
	UIImageView* _arrow;
}
@property(assign, nonatomic) __weak UIImageView* arrow;
-(void).cxx_destruct;
-(void)refreshTitle:(id)title;
-(int)currentState:(id)state;
-(id)footerActionLayout:(id)layout;
-(void)refreshWithData:(id)data Layout:(id)layout Action:(int)action;
-(id)init;
@end

