/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import "DTUIAlertView.h"

@class CDVNotification, NSString;

@interface CDVAlertView : DTUIAlertView {
@private
	CDVNotification* caller;
	NSString* callbackId;
}
@property(retain, nonatomic) CDVNotification* caller;
@property(copy, nonatomic) NSString* callbackId;
-(void)dealloc;
@end

