/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "APViewController2.h"
#import "APNavigationBarDelegate.h"
#import "Portal-Structs.h"
#import "CDVCommandDelegate.h"
#import "UIWebViewDelegate.h"

@class NSDictionary, NSArray, CDVLocalStorage, WebappRuntime, NSString, CDVCordovaView, APNavigationBar, UIImageView, UIActivityIndicatorView, NSMutableDictionary, CDVWhitelist, UIViewController;

@interface CDVViewController : APViewController2 <UIWebViewDelegate, CDVCommandDelegate, APNavigationBarDelegate> {
	APNavigationBar* navigationBar;
@private
	BOOL loadFromString;
	BOOL useSplashScreen;
	BOOL isLoading;
	BOOL isPush;
	BOOL isTitleIcon;
	CDVCordovaView* webView;
	NSArray* supportedOrientations;
	NSDictionary* pluginsMap;
	CDVWhitelist* whitelist;
	NSDictionary* settings;
	UIImageView* imageView;
	UIActivityIndicatorView* activityView;
	id<CDVCommandDelegate> commandDelegate;
	NSString* wwwFolderName;
	NSString* startPage;
	NSString* invokeString;
	UIViewController* parentNavigationController;
	NSString* backEvent;
	NSString* centerEvent;
	NSString* rightEvent;
	NSString* rightEvent1;
	WebappRuntime* runtime;
	CDVLocalStorage* storage;
	NSMutableDictionary* pluginObjects;
	NSDictionary* propertyDict;
}
@property(retain, nonatomic) NSMutableDictionary* pluginObjects;
@property(assign, nonatomic) BOOL isTitleIcon;
@property(retain, nonatomic) NSDictionary* propertyDict;
@property(assign, nonatomic) BOOL isPush;
@property(assign, nonatomic) UIViewController* parentNavigationController;
@property(retain, nonatomic) CDVLocalStorage* storage;
@property(assign, nonatomic) WebappRuntime* runtime;
@property(assign, nonatomic) BOOL isLoading;
@property(retain, nonatomic) NSString* rightEvent1;
@property(retain, nonatomic) NSString* rightEvent;
@property(retain, nonatomic) NSString* centerEvent;
@property(retain, nonatomic) NSString* backEvent;
@property(copy, nonatomic) NSString* startPage;
@property(copy, nonatomic) NSString* wwwFolderName;
@property(assign, nonatomic) id<CDVCommandDelegate> commandDelegate;
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) UIActivityIndicatorView* activityView;
@property(assign, nonatomic) BOOL useSplashScreen;
@property(copy, nonatomic) NSString* invokeString;
@property(assign, nonatomic) BOOL loadFromString;
@property(retain, nonatomic) NSArray* supportedOrientations;
@property(retain, nonatomic) CDVWhitelist* whitelist;
@property(retain, nonatomic) NSDictionary* settings;
@property(retain, nonatomic) NSDictionary* pluginsMap;
@property(retain, nonatomic) CDVCordovaView* webView;
+(id)cordovaVersion;
+(id)getBundlePlist:(id)plist;
+(id)deviceProperties;
+(id)applicationDocumentsDirectory;
+(id)resolveImageResource:(id)resource;
+(BOOL)isIPad;
+(id)wrapProperty:(id)property;
+(id)contextInitScript;
-(void)setAPNavigationBar:(id)bar;
-(void)dealloc;
-(void)onAppDidEnterBackground:(id)onApp;
-(void)onAppDidBecomeActive:(id)onApp;
-(void)onAppWillEnterForeground:(id)onApp;
-(void)onAppWillResignActive:(id)onApp;
-(void)onAppWillTerminate:(id)onApp;
-(id)appURLScheme;
-(id)getCommandInstance:(id)instance;
-(void)registerPlugin:(id)plugin withClassName:(id)className;
-(BOOL)execute:(id)execute;
-(void)flushCommandQueue;
-(int)executeQueuedCommands;
-(void)receivedOrientationChange;
-(void)showSplashScreen;
-(id)pathForResource:(id)resource;
-(void)javascriptAlert:(id)alert;
-(void)safeDismiss:(BOOL)dismiss;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)webViewDidStartLoad:(id)webView;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)initJavaScriptApi:(id)api;
-(BOOL)checkLocalHost:(id)host;
-(void)initNavigationBar;
-(void)rightClick1:(id)a1;
-(void)rightClick:(id)click;
-(void)leftClick:(id)click;
-(void)centerClick:(id)click;
-(id)getTitleButton;
-(void)setNavigationIcon:(id)icon imageName:(id)name;
-(void)setNavigationEvent:(id)event action:(id)action;
-(id)getLeftButton;
-(void)setTitleIcon;
-(void)setNavigationTitle:(id)title title:(id)title2;
-(void)modifyNavigationBarByMeta:(id)meta withView:(id)view;
-(void)loadCustomJS;
-(void)setNavigationTitleWithWebView:(id)webView;
-(void)modifyLeftAction:(id)action;
-(void)modifyCenterAction:(id)action;
-(void)modifyRightAction:(id)action;
-(void)modifyRightTitle:(id)title;
-(void)modifyLeftTitle:(id)title;
-(void)modifyLeftIcon:(id)icon;
-(void)modifyRightIcon:(id)icon;
-(void)modifySlaveTitle:(id)title;
-(void)modifySlaveIcon:(id)icon;
-(void)modifyCenterTitle:(id)title;
-(void)APNavigationBarDidClickRightButton;
-(void)APNavigationBarDidClickCenterButton;
-(void)APNavigationBarDidClickBackButton;
-(void)addLog:(id)log;
-(void)webViewDidFinishLoad:(id)webView;
-(void)loadCordovaScript:(id)script;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)closeLongPress;
-(void)createGapView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)parseInterfaceOrientations:(id)orientations;
-(void)viewDidLoad;
-(void)printMultitaskingInfo;
-(id)init;
@end

