/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIFont, UIColor;
@protocol CMIndexBarDelegate;

@interface CMIndexBar : XXUnknownSuperclass {
@private
	id<CMIndexBarDelegate> delegate;
	UIColor* highlightedBackgroundColor;
	UIColor* textColor;
	UIFont* _textFont;
}
@property(retain, nonatomic) UIFont* textFont;
@property(retain, nonatomic) UIColor* textColor;
@property(retain, nonatomic) UIColor* highlightedBackgroundColor;
@property(assign, nonatomic) __weak id<CMIndexBarDelegate> delegate;
-(void).cxx_destruct;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEndedOrCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)clearIndex;
-(void)setIndexes:(id)indexes;
-(void)layoutSubviews;
-(void)initializeDefaults;
-(id)initWithFrame:(CGRect)frame;
-(id)init;
@end

