/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface COCBalanceInfo : XXUnknownSuperclass {
@private
	NSString* _agentCode;
	NSString* _cardName;
	NSString* _cardNo;
	NSString* _balance;
	NSString* _poundAmount;
	NSString* _lastUpdateTime;
}
@property(retain, nonatomic) NSString* lastUpdateTime;
@property(retain, nonatomic) NSString* poundAmount;
@property(retain, nonatomic) NSString* balance;
@property(retain, nonatomic) NSString* cardNo;
@property(retain, nonatomic) NSString* cardName;
@property(retain, nonatomic) NSString* agentCode;
-(void).cxx_destruct;
@end

