/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DTViewController.h"

@class UIWebView, NSString, NSURL;

@interface COCWebViewController : DTViewController {
@private
	UIWebView* _webView;
	NSURL* _url;
	NSString* _webTitle;
}
@property(retain, nonatomic) NSString* webTitle;
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) UIWebView* webView;
-(void).cxx_destruct;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webViewDidStartLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)didReceiveMemoryWarning;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithURLString:(id)urlstring title:(id)title;
-(void)_loadUrl;
-(void)_creatWebView;
@end

