/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import "ALPPassView.h"

@class KABAOPRODPassBaseInfo;

@interface CouponPassView : ALPPassView {
	id _notifBlock;
@private
	KABAOPRODPassBaseInfo* passBaseInfo;
}
-(void)setPassBaseInfo:(id)info;
-(id)passBaseInfo;
-(void).cxx_destruct;
-(void)loadUIData:(id)data;
-(id)loadBackgroundColorFromString:(id)string;
-(id)loadBackgroundColor:(id)color;
-(void)setNotificationBlock:(id)block;
-(id)initWithFrame:(CGRect)frame header:(id)header backColor:(id)color;
-(id)initWithFrame:(CGRect)frame;
-(void)initPassViews:(CGRect)views header:(id)header backColor:(id)color;
@end

