/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import "CPTNumericData.h"

@class NSArray;

@interface CPTMutableNumericData : CPTNumericData {
}
@property(copy) NSArray* shape;
@property(readonly, assign) void* mutableBytes;
@property(assign) long byteOrder;
@property(assign) unsigned long sampleBytes;
@property(assign) int dataTypeFormat;
@property(assign) CPTNumericDataType dataType;
-(void)convertToType:(int)type sampleBytes:(unsigned long)bytes byteOrder:(long)order;
@end

