/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

@interface DACircularProgressLayer : XXUnknownSuperclass {
	CGPoint centerPoint;
	float radius;
	float innerRadius;
@private
	float _progress;
}
@property(assign, nonatomic) float progress;
@property(assign, nonatomic) float thicknessRatio;
@property(assign, nonatomic) int roundedCorners;
@property(retain, nonatomic) UIColor* progressTintColor;
@property(retain, nonatomic) UIColor* trackTintColor;
+(BOOL)needsDisplayForKey:(id)key;
-(void)drawInContext:(CGContextRef)context;
@end

