/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;
@protocol DropDownOptionViewDelegate;

@interface DropDownOptionViewController : XXUnknownSuperclass {
@private
	NSArray* _dataList;
	id<DropDownOptionViewDelegate> _delegate;
}
@property(retain, nonatomic) NSArray* dataList;
@property(assign) id<DropDownOptionViewDelegate> delegate;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)updateData:(id)data;
-(void)viewDidLoad;
-(void)dealloc;
@end

