/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSThread;

@interface DTAsyncCaller : XXUnknownSuperclass {
@private
	BOOL _cancelled;
	NSThread* _asyncThread;
}
@property(assign, nonatomic) __weak NSThread* asyncThread;
@property(assign, getter=isCancelled) BOOL cancelled;
-(void).cxx_destruct;
-(void)handleException:(id)exception;
-(void)cancel;
-(void)startAsyncBlock:(id)block completion:(id)completion;
-(id)init;
@end

