/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface DTGesture : XXUnknownSuperclass <NSCoding> {
@private
	NSString* _password;
	NSString* _identifier;
}
@property(retain, nonatomic) NSString* identifier;
@property(retain, nonatomic) NSString* password;
+(id)archivedPathWithIdentifier:(id)identifier;
+(id)gestureWithIdentifier:(id)identifier;
-(void).cxx_destruct;
-(void)synchronize;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithIdentifier:(id)identifier;
@end

