/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DTViewController.h"
#import "Portal-Structs.h"
#import "DTLauncherWidgetGroup.h"

@class NSString;
@protocol DTLauncher;

@interface DTLauncherWidgetGroupBase : DTViewController <DTLauncherWidgetGroup> {
@private
	id<DTLauncher> _launcher;
	NSString* _name;
}
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) __weak id<DTLauncher> launcher;
-(void).cxx_destruct;
-(id)allWidgets;
-(id)indicatorView;
-(id)contentViewController;
-(void)refresh;
@end

