/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface DTMemoryCacheItem : XXUnknownSuperclass {
@private
	BOOL _expired;
	id _object;
	NSMutableArray* _dependencies;
}
@property(retain, nonatomic) NSMutableArray* dependencies;
@property(assign, nonatomic, getter=isExpired) BOOL expired;
@property(retain, nonatomic) id object;
-(void).cxx_destruct;
-(BOOL)determineExpiration;
-(void)addDependency:(id)dependency;
-(id)init;
@end

