/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface DTWebViewBridgeElement : XXUnknownSuperclass {
@private
	id _registerObject;
	NSString* _functionKey;
	SEL _functionSelector;
	NSString* _msgType;
	NSString* _param;
	NSString* _clientId;
}
@property(copy, nonatomic) NSString* clientId;
@property(copy, nonatomic) NSString* param;
@property(copy, nonatomic) NSString* msgType;
@property(assign, nonatomic) SEL functionSelector;
@property(copy, nonatomic) NSString* functionKey;
@property(assign, nonatomic) __weak id registerObject;
-(void).cxx_destruct;
@end

