/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FinaTableController.h"
#import "UITableViewDataSource.h"
#import "Portal-Structs.h"
#import "UITableViewDelegate.h"

@class NSMutableArray;

@interface FinaKBAutoTableController : FinaTableController <UITableViewDataSource, UITableViewDelegate> {
	BOOL _keyboardShown;
	NSMutableArray* _textFields;
}
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)editingDidEndOnExit:(id)editing;
-(void)editingDidBegin:(id)editing;
-(void)centerView:(id)view;
-(float)centerOffset;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)loadView;
-(void)observeTextField:(id)field;
-(void)pushTextField:(id)field;
-(void)lookupTextFieldsInView:(id)view;
-(void)resetContentSize;
-(void)dealloc;
@end

