/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FundTransferOutFunctionData : XXUnknownSuperclass {
@private
	NSString* _canTransferOutAmount;
	NSString* _totalAmount;
	NSString* _quotaString;
}
@property(retain, nonatomic) NSString* quotaString;
@property(retain, nonatomic) NSString* canTransferOutAmount;
@property(retain, nonatomic) NSString* totalAmount;
-(void).cxx_destruct;
-(id)getCanTransferOutAmount;
-(id)getTotalAmount;
-(id)init;
@end

