/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

@interface FundIncomeListManager : XXUnknownSuperclass {
	NSMutableArray* _fundTradeArray;
@private
	NSString* _currentTransType;
	int _currentPage;
	int _pageSize;
	int _totolPage;
}
@property(retain, nonatomic) NSString* currentTransType;
@property(assign, nonatomic) int totolPage;
@property(assign, nonatomic) int pageSize;
@property(assign, nonatomic) int currentPage;
@property(retain, nonatomic) NSMutableArray* fundTradeArray;
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)cancelFundTradeListRpcRequest;
-(void)updateTableViewData:(id)data;
-(void)refreshTableViewData:(id)data;
-(id)getFundTradeRecordNodeInSection:(int)section row:(int)row;
-(int)numberOfFundInSection:(int)section;
-(int)numberOfFundSection;
-(void)_getCurrentPageData:(int)data pageSiz:(int)siz transType:(id)type;
-(id)init;
@end

