/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseOperation.h"

@class NSArray, NSString, NSMutableArray;

@interface GetBillListOperation : BaseOperation {
	int _tradeType;
	int _page;
	int _pageSize;
	BOOL _hasMoreData;
	NSMutableArray* _trades;
	NSArray* _originTrades;
	NSString* _uploadStartRowNum;
	NSString* downloadStartRowNum;
	int totalCount;
	int _pucBillCount;
	int _waitPayBillCount;
	NSArray* _pucBills;
}
@property(retain, nonatomic) NSArray* pucBills;
@property(readonly, assign, nonatomic) int waitPayBillCount;
@property(assign, nonatomic) int pucBillCount;
@property(readonly, assign, nonatomic) int totalCount;
@property(readonly, assign, nonatomic) int page;
@property(readonly, assign, nonatomic) NSString* downloadStartRowNum;
@property(readonly, assign, nonatomic) NSArray* originTrades;
@property(readonly, assign, nonatomic) NSArray* trades;
@property(readonly, assign, nonatomic) BOOL hasMoreData;
@property(readonly, assign, nonatomic) int tradeType;
-(id)stringFromTradeType:(int)tradeType;
-(void)main;
-(void)dealloc;
-(id)initWithTradeType:(int)tradeType page:(int)page pageSize:(int)size uploadStartRowNum:(id)num;
@end

