/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray, DTFileDownloadManager;

@interface HPAppCenterLoader : XXUnknownSuperclass {
@private
	NSMutableArray* bundleArray;
	NSString* currentBundleName;
	NSString* currentZipBundleName;
	NSString* currentZipPath;
	NSMutableArray* _updateBundleInfo;
	NSMutableArray* _curBundleInfo;
	NSString* _unZipBundlePath;
	NSMutableArray* _specialInfo;
	NSString* _zipBundlePath;
	NSString* _usersInfoPath;
	NSString* _operationFuncId;
	DTFileDownloadManager* _downloadManager;
	NSString* diskDirectory;
}
@property(retain, nonatomic) DTFileDownloadManager* downloadManager;
@property(retain, nonatomic) NSString* operationFuncId;
@property(retain, nonatomic) NSString* usersInfoPath;
@property(retain, nonatomic) NSString* zipBundlePath;
@property(retain, nonatomic) NSString* unZipBundlePath;
@property(retain, nonatomic) NSMutableArray* specialInfo;
@property(retain, nonatomic) NSMutableArray* updateBundleInfo;
@property(retain, nonatomic) NSMutableArray* curBundleInfo;
@property(retain, nonatomic) NSMutableArray* bundleArray;
@property(retain, nonatomic) NSString* currentZipBundleName;
@property(retain, nonatomic) NSString* currentBundleName;
@property(retain, nonatomic) NSString* currentZipPath;
@property(retain, nonatomic) NSString* diskDirectory;
+(id)sharedBundleLoader;
-(void).cxx_destruct;
-(BOOL)IsExistFunidFromArray:(id)array array:(id)array2;
-(void)upBundleInfoFromResource:(id)resource resBundleInfoPath:(id)path;
-(id)getBundleObject:(id)object;
-(id)currentBundle;
-(id)getImageResPath;
-(void)_bundleInfoMergeFrom:(id)from toTarget:(id)target;
-(id)unZip:(id)zip;
-(void)copyBundleFromApp:(id)app;
-(void)validateBundleInfoFile;
-(void)initLocalBundleInfoFile;
-(int)indexForFuncId:(id)funcId;
-(id)saveBundleWithData:(id)data withzipName:(id)name appName:(id)name3 type:(id)type;
-(void)insertBundleItem:(id)item infoDict:(id)dict;
-(void)clearCacheFile:(id)file;
-(void)_bundleDownloadFinsh:(id)finsh;
-(id)packRPCSyncFuncStatusReq;
-(id)packArrayWithDictionary:(id)dictionary;
-(void)updateBundleInfoSelector;
-(void)_notifyBundleDownload:(id)download;
-(void)_downloadBundleErr:(id)err;
-(void)_updataAbundleImage:(id)image;
-(void)reviewBundleIconImage;
-(int)doCheckBundleVersion;
-(void)removeBundleInfoWithFuncId:(id)funcId andBundleName:(id)name atIndex:(int)index;
-(int)checkBundleVersion;
-(void)_updataAbundleDownloading:(id)downloading;
-(void)dealloc;
-(void)setupNotification;
-(id)init;
@end

