/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIBase.h"
#import "Portal-Structs.h"
#import "UITextFieldDelegate.h"

@class UITextField, NSString, UILabel;

@interface Input : UIBase <UITextFieldDelegate> {
@private
	NSString* _content;
	NSString* _format;
	UILabel* _paddingView;
	NSString* _textFieldFormat;
	NSString* _keyboard;
	NSString* _format_msg;
	UITextField* _textField;
}
@property(retain, nonatomic) UITextField* textField;
-(void).cxx_destruct;
-(void)dissmissPopView;
-(void)showErrorMsg:(id)msg;
-(BOOL)resignFirstResponder;
-(BOOL)checkInput;
-(BOOL)checkContent;
-(BOOL)becomeFirstResponder;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textFieldShouldClear:(id)textField;
-(void)afterEdit:(id)edit;
-(id)textRangeFromRange:(NSRange)range;
-(NSRange)rangeFromTextRange:(id)textRange;
-(void)textFieldTextDidChange:(id)textFieldText;
-(void)setTextFieldText:(id)text;
-(id)formatText:(id)text;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldEndEditing:(id)textField;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(id)getValue;
-(CGSize)calcSize;
-(void)layoutSubviews;
-(id)init:(CGSize)init withModel:(id)model;
@end

