/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface JsonWrapper : XXUnknownSuperclass {
}
+(id)convertoDictionaryWithJsonString:(id)jsonString;
+(id)convertoDictionaryWithJsonData:(id)jsonData;
+(id)convertToJsonStringWithDictionary:(id)dictionary;
+(id)convertToJsonDataWithDictionary:(id)dictionary;
@end

