/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "KABAOPRODToString.h"

@class NSString;

@interface KABAOPRODFundApplyTransferInReq : KABAOPRODToString {
@private
	NSString* _fundCode;
	NSString* _amount;
}
@property(retain, nonatomic) NSString* amount;
@property(retain, nonatomic) NSString* fundCode;
-(void).cxx_destruct;
@end

