/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "KABAOPRODKabaoCommonResult.h"

@class NSString;

@interface KABAOPRODFundTransferInSuccessResult : KABAOPRODKabaoCommonResult {
@private
	NSString* _profitDateMsg;
}
@property(retain, nonatomic) NSString* profitDateMsg;
-(void).cxx_destruct;
@end

