/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface KABAOPRODWithdrawReq : XXUnknownSuperclass {
@private
	BOOL _needResendRandomCode;
	NSString* _amount;
	NSString* _payPassword;
	NSString* _bankAccountNo;
	NSString* _bankMark;
	NSString* _randomCode;
	NSString* _arrivedDateType;
	NSString* _passwordType;
}
@property(retain, nonatomic) NSString* passwordType;
@property(retain, nonatomic) NSString* arrivedDateType;
@property(retain, nonatomic) NSString* randomCode;
@property(assign, nonatomic) BOOL needResendRandomCode;
@property(retain, nonatomic) NSString* bankMark;
@property(retain, nonatomic) NSString* bankAccountNo;
@property(retain, nonatomic) NSString* payPassword;
@property(retain, nonatomic) NSString* amount;
-(void).cxx_destruct;
@end

