/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "KABAOPRODKabaoCommonPageReq.h"

@class NSString;

@interface KABAOPRODBillListReq : KABAOPRODKabaoCommonPageReq {
@private
	NSString* _billPeriodBegin;
	NSString* _billPeriodEnd;
}
@property(retain, nonatomic) NSString* billPeriodEnd;
@property(retain, nonatomic) NSString* billPeriodBegin;
-(void).cxx_destruct;
@end

