/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "KABAOPRODKabaoCommonResult.h"

@class NSString, KABAOPRODFundInfo, NSDictionary;

@interface KABAOPRODFundAssetsInfoResult : KABAOPRODKabaoCommonResult {
@private
	KABAOPRODFundInfo* _fundInfo;
	NSString* _totalAmount;
	NSString* _totalProfit;
	NSString* _previousProfit;
	NSString* _previousDate;
	NSDictionary* _extraInfo;
}
@property(retain, nonatomic) NSDictionary* extraInfo;
@property(retain, nonatomic) NSString* previousDate;
@property(retain, nonatomic) NSString* previousProfit;
@property(retain, nonatomic) NSString* totalProfit;
@property(retain, nonatomic) NSString* totalAmount;
@property(retain, nonatomic) KABAOPRODFundInfo* fundInfo;
+(Class)extraInfoElementClass;
-(void).cxx_destruct;
@end

