/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LWApiMediaObject.h"

@class NSString;

@interface LWApiNewsObject : LWApiMediaObject {
@private
	NSString* _detailURL;
}
@property(retain, nonatomic) NSString* detailURL;
-(void)structure:(id)structure;
-(id)parse;
-(void)dealloc;
@end

