/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface MAPathGroup : XXUnknownSuperclass {
	NSMutableArray* paths;
	CGAffineTransform modelTransform;
}
@property(assign, nonatomic) CGAffineTransform modelTransform;
@property(retain, nonatomic) NSMutableArray* paths;
-(void).cxx_destruct;
-(id)init;
@end

