/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIColor, PPChatMedia;

@interface Message : XXUnknownSuperclass <NSCoding> {
@private
	BOOL _deleteOnLongPress;
	BOOL _deleteOnClick;
	BOOL _isRealtime;
	BOOL _isP2P;
	BOOL _useFriendlyDate;
	NSString* _msgId;
	NSString* _msgTypeString;
	int _msgType;
	NSString* _msgTime;
	NSString* _thirdAccountId;
	NSString* _showType;
	UIColor* _backgroundColor;
	NSString* _incomeIconUrl;
	NSString* _outputIconUrl;
	UIColor* _baseColor;
	PPChatMedia* _extAnimation;
	PPChatMedia* _extVoice;
}
@property(retain, nonatomic) PPChatMedia* extVoice;
@property(retain, nonatomic) PPChatMedia* extAnimation;
@property(assign, nonatomic) BOOL useFriendlyDate;
@property(assign, nonatomic) BOOL isP2P;
@property(retain, nonatomic) UIColor* baseColor;
@property(retain, nonatomic) NSString* outputIconUrl;
@property(retain, nonatomic) NSString* incomeIconUrl;
@property(retain, nonatomic) UIColor* backgroundColor;
@property(retain, nonatomic) NSString* showType;
@property(assign, nonatomic) BOOL isRealtime;
@property(retain, nonatomic) NSString* thirdAccountId;
@property(assign, nonatomic) BOOL deleteOnClick;
@property(assign, nonatomic) BOOL deleteOnLongPress;
@property(retain, nonatomic) NSString* msgTime;
@property(assign, nonatomic) int msgType;
@property(retain, nonatomic) NSString* msgTypeString;
@property(retain, nonatomic) NSString* msgId;
-(void).cxx_destruct;
-(BOOL)hasAction;
-(id)titleForHome;
-(id)monthString;
-(id)friendlyDateString;
-(id)dateString;
-(id)subItemForIndex:(int)index;
-(id)initWithRpcMessageEntry:(id)rpcMessageEntry;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

