/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIImageView, UILabel, UIButton;

@interface MessageHeaderView : XXUnknownSuperclass {
@private
	BOOL _isPersonal;
	UIImageView* _headImageView;
	UIImageView* _backgroundView;
	UIButton* _addingButton;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIView* _lineView;
	float _titleY1;
	float _titleY2;
}
@property(assign, nonatomic) float titleY2;
@property(assign, nonatomic) float titleY1;
@property(retain, nonatomic) UIView* lineView;
@property(retain, nonatomic) UILabel* subtitleLabel;
@property(retain, nonatomic) UILabel* titleLabel;
@property(assign, nonatomic) BOOL isPersonal;
@property(retain, nonatomic) UIButton* addingButton;
@property(retain, nonatomic) UIImageView* backgroundView;
@property(retain, nonatomic) UIImageView* headImageView;
+(float)height;
-(void).cxx_destruct;
-(void)setVisibleHeight:(float)height;
-(void)setLineColor:(id)color;
-(void)setBackImageUrl:(id)url;
-(void)setHeadImageUrl:(id)url;
-(void)showSecondLine:(BOOL)line;
-(void)setSubtitle:(id)subtitle;
-(void)setTitle:(id)title;
-(void)setAddingButtonTitle:(id)title target:(id)target action:(SEL)action;
-(id)initWithFrame:(CGRect)frame;
@end

