/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIScrollView, UIActivityIndicatorView, UIImageView, UILabel;
@protocol MJRefreshBaseViewDelegate;

@interface MJRefreshBaseView : XXUnknownSuperclass {
	UIScrollView* _scrollView;
	id<MJRefreshBaseViewDelegate> _delegate;
	id _beginRefreshingBlock;
	UILabel* _lastUpdateTimeLabel;
	UILabel* _statusLabel;
	UIImageView* _arrowImage;
	UIActivityIndicatorView* _activityView;
	int _state;
}
@property(readonly, assign, nonatomic, getter=isRefreshing) BOOL refreshing;
@property(assign, nonatomic) __weak UIScrollView* scrollView;
@property(assign, nonatomic) __weak id<MJRefreshBaseViewDelegate> delegate;
@property(copy, nonatomic) id beginRefreshingBlock;
@property(readonly, assign, nonatomic) UIImageView* arrowImage;
@property(readonly, assign, nonatomic) UILabel* statusLabel;
@property(readonly, assign, nonatomic) UILabel* lastUpdateTimeLabel;
-(void).cxx_destruct;
-(void)endRefreshing;
-(void)beginRefreshing;
-(void)setState:(int)state;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)removeFromSuperview;
-(void)setFrame:(CGRect)frame;
-(id)labelWithFontSize:(float)fontSize;
-(id)initWithFrame:(CGRect)frame;
-(void)initial;
-(id)initWithScrollView:(id)scrollView;
@end

