/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableArray;

@interface MQPExtPaneList : XXUnknownSuperclass {
@private
	NSMutableArray* _elementArray;
	NSArray* _elementModelArray;
}
@property(retain, nonatomic) NSArray* elementModelArray;
-(void)dealloc;
-(id)elementList;
-(id)factoryElementWithMdoel:(id)mdoel AndBlock:(id)block;
-(id)initWithElementModelList:(id)elementModelList AndBlock:(id)block;
@end

