/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MQPJsonProcess : XXUnknownSuperclass {
}
+(id)jsonRepresentation:(id)representation;
+(id)jsonValue:(id)value;
@end

