/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MQProtScriptNetwork <NSObject>
-(void)ScriptNetworkRequest:(id)request apiName:(id)name apiVer:(id)ver url:(id)url param:(id)param;
-(void)ScriptNetworkSend:(id)send nameSpace:(id)space apiName:(id)name apiVer:(id)ver url:(id)url param:(id)param;
@end

