/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MSMobileSecurityResult.h"

@class NSString;

@interface MSApplyImageCodeResult : MSMobileSecurityResult {
@private
	NSString* _sessionId;
	NSString* _imageCode;
	NSString* _checkCodeUrl;
}
@property(retain, nonatomic) NSString* checkCodeUrl;
@property(retain, nonatomic) NSString* imageCode;
@property(retain, nonatomic) NSString* sessionId;
-(void).cxx_destruct;
@end

