/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MSMobileSmsResult.h"

@class NSString;

@interface MSApplyModifyPwdResult : MSMobileSmsResult {
@private
	BOOL _certified;
	NSString* _smsCode;
	NSString* _sessionId;
	NSString* _imageCode;
}
@property(retain, nonatomic) NSString* imageCode;
@property(retain, nonatomic) NSString* sessionId;
@property(retain, nonatomic) NSString* smsCode;
@property(assign, nonatomic) BOOL certified;
-(void).cxx_destruct;
@end

