/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MSSendSmsCheckCodeReq : XXUnknownSuperclass {
@private
	NSString* _mobileNo;
}
@property(retain, nonatomic) NSString* mobileNo;
-(void).cxx_destruct;
@end

