/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol MQProtScriptNetwork;

@interface newNetwork : XXUnknownSuperclass {
@private
	id<MQProtScriptNetwork> _mObj;
}
@property(assign, nonatomic) id<MQProtScriptNetwork> mObj;
-(void)dealloc;
-(id)init:(id)init;
@end

