/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, Reachability, AsyncSocket, NSTimer;

@interface NotificationManager : XXUnknownSuperclass {
	NSTimer* _timer;
	NSTimer* _testConnectionTimer;
	int _testConnectionTime;
	int _heartBeatInterval;
	int _heartBeatRetryState;
	AsyncSocket* _asyncSocket;
	Reachability* _internetReachability;
	int _connectionType;
	int _connectState;
	BOOL _currentConnectState;
	NSTimer* _connectionRetryTimer;
	NSString* _notificationData;
@private
	BOOL _barcodeMode;
}
@property(assign, nonatomic) BOOL barcodeMode;
@property(readonly, assign, nonatomic) NSString* stringData;
+(id)sharedInstance;
-(double)onSocket:(id)socket shouldTimeoutWriteWithTag:(long)tag elapsed:(double)elapsed bytesDone:(unsigned)done;
-(double)onSocket:(id)socket shouldTimeoutReadWithTag:(long)tag elapsed:(double)elapsed bytesDone:(unsigned)done;
-(void)onSocketDidDisconnect:(id)onSocket;
-(void)onSocket:(id)socket willDisconnectWithError:(id)error;
-(void)onSocket:(id)socket didWriteDataWithTag:(long)tag;
-(void)onSocket:(id)socket didReadData:(id)data withTag:(long)tag;
-(void)onSocketDidSecure:(id)onSocket;
-(void)onSocket:(id)socket didConnectToHost:(id)host port:(unsigned short)port;
-(void)tryReLink;
-(void)stopAndCheckLink;
-(void)startAndCheckLink;
-(void)stopPushLink;
-(void)startPushLink;
-(void)_connectionStatesChanged;
-(void)_startToLink;
-(int)_port;
-(id)_properAddress;
-(BOOL)isConnection;
-(void)closeConnection;
-(void)dealloc;
-(id)init;
-(void)_connectionTime;
-(void)_tellSeverDone:(id)done;
-(void)_checkPushSever:(id)sever;
-(void)_scheduleHeartBeat:(double)beat toSocket:(id)socket;
-(void)_sendHeartBeatPackage:(id)package;
@end

