/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, CAGradientLayer;

@interface OBGradientView : XXUnknownSuperclass {
}
@property(copy, nonatomic) NSString* type;
@property(assign, nonatomic) CGPoint endPoint;
@property(assign, nonatomic) CGPoint startPoint;
@property(retain, nonatomic) NSArray* locations;
@property(retain, nonatomic) NSArray* colors;
@property(readonly, assign, nonatomic) CAGradientLayer* gradientLayer;
+(Class)layerClass;
@end

