/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OPApp.h"

@class NSString;

@interface OPAppEntry : OPApp {
@private
	NSString* title;
	NSString* info;
	NSString* logoImageName;
}
@property(retain, nonatomic) NSString* logoImageName;
@property(retain, nonatomic) NSString* info;
@property(retain, nonatomic) NSString* title;
-(void).cxx_destruct;
@end

