/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OPAuthGetAuthStatus : XXUnknownSuperclass {
}
+(id)authSignSync:(id)sync userId:(id)anId;
+(id)authSignAsyncLaunchWeb:(id)web userId:(id)anId resultCallback:(id)callback;
+(id)authSignAsync:(id)async userId:(id)anId resultCallback:(id)callback;
+(id)getAuthStatusSync:(id)sync userId:(id)anId;
+(id)getAuthStatusAsyncLaunchWeb:(id)web userId:(id)anId resultCallback:(id)callback;
+(id)getAuthStatusAsync:(id)async userId:(id)anId resultCallback:(id)callback;
@end

