/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface OPCircularRingView : XXUnknownSuperclass {
	CGPoint _circularCenter;
	NSMutableArray* _colorArray;
	NSMutableArray* _radiusArray;
}
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)addOneCircular:(float)circular color:(id)color;
-(void)setCircularCenter:(CGPoint)center;
-(id)initWithFrame:(CGRect)frame;
@end

