/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DTViewController.h"

@class UIView, FTCoreTextStyle, UIImageView, UIScrollView, UILabel, FTCoreTextView, ALPButton, OPAppManageService, OPApp, ALPToastView;

@interface OPDetailViewController : DTViewController {
@private
	OPApp* _opApp;
	UIScrollView* _view;
	OPAppManageService* _opAppManageService;
	float fullViewHeight;
	UIImageView* _icon;
	UILabel* _title;
	UILabel* _version;
	UILabel* _size;
	UIView* _contentView;
	UIImageView* _backgroundWithTrangleView;
	UIImageView* _dottedLineView;
	FTCoreTextStyle* _defaultStyle;
	FTCoreTextView* _contentTextView;
	ALPButton* _operationButton;
	OPApp* _toOperation;
	int operationType;
	BOOL _buttonDidClicked;
	int _buttonStatus;
	int _moniterButtonStatus;
	UIView* topBackView;
	BOOL isFromAlipayAppList;
	BOOL isFromThirdpartyAppList;
	int indexFromHotAppList;
	ALPToastView* toast;
}
@property(retain, nonatomic) ALPToastView* toast;
@property(assign, nonatomic) BOOL isFromThirdpartyAppList;
@property(assign, nonatomic) BOOL isFromAlipayAppList;
@property(assign, nonatomic) int indexFromHotAppList;
-(void).cxx_destruct;
-(id)createImageWithColor:(id)color;
-(void)closeToast;
-(void)openToast:(id)toast;
-(void)writeMoniterPoint;
-(void)back;
-(void)doExpand:(float)expand duration:(float)duration;
-(void)buttonTypeStyle:(id)style type:(int)type;
-(void)doAddInstallApp:(id)app;
-(void)doRemoveApp:(id)app;
-(void)doAddApp:(id)app;
-(void)loadAppStatus;
-(void)buttonStatus;
-(void)doFunction;
-(void)reloadAppData:(id)data;
-(void)viewWillDestroy;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)reflushAppInfo;
-(void)gotoLauncher;
-(void)loadApp:(id)app;
-(void)viewDidLoad;
-(id)init;
@end

