/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OPLibHelper : XXUnknownSuperclass {
}
+(id)traingleImage;
+(id)blankViewWithSize:(CGRect)size target:(id)target action:(SEL)action;
+(id)blankViewWithSize:(CGRect)size text:(id)text;
+(id)recommendImage;
+(id)triangleViewInAppDetail;
+(id)defaultIcon;
@end

