/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIWebView, ALPButton;
@protocol OPPopupViewDelegate;

@interface OPPopupView : XXUnknownSuperclass {
@private
	UIWebView* _webView;
	ALPButton* _agreeBtn;
	id<OPPopupViewDelegate> _delegate;
}
@property(assign, nonatomic) id<OPPopupViewDelegate> delegate;
@property(assign, nonatomic) __weak ALPButton* agreeBtn;
@property(assign, nonatomic) __weak UIWebView* webView;
-(void).cxx_destruct;
-(void)onConfirm;
-(id)initWithFrame:(CGRect)frame;
@end

