/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import "PPChatCtrlBase.h"

@class UIImageView, UILabel, UIButton;

@interface PPChatCtrlButton : PPChatCtrlBase {
@private
	UIButton* _backgroundButton;
	UILabel* _textLabel;
	UILabel* _detailLabel;
	UIImageView* _viewMore;
}
@property(retain, nonatomic) UIImageView* viewMore;
@property(retain, nonatomic) UILabel* detailLabel;
@property(retain, nonatomic) UILabel* textLabel;
@property(retain, nonatomic) UIButton* backgroundButton;
-(void).cxx_destruct;
-(void)touchup:(id)touchup;
-(void)touchdown:(id)touchdown;
-(void)click:(id)click;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame param:(id)param notify:(id)notify;
@end

