/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MessageDataDelegate.h"

@class UIColor, MessageHeaderView, UIView, PublicAccount, ThirdPartyAccount, UIActivityIndicatorView, NSMutableArray, NSArray, ODRefreshControl, NSString, PPChatRefreshControl, Message;
@protocol MessageDataSource;

@interface PPChatBaseMessageController : XXUnknownSuperclass <MessageDataDelegate> {
@private
	BOOL _frozen;
	BOOL _loadingHead;
	BOOL _loadingHistory;
	BOOL _allHistoryLoaded;
	id<MessageDataSource> _messageDataSource;
	Message* _firstVisibleMessage;
	PublicAccount* _publicAccount;
	ThirdPartyAccount* _thirdPartyAccount;
	NSMutableArray* _messageArray;
	Message* _activeMessage;
	UIView* _footerView;
	UIActivityIndicatorView* _footerActivity;
	ODRefreshControl* _odRefreshControl;
	PPChatRefreshControl* _ppcRefreshControl;
}
@property(assign, nonatomic) BOOL allHistoryLoaded;
@property(assign, nonatomic) BOOL loadingHistory;
@property(assign, nonatomic) BOOL loadingHead;
@property(retain, nonatomic) PPChatRefreshControl* ppcRefreshControl;
@property(retain, nonatomic) ODRefreshControl* odRefreshControl;
@property(retain, nonatomic) UIActivityIndicatorView* footerActivity;
@property(retain, nonatomic) UIView* footerView;
@property(assign, nonatomic) BOOL frozen;
@property(retain, nonatomic) Message* activeMessage;
@property(retain, nonatomic) NSMutableArray* messageArray;
@property(retain, nonatomic) ThirdPartyAccount* thirdPartyAccount;
@property(retain, nonatomic) PublicAccount* publicAccount;
@property(readonly, assign, nonatomic) NSString* userIconUrl;
@property(readonly, assign, nonatomic) NSString* objectIconUrl;
@property(readonly, assign, nonatomic) UIColor* baseColor;
@property(readonly, assign, nonatomic) BOOL injectsTimeline;
@property(readonly, assign, nonatomic) MessageHeaderView* headerView;
@property(readonly, assign, nonatomic) NSArray* messages;
@property(readonly, assign, nonatomic) Message* firstVisibleMessage;
@property(readonly, assign, nonatomic) BOOL loadingMessage;
@property(retain, nonatomic) id<MessageDataSource> messageDataSource;
-(void).cxx_destruct;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)messageDataShouldAcceptRealtimeMessage:(id)messageData withContext:(id)context;
-(void)messageDataDidUpdateMessages:(id)messageData;
-(void)messageDataDeleteMessage:(id)message failWithError:(id)error;
-(void)messageDataDidDeleteMessage:(id)messageData;
-(void)messageDataDidLoadRealtimeMessages:(id)messageData;
-(void)messageDataRequestHistoryMessagesFailWithError:(id)error;
-(void)messageDataDidLoadHistoryMessages:(id)messageData gotAll:(BOOL)all;
-(void)messageDataRequestHeadMessgesFailWithError:(id)error;
-(void)messageDataDidLoadHeadMessages:(id)messageData shouldReplace:(BOOL)replace gotAll:(BOOL)all;
-(void)updateMessages:(id)messages;
-(void)deleteMessage:(id)message;
-(void)appendMessages:(id)messages;
-(void)afterPrependMessagesWithIndexSet:(id)indexSet;
-(void)prependMessages:(id)messages;
-(void)setMessages:(id)messages;
-(id)preprocessMessages:(id)messages withPrev:(id)prev next:(id)next;
-(void)configureMessage:(id)message;
-(id)injectTimelines:(id)timelines withPrev:(id)prev next:(id)next;
-(void)onMenuDismiss:(id)dismiss;
-(void)delete:(id)aDelete;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canBecomeFirstResponder;
-(id)indexPathsForMessage:(id)message;
-(id)cellsForMessage:(id)message;
-(void)setActiveCellsHighlighted:(BOOL)highlighted;
-(void)onLongPress:(id)press;
-(void)stopLoadingHistory;
-(void)startLoadingHistory;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)stopLoadingHead;
-(BOOL)startLoadingHead;
-(void)dropViewDidBeginRefreshing:(id)dropView;
-(void)postClickMessage:(id)message;
-(void)postLongPressDeleteMessage:(id)message;
-(void)updateVisibleMessages;
-(void)refreshWithProgressHUD;
-(void)refresh;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

