/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView, UILabel;
@protocol PPSubviewsDelegate;

@interface PPDetailUserInfoSubview : XXUnknownSuperclass {
@private
	BOOL _isPrevSetting;
	id<PPSubviewsDelegate> _delegate;
	UIImageView* _imgView;
	UILabel* _name;
	UILabel* _identify;
	UIImageView* _followCountImgView;
	NSString* _loginId;
	NSString* _strName;
	NSString* _followType;
}
@property(retain, nonatomic) NSString* followType;
@property(assign, nonatomic) BOOL isPrevSetting;
@property(retain, nonatomic) NSString* strName;
@property(retain, nonatomic) NSString* loginId;
@property(retain, nonatomic) UIImageView* followCountImgView;
@property(retain, nonatomic) UILabel* identify;
@property(retain, nonatomic) UILabel* name;
@property(retain, nonatomic) UIImageView* imgView;
@property(assign, nonatomic) __weak id<PPSubviewsDelegate> delegate;
-(void).cxx_destruct;
-(BOOL)isEmptyText:(id)text;
-(BOOL)needGetUserInfo;
-(BOOL)isPrevSet:(id)set;
-(BOOL)isOneLine:(CGRect)line lineHeight:(float)height;
-(float)maxValue:(float)value another:(float)another;
-(void)calculateSubviewFrameWithNameShow:(BOOL)nameShow isNotShowIdentify:(BOOL)identify;
-(void)updateInfo:(id)info name:(id)name identify:(id)identify;
-(void)addLabel:(id)label frame:(CGRect)frame labelProperties:(id)properties;
-(id)defaultImageFromFollowType:(id)followType;
-(void)setImageViewImageWithUrl:(id)url width:(int)width height:(int)height;
-(void)addRoundedCornerImageViewFromUrl:(id)url frame:(CGRect)frame widthHeight:(float)height raidus:(float)raidus;
-(void)roundedCornerImageView:(id)view cornerRaidus:(float)raidus;
-(void)addRoundedImageViewFromUrl:(id)url frame:(CGRect)frame diameter:(float)diameter;
-(void)setRoundedView:(id)view toDiameter:(float)diameter;
-(id)initWithParent:(id)parent frame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
@end

