/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;
@protocol PPSubviewsDelegate;

@interface PPDetailSummarySubview : XXUnknownSuperclass {
@private
	id<PPSubviewsDelegate> _delegate;
	UILabel* _title;
	UILabel* _summaryInfo;
}
@property(retain, nonatomic) UILabel* summaryInfo;
@property(retain, nonatomic) UILabel* title;
@property(assign, nonatomic) __weak id<PPSubviewsDelegate> delegate;
-(void).cxx_destruct;
-(void)updateSummary:(id)summary;
-(id)initWithParent:(id)parent frame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
@end

