/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PPViewController.h"
#import "Portal-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class ALPNextPagePullView, UIView, NSString, DTRpcAsyncCaller, UILabel, UIActivityIndicatorView, NewTodoData, UITableView, PPHeadImageView, PPChatRefreshControl;

@interface PPMsgBoxViewController : PPViewController <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate> {
@private
	BOOL _reloading;
	BOOL reloadNextPage;
	CGPoint longPressedPosition;
	CGPoint startTouch;
	CGRect _headViewFrame;
	PPHeadImageView* _ppHeadImageView;
	BOOL _needBackFlags;
	BOOL _isConnectting;
	NewTodoData* _newtodoData;
	NSString* _controlType;
	float _oldPostionY;
	ALPNextPagePullView* _refreshTailerView;
	DTRpcAsyncCaller* _msgAsyncCaller;
	DTRpcAsyncCaller* _msgUpAsyncCaller;
	DTRpcAsyncCaller* _msgneedUpdataAsyncCaller;
	UITableView* _tableView;
	UIView* _noMsgTipView;
	UIActivityIndicatorView* _waitIndicator;
	UILabel* _loadTip;
	PPChatRefreshControl* _refreshControl;
	CGRect _frame;
}
@property(assign, nonatomic) BOOL isConnectting;
@property(assign, nonatomic) BOOL needBackFlags;
@property(retain, nonatomic) DTRpcAsyncCaller* msgneedUpdataAsyncCaller;
@property(retain, nonatomic) DTRpcAsyncCaller* msgUpAsyncCaller;
@property(retain, nonatomic) DTRpcAsyncCaller* msgAsyncCaller;
@property(assign, nonatomic) float oldPostionY;
@property(retain, nonatomic) NSString* controlType;
@property(retain, nonatomic) NewTodoData* newtodoData;
@property(retain, nonatomic) PPChatRefreshControl* refreshControl;
@property(retain, nonatomic) UILabel* loadTip;
@property(retain, nonatomic) UIActivityIndicatorView* waitIndicator;
@property(retain, nonatomic) UIView* noMsgTipView;
@property(assign, nonatomic) CGRect frame;
@property(retain, nonatomic) ALPNextPagePullView* refreshTailerView;
@property(retain, nonatomic) UITableView* tableView;
-(void).cxx_destruct;
-(void)dealloc;
-(void)upPullTableDidTriggerRefresh:(id)upPullTable;
-(BOOL)isTableViewLoadingNextPage:(id)page;
-(id)egoRefreshTableHeaderDataSourceLastUpdated:(id)updated;
-(BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)loading;
-(void)egoRefreshTableHeaderDidTriggerRefresh:(id)egoRefreshTableHeader;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)onReceivedMsg:(id)msg;
-(void)delayUpdateViewWithCache;
-(void)onReceivedCache:(id)cache;
-(void)doneLoadingTableViewData;
-(void)delayUpdateHeaderView;
-(void)doneReLoadingTableViewData;
-(void)loadMoreTableViewDataSource;
-(void)reloadTableViewDataSource;
-(void)checkAndSwitchTodo;
-(void)deleteMsgType:(id)type;
-(void)updateTabMsgCount;
-(id)dictionaryFromString:(id)string;
-(void)doProcess:(id)process;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canBecomeFirstResponder;
-(void)handleLongPress:(id)press;
-(BOOL)deleteCellOnTableByPathIndex:(id)index;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)stopTipAnimation;
-(void)startTipAnimation;
-(void)hideLoadTip;
-(void)hideNoTodoTip;
-(void)showNoTodoTip;
-(void)hideFootRefreshVew;
-(void)showFootRefreshVew;
-(void)showWaitIndicator:(BOOL)indicator;
-(void)onReceivedExitNotification:(id)notification;
-(void)onReceivedLoginNotification:(id)notification;
-(void)onAppEnterForeground:(id)foreground;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)existUser;
-(void)refreshEventRecieved:(id)recieved;
-(BOOL)needRemoveFromeArray:(id)array;
-(void)onReceivedTodoUpdateInfo:(id)info;
-(void)readyToShowNetworkData:(id)showNetworkData;
-(void)clearButtonClicked;
-(void)upDataScreenWhenLogin:(id)login;
-(void)onReceivedLoginMsg:(id)msg;
-(void)loadInitData;
-(void)viewDidLoad;
-(void)swipeBack;
-(void)paningGestureReceive:(id)receive;
-(void)addObjcSuccess:(id)success;
-(void)viewDidAppear:(BOOL)view;
-(void)goBackButtonClickedWithoutAnimated;
-(void)goBackButtonClicked;
-(void)loadView;
-(id)initWithType:(id)type;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

