/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PUBLICCOREBaseMessageQuery.h"

@class NSArray, NSString, DTInteger;

@interface PUBLICCOREMessageQuery : PUBLICCOREBaseMessageQuery {
@private
	BOOL _includeTotalCount;
	NSString* _publicId;
	NSString* _agreementId;
	NSString* _startTime;
	NSString* _endTime;
	NSArray* _includeMsgType;
	DTInteger* _pageSize;
}
@property(retain, nonatomic) DTInteger* pageSize;
@property(assign, nonatomic) BOOL includeTotalCount;
@property(retain, nonatomic) NSArray* includeMsgType;
@property(retain, nonatomic) NSString* endTime;
@property(retain, nonatomic) NSString* startTime;
@property(retain, nonatomic) NSString* agreementId;
@property(retain, nonatomic) NSString* publicId;
+(Class)includeMsgTypeElementClass;
-(void).cxx_destruct;
@end

