/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface PUBLICCOREAlipaySsoLoginReq : XXUnknownSuperclass {
@private
	NSString* _userId;
	NSString* _appId;
	NSString* _logonId;
	NSString* _scope;
	NSString* _authDigest;
	NSString* _from;
}
@property(retain, nonatomic) NSString* from;
@property(retain, nonatomic) NSString* authDigest;
@property(retain, nonatomic) NSString* scope;
@property(retain, nonatomic) NSString* logonId;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) NSString* userId;
-(void).cxx_destruct;
@end

