/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DTMicroApplicationDelegate.h"

@class NSDictionary, UIViewController, UINavigationController;

@interface SACLoginAppDelegate : XXUnknownSuperclass <DTMicroApplicationDelegate> {
@private
	UIViewController* _rootController;
	UINavigationController* _rootNavController;
	NSDictionary* _yuEBaoInfo;
}
@property(retain, nonatomic) NSDictionary* yuEBaoInfo;
@property(retain, nonatomic) UINavigationController* rootNavController;
@property(retain, nonatomic) UIViewController* rootController;
-(void).cxx_destruct;
-(void)applicationWillTerminate:(id)application animated:(BOOL)animated;
-(void)applicationWillPause:(id)application;
-(void)applicationDidFinishLaunching:(id)application;
-(void)application:(id)application willResumeWithOptions:(id)options;
-(void)application:(id)application willStartLaunchingWithOptions:(id)options;
-(void)applicationDidCreate:(id)application;
-(id)rootControllerInApplication:(id)application;
@end

