/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SARouterMgr, NSDictionary;
@protocol SARouterMgrDelegate;

@interface SARouter : XXUnknownSuperclass {
@private
	NSDictionary* _params;
	SARouterMgr* _routerMgr;
	id<SARouterMgrDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<SARouterMgrDelegate> delegate;
@property(assign, nonatomic) __weak SARouterMgr* routerMgr;
@property(retain, nonatomic) NSDictionary* params;
-(void).cxx_destruct;
-(void)exec:(id)exec;
-(void)dealloc;
-(void)notifyRouterMgr:(id)mgr didFailAction:(int)action Error:(id)error;
-(void)notifyRouterMgr:(id)mgr didFinishAction:(int)action UserInfo:(id)info;
-(void)hideProcessActiving;
-(void)showProcessActiving;
-(id)processSuperView;
-(void)enableUserInteraction:(BOOL)interaction;
@end

