/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class TTTAttributedLabel, UIImageView, SAUserInfo;

@interface SCAccountInfoTableCell : XXUnknownSuperclass {
@private
	SAUserInfo* _userInfo;
	UIImageView* _headImage;
	TTTAttributedLabel* _accountNameLabel;
}
@property(assign, nonatomic) __weak TTTAttributedLabel* accountNameLabel;
@property(assign, nonatomic) __weak UIImageView* headImage;
@property(retain, nonatomic) SAUserInfo* userInfo;
-(void).cxx_destruct;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

