/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIFont, UIColor;

@interface SCRegisterTextField : XXUnknownSuperclass {
@private
	BOOL _drawsPlaceholder;
	NSString* _scplaceholder;
	UIFont* _scplaceholderFont;
	UIColor* _scplaceholderColor;
}
@property(retain, nonatomic) UIColor* scplaceholderColor;
@property(retain, nonatomic) UIFont* scplaceholderFont;
@property(copy, nonatomic) NSString* scplaceholder;
-(void).cxx_destruct;
-(void)textChanged:(id)changed;
-(void)clearAndReset;
-(void)updatePlaceholder;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
@end

