/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SEDevice : XXUnknownSuperclass {
}
+(id)uniqueDeviceIdentifierEx;
+(id)macaddress;
+(id)getSID;
+(id)getHID;
@end

