/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SPClient : XXUnknownSuperclass {
}
+(void)getSettingViewControllerWithExternal:(id)external CompletionBlock:(id)block;
+(void)AliSetPaySys:(int)sys param:(id)param notify:(id)notify;
+(id)AliGetPaySysInfo:(int)info;
+(BOOL)isCurrentSPView;
+(void)reMoveSPView;
+(BOOL)startPrePayWithUrl:(id)url;
+(BOOL)StartServiceWithUrl:(id)url;
+(void)setCallBackFunc:(SEL)func target:(id)target;
+(void)shareStorageCallThirdPartWithResult:(id)result suc:(BOOL)suc;
+(void)shareStorageCallInvokeWithResult:(id)result suc:(BOOL)suc;
+(void)shareStorageInit:(id)init;
+(void)pay:(id)pay scheme:(id)scheme WithRootViewController:(id)rootViewController;
+(void)pay:(id)pay scheme:(id)scheme oneKey:(BOOL)key;
+(void)pay:(id)pay scheme:(id)scheme;
+(void)prePay:(id)pay;
+(void)clearTid;
+(void)updataTidIfKeychainIsstored;
+(void)setUrl:(id)url;
+(void)setupSqlite;
@end

