/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SSDeviceHelper : XXUnknownSuperclass {
}
+(BOOL)passwordLegalCheck:(id)check;
+(int)iphoneType;
+(void)dismissAlertViews;
+(id)formatMobileNO:(id)no;
+(id)hideRule:(id)rule hideType:(int)type;
+(BOOL)isMobileNumber:(id)number;
+(void)callPhoneNumberNoAlert:(id)alert;
+(id)getCarrier;
+(BOOL)hasProviderInfo;
+(BOOL)deviceHasSMSModule;
+(BOOL)hasSmsAbility;
+(BOOL)hasSIMCard;
+(void)callPhoneNumber:(id)number fromView:(id)view;
+(BOOL)canSendText;
+(BOOL)canMakeCall;
+(id)wirelessMacAddress;
@end

