/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSString;

@interface STATUSBARTodoRemind : XXUnknownSuperclass <NSCoding> {
@private
	BOOL _iconCount;
	BOOL _canDelete;
	BOOL _deleteOnClick;
	NSString* _id;
	NSString* _cardNo;
	NSString* _remindScene;
	NSString* _remindSceneCode;
	NSString* _priority;
	NSString* _businessType;
	NSString* _title;
	NSString* _url;
	NSString* _memo;
	NSString* _iconUrl;
	NSString* _businessId;
	NSString* _businessArgs;
	NSDate* _gmtCreate;
	NSDate* _gmtModified;
}
@property(retain, nonatomic) NSDate* gmtModified;
@property(retain, nonatomic) NSDate* gmtCreate;
@property(retain, nonatomic) NSString* businessArgs;
@property(retain, nonatomic) NSString* businessId;
@property(assign, nonatomic) BOOL deleteOnClick;
@property(assign, nonatomic) BOOL canDelete;
@property(assign, nonatomic) BOOL iconCount;
@property(retain, nonatomic) NSString* iconUrl;
@property(retain, nonatomic) NSString* memo;
@property(retain, nonatomic) NSString* url;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* businessType;
@property(retain, nonatomic) NSString* priority;
@property(retain, nonatomic) NSString* remindSceneCode;
@property(retain, nonatomic) NSString* remindScene;
@property(retain, nonatomic) NSString* cardNo;
@property(retain, nonatomic) NSString* id;
-(void).cxx_destruct;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

