/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSString;

@interface STATUSBARTodoQueryRequest : XXUnknownSuperclass {
@private
	NSString* _cardNo;
	NSString* _terminal;
	NSDate* _endDate;
	int _pageNum;
	int _pageSize;
}
@property(assign, nonatomic) int pageSize;
@property(assign, nonatomic) int pageNum;
@property(retain, nonatomic) NSDate* endDate;
@property(retain, nonatomic) NSString* terminal;
@property(retain, nonatomic) NSString* cardNo;
-(void).cxx_destruct;
@end

