/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TFChatBoardView.h"
#import "Portal-Structs.h"
#import "TFSceneControllerDelegate.h"

@class UILabel, TFSceneController;

@interface TFChatSceneBoardView : TFChatBoardView <TFSceneControllerDelegate> {
@private
	TFSceneController* _sceneController;
	id<TFSceneControllerDelegate> _sceneControllserDelegate;
	UILabel* _sceneDescription;
}
@property(assign, nonatomic) __weak UILabel* sceneDescription;
@property(assign, nonatomic) __weak id<TFSceneControllerDelegate> sceneControllserDelegate;
@property(retain, nonatomic) TFSceneController* sceneController;
+(float)viewHeight;
-(void).cxx_destruct;
-(void)postBoardWillHideNotification:(CGRect)postBoard AnimationDuration:(float)duration;
-(void)postBoardWillShowNotification:(CGRect)postBoard AnimationDuration:(float)duration;
-(void)updateCustomSceneDescription:(id)description;
-(void)notifySceneController:(id)controller changedScene:(id)scene;
-(void)sceneController:(id)controller changedScene:(id)scene;
-(void)hideBoard;
-(void)showBoard;
-(void)resignActive:(BOOL)active;
-(void)becomeActive:(BOOL)active;
-(id)createSceneStore;
-(id)initWithChatControl:(id)chatControl;
@end

