/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSError, NSData;

@interface TFCMSRequestResult : XXUnknownSuperclass {
@private
	NSData* resultData;
	NSError* errorData;
}
@property(retain, nonatomic) NSError* errorData;
@property(retain, nonatomic) NSData* resultData;
-(void).cxx_destruct;
-(id)initWithError:(id)error;
-(id)initWithData:(id)data;
@end

