/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TFAccount.h"

@class NSString;

@interface TFMAAccount : TFAccount {
@private
	NSString* _mobileBindingType;
	NSString* _sign;
	NSString* _receiverMobile;
}
@property(copy, nonatomic) NSString* receiverMobile;
@property(copy, nonatomic) NSString* sign;
@property(copy, nonatomic) NSString* mobileBindingType;
-(void).cxx_destruct;
-(id)createToAccountRequest;
@end

