/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Portal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView, UILabel;

@interface TFNoContactView : XXUnknownSuperclass {
	int _loadRetType;
	UIImageView* _imgIndicator;
	UILabel* _labelIndicator;
@private
	NSString* indicator;
	NSString* icon;
}
@property(retain, nonatomic) NSString* icon;
@property(retain, nonatomic) NSString* indicator;
-(void).cxx_destruct;
-(void)buildLabelIndicator:(float)indicator;
-(void)indicatorWithLoadType;
-(float)buildImgIndicator;
-(void)buildNoContactView:(float)view;
-(id)initWithFrame:(CGRect)frame retType:(int)type;
@end

