/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TFTransferRecordVO.h"
#import "NSCoding.h"


@interface TFTransferRecordVOClickable : TFTransferRecordVO <NSCoding> {
@private
	BOOL _readFlag;
}
@property(assign, nonatomic) BOOL readFlag;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithRecordVO:(id)recordVO;
@end

