/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MessageCell.h"

@class UIImage, UIImageView, UIView, UILabel, TradeMessage;

@interface TradeMessageCell : MessageCell {
@private
	BOOL _iconPosition;
	UILabel* _titleLabel;
	UILabel* _amountLabel;
	UILabel* _dateLabel;
	UILabel* _statusLabel;
	UIView* _lineView;
	UIImageView* _iconImageView;
}
@property(retain, nonatomic) UIImageView* iconImageView;
@property(retain, nonatomic) UIView* lineView;
@property(retain, nonatomic) UILabel* statusLabel;
@property(retain, nonatomic) UILabel* dateLabel;
@property(retain, nonatomic) UILabel* amountLabel;
@property(retain, nonatomic) UILabel* titleLabel;
@property(readonly, assign, nonatomic) UIImage* backgroundImageHilighted;
@property(readonly, assign, nonatomic) UIImage* backgroundImage;
@property(readonly, assign, nonatomic) UIImage* iconPlaceholder;
@property(assign, nonatomic) BOOL iconPosition;
@property(readonly, assign, nonatomic) TradeMessage* tradeMessage;
+(float)cellHeightForData:(id)data ofMessage:(id)message;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)loadData:(id)data;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

