/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PBGeneratedMessage.h"

@class NSMutableArray, NSData;

@interface TrafficTile : PBGeneratedMessage {
@private
	unsigned hasVertices_ : 1;
	NSData* vertices;
	NSMutableArray* mutableTrafficSegmentList;
	NSMutableArray* mutableTrafficIncidentList;
}
@property(retain) NSMutableArray* mutableTrafficIncidentList;
@property(retain) NSMutableArray* mutableTrafficSegmentList;
@property(retain) NSData* vertices;
+(id)builderWithPrototype:(id)prototype;
+(id)builder;
+(id)parseFromCodedInputStream:(id)codedInputStream extensionRegistry:(id)registry;
+(id)parseFromCodedInputStream:(id)codedInputStream;
+(id)parseFromInputStream:(id)inputStream extensionRegistry:(id)registry;
+(id)parseFromInputStream:(id)inputStream;
+(id)parseFromData:(id)data extensionRegistry:(id)registry;
+(id)parseFromData:(id)data;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)codedOutputStream;
-(BOOL)isInitialized;
-(id)trafficIncidentAtIndex:(int)index;
-(id)trafficIncidentList;
-(id)trafficSegmentAtIndex:(int)index;
-(id)trafficSegmentList;
-(id)defaultInstance;
-(id)init;
-(void)dealloc;
-(void)setHasVertices:(BOOL)vertices;
-(BOOL)hasVertices;
@end

