/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UITextInputDelegate <NSObject>
-(void)textDidChange:(id)text;
-(void)textWillChange:(id)text;
-(void)selectionDidChange:(id)selection;
-(void)selectionWillChange:(id)selection;
@end

