/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface UTAES : XXUnknownSuperclass {
}
+(id)AES256DecryptWithKey:(id)key forKey:(id)key2;
+(id)AES256EncryptWithKey:(id)key forKey:(id)key2;
@end

