/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WXAuthInternal : XXUnknownSuperclass {
@private
	NSString* scope;
	NSString* state;
}
@property(retain, nonatomic) NSString* state;
@property(retain, nonatomic) NSString* scope;
-(void)dealloc;
-(id)init;
@end

