/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSXMLParserDelegate.h"

@class NSMutableString, NSMutableArray, NSMutableDictionary;

@interface XMLDictionaryParser : XXUnknownSuperclass <NSXMLParserDelegate> {
@private
	NSMutableDictionary* _root;
	NSMutableArray* _stack;
	NSMutableString* _text;
}
@property(retain, nonatomic) NSMutableString* text;
@property(readonly, assign, nonatomic) NSMutableDictionary* top;
@property(retain, nonatomic) NSMutableArray* stack;
@property(retain, nonatomic) NSMutableDictionary* root;
+(id)xmlStringForNode:(id)node withNodeName:(id)nodeName;
+(id)dictionaryWithXMLFile:(id)xmlfile;
+(id)dictionaryWithXMLData:(id)xmldata;
-(void).cxx_destruct;
-(void)parser:(id)parser foundComment:(id)comment;
-(void)parser:(id)parser foundCDATA:(id)cdata;
-(void)parser:(id)parser foundCharacters:(id)characters;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(id)nameForNode:(id)node inDictionary:(id)dictionary;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)addText:(id)text;
-(void)endText;
-(id)initWithXMLData:(id)xmldata;
@end

