/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XTBusinessCommonService.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XTBusinessCommonServiceImpl : XXUnknownSuperclass <XTBusinessCommonService> {
}
-(void)applicationWillEnterForeground:(id)application;
-(void)onUnBindDeviceTokenWithUserID:(id)userID;
-(void)onBindDeviceTokenWithUserID:(id)userID;
-(void)bindDeiceTokenWithUserID:(id)userID isBind:(unsigned char)bind;
-(void)startHome;
-(void)onAccountChanged;
-(void)onLoginSuccess:(id)success;
-(void)dealloc;
-(void)start;
@end

