//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapView.h"

@interface MKMapView (util)
+ (double)degreesForMeters:(int)arg1;
+ (int)metersForLocationDegrees:(double)arg1;
- (id)annotationsInRect:(CDStruct_feeb6407)arg1 originAnnotations:(id)arg2;
@end

