//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTFilterGridView.h"

@class NSMutableArray, UIImageView;

@interface MTCheckListGridView : MTFilterGridView
{
    UIImageView *_shadowImageView;
    NSMutableArray *_buttonsArray;
}

@property(retain, nonatomic) NSMutableArray *buttonsArray; // @synthesize buttonsArray=_buttonsArray;
@property(retain, nonatomic) UIImageView *shadowImageView; // @synthesize shadowImageView=_shadowImageView;
- (void).cxx_destruct;
- (void)didClickCheckListButton:(id)arg1;
- (void)setRefGridItem:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

