//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMapViewController.h"

#import "MTDropdownListViewDelegate.h"

@class MTActivityIndicatorView, MTMapDealListVC, MTMapDealService, MTMapDropdownVC, UIButton, UILabel;

@interface MTDealsMapViewController : MTMapViewController <MTDropdownListViewDelegate>
{
    CDStruct_feeb6407 _currentMapRegion;
    CDStruct_951efa70 _currentSpan;
    BOOL _isTipsShow;
    BOOL _canShowTips;
    MTMapDealService *_mapService;
    MTMapDropdownVC *_mapDropVC;
    MTMapDealListVC *_dealsListVC;
    MTActivityIndicatorView *_activityIndicatorView;
    id <MTCategory> _currentCate;
    UIButton *_locateButton;
    UIButton *_listButton;
    UIButton *_refreshButton;
    UIButton *_backButton;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) MTActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIButton *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) UIButton *listButton; // @synthesize listButton=_listButton;
@property(retain, nonatomic) UIButton *locateButton; // @synthesize locateButton=_locateButton;
@property(retain, nonatomic) id <MTCategory> currentCate; // @synthesize currentCate=_currentCate;
- (void).cxx_destruct;
- (void)dropdownListViewController:(id)arg1 selectedDropdownArray:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)showTipsLabel;
- (void)annotationSelected:(id)arg1;
- (void)didClickButtonRefresh;
- (void)didClickButtonList;
- (void)locateUser;
- (void)didClickButtonBack;
- (void)updateDataSource:(id)arg1;
- (void)reloadData;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)init;
- (id)pageParameter;

@end

