//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MTDealRecommendationParameter : NSObject
{
    BOOL _hasBought;
    long _dealID;
    int _sceneType;
    int _cate;
    int _district;
    NSString *_sort;
    int _poiID;
    int _storeID;
    double _distance;
    CDStruct_2c43369c _locationCoordinate;
}

@property(nonatomic) BOOL hasBought; // @synthesize hasBought=_hasBought;
@property(nonatomic) int storeID; // @synthesize storeID=_storeID;
@property(nonatomic) int poiID; // @synthesize poiID=_poiID;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(nonatomic) CDStruct_c3b9c2ee locationCoordinate; // @synthesize locationCoordinate=_locationCoordinate;
@property(nonatomic) NSString *sort; // @synthesize sort=_sort;
@property(nonatomic) int district; // @synthesize district=_district;
@property(nonatomic) int cate; // @synthesize cate=_cate;
@property(nonatomic) int sceneType; // @synthesize sceneType=_sceneType;
@property(nonatomic) long dealID; // @synthesize dealID=_dealID;
- (id)dictionaryForRequestParamter;

@end

