//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBaseService.h"

#import "MTCityBasedService.h"

@class MTCity, MTDealCategoryModel;

@interface MTDealCategoryService : MTBaseService <MTCityBasedService>
{
    MTDealCategoryModel *_model;
}

- (void).cxx_destruct;
- (id)categoriesOfNearbyPage;
- (void)loadCategoriesNearTo:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (id)categoriesOfHomePage;
- (void)loadCategories:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) MTCity *city;
- (id)init;

@end

