//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTGridView.h"

@class NSDictionary, UIImageView, UILabel;

@interface MTFilterGridView : MTGridView
{
    UIImageView *_separateLineView;
    UILabel *_titleLabel;
    NSDictionary *_originSelectDict;
}

@property(retain, nonatomic) NSDictionary *originSelectDict; // @synthesize originSelectDict=_originSelectDict;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *separateLineView; // @synthesize separateLineView=_separateLineView;
- (void).cxx_destruct;
- (void)setRefGridItem:(id)arg1;
- (id)init;

@end

