//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImageView;

@interface MTImageAnimationView : UIView
{
    UIImageView *_imageView;
    NSArray *_imageArray;
}

- (void).cxx_destruct;
- (BOOL)isAnimating;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setAnimationDuration:(double)arg1;
- (void)setImageArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

