//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class UILongPressGestureRecognizer;

@interface MTLabel : UILabel
{
    BOOL _menuEnabled;
    int _verticalAlignment;
    CDUnknownBlockType _didSelectCopyMenu;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
}

@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(copy, nonatomic) CDUnknownBlockType didSelectCopyMenu; // @synthesize didSelectCopyMenu=_didSelectCopyMenu;
@property(nonatomic) BOOL menuEnabled; // @synthesize menuEnabled=_menuEnabled;
@property(nonatomic) int verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
- (void).cxx_destruct;
- (void)copy:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)canBecomeFirstResponder;
- (void)didLongPressSelf:(id)arg1;
- (void)drawTextInRect:(struct CGRect)arg1;

@end

