//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBaseViewController.h"

#import "MKMapViewDelegate.h"

@class MKMapView, MTMKMapView, NSMutableArray;

@interface MTMapViewController : MTBaseViewController <MKMapViewDelegate>
{
    MTMKMapView *_mapView;
    BOOL _followUser;
    struct {
        CDStruct_feeb6407 _region;
        struct CGRect _frame;
    } _unloadSaver;
    BOOL _isInMapPage;
    NSMutableArray *_annotations;
}

@property(retain, nonatomic) NSMutableArray *annotations; // @synthesize annotations=_annotations;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (void)mapView:(id)arg1 didDeselectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)removeAllAnnotions;
- (void)showUserLocation:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (BOOL)rightSwipeEnabled;
- (void)loadView;
- (void)dealloc;

@end

