//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMapViewController.h"

@class MTMerchant, MTMerchantCorrectOriginalAnnotation, MTMerchantInfoUpdateService, UILabel;

@interface MTMerchantInfoCorrectMapViewController : MTMapViewController
{
    BOOL _canChangeBottomLabel;
    UILabel *_bottomLabel;
    MTMerchant *_merchant;
    MTMerchantInfoUpdateService *_merchantInfoUpdateService;
    MTMerchantCorrectOriginalAnnotation *_merchantAnnotation;
}

- (void).cxx_destruct;
- (void)submit;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(BOOL)arg2;
- (void)showMerchants;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithMerchant:(id)arg1;

@end

