//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTDragRefreshTableViewController.h"

#import "MTLocationManagerProtocol.h"

@class MTImageAnimationLoadingView, MTMerchantListService, NSMutableArray, NSString, SAKError;

@interface MTMerchantListViewController : MTDragRefreshTableViewController <MTLocationManagerProtocol>
{
    NSString *_currentAddress;
    SAKError *_networkError;
    BOOL _isLoadMore;
    BOOL _isResetData;
    BOOL _isRemoveAllData;
    int _totalCount;
    NSMutableArray *_merchantArray;
    BOOL _loadMoreFinished;
    BOOL _displayLowestPrice;
    BOOL _showLocationIndicator;
    BOOL _loadingData;
    NSMutableArray *_totalMerchantArray;
    MTMerchantListService *_merchantListService;
    CDUnknownBlockType _resetFilterBlock;
    MTImageAnimationLoadingView *_loadingImageView;
}

@property(nonatomic, getter=isLoadingData) BOOL loadingData; // @synthesize loadingData=_loadingData;
@property(retain, nonatomic) NSString *currentAddress; // @synthesize currentAddress=_currentAddress;
@property(retain, nonatomic) MTImageAnimationLoadingView *loadingImageView; // @synthesize loadingImageView=_loadingImageView;
@property(copy, nonatomic) CDUnknownBlockType resetFilterBlock; // @synthesize resetFilterBlock=_resetFilterBlock;
@property(nonatomic) BOOL showLocationIndicator; // @synthesize showLocationIndicator=_showLocationIndicator;
@property(nonatomic) BOOL displayLowestPrice; // @synthesize displayLowestPrice=_displayLowestPrice;
@property(nonatomic) BOOL loadMoreFinished; // @synthesize loadMoreFinished=_loadMoreFinished;
@property(retain, nonatomic) MTMerchantListService *merchantListService; // @synthesize merchantListService=_merchantListService;
@property(retain, nonatomic) NSMutableArray *totalMerchantArray; // @synthesize totalMerchantArray=_totalMerchantArray;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)processedWhenLocationFailedWithPlaceMark:(id)arg1;
- (void)didReceiveAddressUpdateNotification:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)refresh;
- (void)loadMore;
- (void)showMerchants;
- (void)resetDataList;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)didReceiveThemeChangeNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

