//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MTPurchaseInfo : NSObject
{
    BOOL _fakeRefund;
    BOOL _sevenRefund;
    BOOL _needComment;
    NSArray *_goodsList;
    int _success;
    NSString *_message;
    int _type;
    int _needSMS;
    NSString *_phoneNumberString;
    NSString *_title;
    float _price;
    int _userMin;
    int _userMax;
    int _orderMax;
    int _mobileMax;
    int _currentSales;
    int _refundType;
    int _userRemain;
    int _totalRemain;
    int _couponEndTime;
    int _free;
    int _chance;
    NSArray *_info;
    double _freight;
}

@property(retain, nonatomic) NSArray *info; // @synthesize info=_info;
@property(nonatomic) int chance; // @synthesize chance=_chance;
@property(nonatomic) int free; // @synthesize free=_free;
@property(nonatomic) double freight; // @synthesize freight=_freight;
@property(nonatomic) BOOL needComment; // @synthesize needComment=_needComment;
@property(nonatomic) BOOL sevenRefund; // @synthesize sevenRefund=_sevenRefund;
@property(nonatomic) BOOL fakeRefund; // @synthesize fakeRefund=_fakeRefund;
@property(nonatomic) int couponEndTime; // @synthesize couponEndTime=_couponEndTime;
@property(nonatomic) int totalRemain; // @synthesize totalRemain=_totalRemain;
@property(nonatomic) int userRemain; // @synthesize userRemain=_userRemain;
@property(nonatomic) int refundType; // @synthesize refundType=_refundType;
@property(nonatomic) int currentSales; // @synthesize currentSales=_currentSales;
@property(nonatomic) int mobileMax; // @synthesize mobileMax=_mobileMax;
@property(nonatomic) int orderMax; // @synthesize orderMax=_orderMax;
@property(nonatomic) int userMax; // @synthesize userMax=_userMax;
@property(nonatomic) int userMin; // @synthesize userMin=_userMin;
@property(nonatomic) float price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *phoneNumberString; // @synthesize phoneNumberString=_phoneNumberString;
@property(nonatomic) int needSMS; // @synthesize needSMS=_needSMS;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) int success; // @synthesize success=_success;
@property(retain, nonatomic) NSArray *goodsList; // @synthesize goodsList=_goodsList;
- (void).cxx_destruct;
- (BOOL)isSevenRefundEnabled;
- (BOOL)isFakeRefundEnabled;
- (BOOL)isRefundWhenExpiredEnabled;
- (BOOL)isRefundAtAnytimeEnabled;
- (int)expiration;
- (BOOL)needGotoWebPurchase;
- (BOOL)hasChance;
- (int)minQuantity;
- (int)maxQuantity;
- (BOOL)isAvailable;
- (id)initWithDictionary:(id)arg1;

@end

