//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPurchaseLabelCell.h"

@class UILabel;

@interface MTPurchaseDeliveryFeeCell : MTPurchaseLabelCell
{
    UILabel *_tipsLabel;
}

+ (id)cellWithStyle:(int)arg1;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1;

@end

