//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIScrollView;

@protocol MTRefreshProtocol <NSObject>
- (void)refreshViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(BOOL)arg2;
- (void)refreshViewDidScroll:(UIScrollView *)arg1;

@optional
- (void)endListeningToRefreshView:(UIScrollView *)arg1;
- (void)beginListeningToRefreshView:(UIScrollView *)arg1;
@end

