//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMapAnnotation.h"

@interface MTRouteAnnotation : MTMapAnnotation
{
    int _type;
}

+ (id)annotationWithLocation:(CDStruct_c3b9c2ee)arg1 type:(int)arg2 title:(id)arg3;
@property(nonatomic) int type; // @synthesize type=_type;

@end

