//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTShareGridViewCell.h"

@class MTShareButton, UILabel;

@interface MTShareItem : MTShareGridViewCell
{
    MTShareButton *_shareButton;
    UILabel *_shareLabel;
    int _shareMethod;
}

- (void).cxx_destruct;
- (id)initWithShareMethod:(int)arg1 target:(id)arg2 action:(SEL)arg3;

@end

