//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBaseViewController.h"

#import "MTShareActionSheetDelegate.h"

@class MTAutoLinearLayoutScrollView, MTOrder, NSArray, NSMutableArray;

@interface MTShareCouponOrderVC : MTBaseViewController <MTShareActionSheetDelegate>
{
    MTOrder *_order;
    NSArray *_codeArray;
    NSMutableArray *_mycouponCells;
    NSMutableArray *_addressCells;
    MTAutoLinearLayoutScrollView *_listView;
}

- (void).cxx_destruct;
- (void)didClickCell:(id)arg1;
- (id)genMessage;
- (id)payloadForShareMethod:(int)arg1;
- (void)onClickShareButton;
- (void)viewDidLoad;
- (void)setupShareUI;
- (void)loadView;
- (id)initWithOrder:(id)arg1 codeArray:(id)arg2;

@end

