//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPersistentCacheManager.h"

@class NSString;

@interface MTURLCacheManager : MTPersistentCacheManager
{
}

- (id)restoreObjectAtPath:(id)arg1 error:(id *)arg2;
- (BOOL)saveObject:(id)arg1 atPath:(id)arg2 error:(id *)arg3;
- (BOOL)canSupportObject:(id)arg1;
- (id)init;

// Remaining properties
@property(retain, nonatomic) NSString *privateCacheDirectory;
@property(retain, nonatomic) NSString *publicCacheDirectory;

@end

