//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableViewItem.h"

@interface MTVoucherTableHelpItem : MTTableViewItem
{
    id _helpTarget;
    SEL _helpAction;
}

@property(nonatomic) SEL helpAction; // @synthesize helpAction=_helpAction;
@property(nonatomic) id helpTarget; // @synthesize helpTarget=_helpTarget;
- (id)init;

@end

