//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PingUtil : NSObject
{
}

+ (id)formatSmartPixelData:(id)arg1;
+ (id)getEscapedArrayString:(id)arg1;
+ (id)getEscapedString:(id)arg1;
+ (id)getEscapedParam:(id)arg1;
+ (id)secondsSinceEpoch;
+ (id)osVersionString;
+ (id)bundleId;
+ (id)appVersionString;
+ (BOOL)hashedDeviceIdentifier:(char *)arg1;
+ (void)hashDeviceIdentifier:(id)arg1 dest:(char *)arg2;
+ (id)deviceIdentifierMD5;
+ (id)deviceIdentifierBase64;
+ (id)base64EncodeHash:(char *)arg1;
+ (id)encodeString:(id)arg1;

@end

