//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "SAKAnalyticsHeader.h"

@class NSDate, NSNumber, NSString;

@interface SAKAnalyticsHeader : NSObject <SAKAnalyticsHeader, NSCopying>
{
    NSString *appChannel;
    NSString *appSubChannel;
    NSString *appPlatForm;
    NSString *appType;
    NSString *appVersion;
    NSString *city;
    NSNumber *cityID;
    NSString *deviceID;
    NSString *deviceModel;
    NSString *idfa;
    NSString *idfv;
    NSNumber *latitude;
    NSString *launchChannel;
    NSNumber *longitude;
    NSString *macID;
    NSString *network;
    NSString *networkoperator;
    NSString *os;
    NSString *osVersion;
    NSString *pushID;
    NSNumber *residenceTime;
    NSString *screen;
    NSString *sessionID;
    NSDate *timestamp;
    NSString *userID;
    NSString *uuid;
}

+ (id)analyticsHeaderWithInitial;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID;
@property(retain, nonatomic) NSString *screen; // @synthesize screen;
@property(retain, nonatomic) NSNumber *residenceTime; // @synthesize residenceTime;
@property(retain, nonatomic) NSString *pushID; // @synthesize pushID;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion;
@property(retain, nonatomic) NSString *os; // @synthesize os;
@property(retain, nonatomic) NSString *networkoperator; // @synthesize networkoperator;
@property(retain, nonatomic) NSString *network; // @synthesize network;
@property(retain, nonatomic) NSString *macID; // @synthesize macID;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude;
@property(retain, nonatomic) NSString *launchChannel; // @synthesize launchChannel;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude;
@property(retain, nonatomic) NSString *idfv; // @synthesize idfv;
@property(retain, nonatomic) NSString *idfa; // @synthesize idfa;
@property(retain, nonatomic) NSString *deviceModel; // @synthesize deviceModel;
@property(retain, nonatomic) NSString *deviceID; // @synthesize deviceID;
@property(retain, nonatomic) NSNumber *cityID; // @synthesize cityID;
@property(retain, nonatomic) NSString *city; // @synthesize city;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion;
@property(retain, nonatomic) NSString *appType; // @synthesize appType;
@property(retain, nonatomic) NSString *appPlatForm; // @synthesize appPlatForm;
@property(retain, nonatomic) NSString *appSubChannel; // @synthesize appSubChannel;
@property(retain, nonatomic) NSString *appChannel; // @synthesize appChannel;
- (void).cxx_destruct;
- (id)dictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

