//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface UMPErrorLog : NSObject <NSCoding>
{
    NSString *stackTrace;
    NSString *time;
    NSString *page;
}

@property(retain, nonatomic) NSString *stackTrace; // @synthesize stackTrace;
@property(retain, nonatomic) NSString *time; // @synthesize time;
@property(retain, nonatomic) NSString *page; // @synthesize page;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

