//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UPNavController : UINavigationController
{
    BOOL _nowOrientating;
    BOOL _keyBoardShowwing;
}

- (void)keyboareDidHide:(id)arg1;
- (void)keyboareWillHide:(id)arg1;
- (void)keyboareDidShow:(id)arg1;
- (void)keyboareWillShow:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)dealloc;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)initWithRootViewController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

