//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

__attribute__((visibility("hidden")))
@interface BokehCtrlView : UIView <UIGestureRecognizerDelegate>
{
    struct CGPoint _bokehCenter;
    float _radius;
    float _width;
    float _angle;
    int _mode;
    int gestureCount;
    BOOL _isVisibled;
    float _bokehAlpha;
    id <BokehCtrlViewDelegate> _delegate;
}

@property(nonatomic) __weak id <BokehCtrlViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL isVisibled; // @synthesize isVisibled=_isVisibled;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (void)rotationGesture:(id)arg1;
- (void)pinchGesture:(id)arg1;
- (void)panGesture:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)setShow:(BOOL)arg1 animated:(BOOL)arg2;
- (void)addToView:(id)arg1;
- (void)adjustViewFrameForImageView:(id)arg1;
- (BOOL)appendToView:(id)arg1;
@property(nonatomic) float angle; // @synthesize angle=_angle;
@property(nonatomic) float width; // @synthesize width=_width;
@property(nonatomic) float radius; // @synthesize radius=_radius;
@property(nonatomic) struct CGPoint bokehCenter; // @synthesize bokehCenter=_bokehCenter;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)initView;

@end

