//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface BokehTool : NSObject
{
    char *_pGaussData;
    int _nGaussRadius;
    UIImage *_currentImage;
}

- (void).cxx_destruct;
- (id)bokehWithRound:(id)arg1 center:(struct CGPoint)arg2 insideRadius:(float)arg3 outsideRadius:(float)arg4;
- (id)bokehWithLine:(id)arg1 center:(struct CGPoint)arg2 insideRadius:(float)arg3 outsideRadius:(float)arg4 rotate:(float)arg5;
- (id)bokehMixing:(id)arg1 alphaImage:(id)arg2;
- (id)bokehImage:(id)arg1 withType:(BOOL)arg2 center:(struct CGPoint)arg3 radius:(float)arg4 width:(float)arg5 angle:(float)arg6;
- (void)dealloc;
- (void)clear;
- (id)initWithImage:(id)arg1;

@end

