//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString;

@interface DMAppRateRemind : NSObject <UIAlertViewDelegate>
{
    NSString *_publisherId;
}

+ (id)sharedInstanceWithPublisherId:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *publisherId; // @synthesize publisherId=_publisherId;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)checkPbRate:(id)arg1;
- (void)storeAppRateInfoInner:(id)arg1;
- (void)storeAppRateInfo:(id)arg1;
- (void)alertRateRemind:(id)arg1;
- (void)pushRateReminder;
- (void)dealloc;

@end

