//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DMWebBrowserDelegate.h"

@class DMMRAIDView, UIViewController;

@interface DMMRAIDViewBrowsingController : NSObject <DMWebBrowserDelegate>
{
    DMMRAIDView *_view;
    UIViewController *_viewControllerForPresentingModalView;
}

@property(nonatomic) UIViewController *viewControllerForPresentingModalView; // @synthesize viewControllerForPresentingModalView=_viewControllerForPresentingModalView;
- (void)dmWebBrowser:(id)arg1 shouldLoadUrl:(id)arg2;
- (void)dmWebBrowserShouldClose:(id)arg1;
- (void)dmWebBrowserWillLeaveApplication:(id)arg1;
- (void)dmWebBrowserDidCancelLoad:(id)arg1;
- (void)dmWebBrowserDidFailLoad:(id)arg1 withError:(id)arg2;
- (void)dmWebBrowserDidFinishLoad:(id)arg1;
- (void)moviePlayerDidClose;
- (void)openBrowserWithUrlString:(id)arg1 enableBack:(BOOL)arg2 enableForward:(BOOL)arg3 enableRefresh:(BOOL)arg4;
- (id)initWithAdView:(id)arg1;

@end

