//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DMFullScreenPlayerViewControllerDelegate.h"
#import "DMPlayerViewDelegate.h"

@class DMFullScreenPlayerViewController, DMPlayerView, DMVideoModel, NSString;

@interface DMNormalScreenPlayerViewController : UIViewController <DMPlayerViewDelegate, DMFullScreenPlayerViewControllerDelegate>
{
    DMPlayerView *_playerView;
    DMFullScreenPlayerViewController *_playerViewController;
    id _timeObserver;
    DMVideoModel *_videoModel;
    NSString *_str;
    BOOL _isMillisecond;
    id _delegate;
}

@property(copy, nonatomic) NSString *str; // @synthesize str=_str;
@property(retain, nonatomic) id timeObserver; // @synthesize timeObserver=_timeObserver;
@property(retain, nonatomic) DMFullScreenPlayerViewController *playerViewController; // @synthesize playerViewController=_playerViewController;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DMPlayerView *playerView; // @synthesize playerView=_playerView;
- (void)dmVideoButtonClick:(id)arg1;
- (void)videoDidEnterFullScreen;
- (void)removeTimeObserver;
- (void)syncScrubber;
- (void)addTimeObserver;
- (id)stringByCMTime:(CDStruct_1b6d18a9)arg1;
- (CDStruct_1b6d18a9)playerItemDuration;
- (void)dmPlayerButtonClick:(id)arg1;
- (BOOL)needRotateAnimationWhenExitFullScreen;
- (void)exitByUserClickButton;
- (void)trackImpReportPhaseMinimumDMPlayer:(int)arg1;
- (struct CGRect)rootVideoViewFrame;
- (void)updateCurrentButton;
- (void)exitFullScreenByFinishPlayAll:(BOOL)arg1;
- (void)fullScreenShowCloseBtn;
- (void)setIsPausedManually:(BOOL)arg1;
- (void)pauseVideo;
- (void)playVideo;
- (void)showClosebuttonAfterTime;
- (void)showControlBarImmediately;
- (void)hideControlBarImmediately;
- (void)hideControlBarAfterDelay;
- (void)videoPlayError:(id)arg1;
- (void)videoDidEndAll:(id)arg1;
- (void)videoResumeToPlay;
- (void)videoDidPause;
- (void)videoDidPlay;
- (void)videoLoadFinished;
- (BOOL)shouldPlayIn2GOr3G;
- (void)reportImpProgressWithTimeFromFullScreen:(int)arg1;
- (BOOL)isPausedManually;
- (BOOL)isFullScreen;
- (BOOL)isPause;
- (void)stopVideo;
- (BOOL)isPlaying;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithVideoModel:(id)arg1 delegate:(id)arg2 andBundleName:(id)arg3 andMillisecond:(BOOL)arg4;

@end

