//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "EffectItemViewDelegate.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface EffectScrollView : UIScrollView <EffectItemViewDelegate>
{
    NSArray *effectList;
    id <EffectItemViewDelegate> _effectDelegate;
}

@property(nonatomic) __weak id <EffectItemViewDelegate> effectDelegate; // @synthesize effectDelegate=_effectDelegate;
- (void).cxx_destruct;
- (void)effectItemViewWasTapped:(id)arg1;
- (void)setEffectIndex:(int)arg1;
- (void)loadList:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

