//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface EffectItemView : UIView
{
    BOOL selected;
    UILabel *nameLabel;
    UIImageView *iconView;
    UIImageView *highlightBg;
    id <EffectItemViewDelegate> _delegate;
    NSDictionary *_itemDic;
}

@property(retain, nonatomic) NSDictionary *itemDic; // @synthesize itemDic=_itemDic;
@property(nonatomic) __weak id <EffectItemViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setSelected:(BOOL)arg1;
- (id)initWithItem:(id)arg1;

@end

