//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TouchScrollViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class TouchScrollView, UIPageControl;

__attribute__((visibility("hidden")))
@interface FaceViewVC : UIViewController <UIScrollViewDelegate, TouchScrollViewDelegate>
{
    TouchScrollView *scrollView;
    UIPageControl *pageControl;
    BOOL pageControlUsed;
    int pageLoaded[10];
    id <FaceViewVCDelegate> _delegate;
}

@property(nonatomic) __weak id <FaceViewVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)selectIndex:(int)arg1;
- (void)changePage:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)loadScrollViewWithPage:(int)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)initState;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

