//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBDialogsParams.h"

@class NSArray, NSString, NSURL;

@interface FBShareDialogParams : FBDialogsParams
{
    BOOL _dataFailuresFatal;
    NSURL *_link;
    NSString *_name;
    NSString *_caption;
    NSString *_description;
    NSURL *_picture;
    NSArray *_friends;
    id _place;
    NSString *_ref;
}

@property(nonatomic) BOOL dataFailuresFatal; // @synthesize dataFailuresFatal=_dataFailuresFatal;
@property(copy, nonatomic) NSString *ref; // @synthesize ref=_ref;
@property(copy, nonatomic) id place; // @synthesize place=_place;
@property(copy, nonatomic) NSArray *friends; // @synthesize friends=_friends;
@property(copy, nonatomic) NSURL *picture; // @synthesize picture=_picture;
@property(copy, nonatomic) NSString *description; // @synthesize description=_description;
@property(copy, nonatomic) NSString *caption; // @synthesize caption=_caption;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSURL *link; // @synthesize link=_link;
- (id)appBridgeVersion;
- (BOOL)isSupportedScheme:(id)arg1;
- (id)dictionaryMethodArgs;
- (void)dealloc;

@end

