//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVCaptureDevice, UIButton, UIImageView;

__attribute__((visibility("hidden")))
@interface FlashStateControl : UIView
{
    int currentOrientation;
    AVCaptureDevice *device;
    BOOL bShow;
    UIView *listView;
    UIButton *flashClose;
    UIButton *flashAuto;
    UIButton *flashOn;
    UIButton *flashTorchOn;
    UIImageView *backgroundView;
    struct CGRect _originalFrame;
    struct CGRect _stateButtonOriginalFrame;
    BOOL _bIgnoreRotate;
    id <FlashStateControlDelegate> _delegate;
    UIButton *_stateBtn;
}

@property(nonatomic) BOOL bIgnoreRotate; // @synthesize bIgnoreRotate=_bIgnoreRotate;
@property(nonatomic) __weak UIButton *stateBtn; // @synthesize stateBtn=_stateBtn;
@property(nonatomic) __weak id <FlashStateControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateStateBtn;
- (void)updateView;
- (void)updateRotation;
- (void)torchOn:(id)arg1;
- (void)flashOn:(id)arg1;
- (void)flashAuto:(id)arg1;
- (void)flashOff:(id)arg1;
- (void)showListView:(id)arg1;
- (void)closeFlashIfNeed;
- (void)setListShowed:(BOOL)arg1;
@property(readonly, nonatomic) BOOL listShow;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initView;

@end

