//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageFilter.h"

@interface GPUImageSphereRefractionFilter : GPUImageFilter
{
    int radiusUniform;
    int centerUniform;
    int aspectRatioUniform;
    int refractiveIndexUniform;
    float _radius;
    float _aspectRatio;
    float _refractiveIndex;
    struct CGPoint _center;
}

@property(nonatomic) float refractiveIndex; // @synthesize refractiveIndex=_refractiveIndex;
@property(nonatomic) float aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(nonatomic) float radius; // @synthesize radius=_radius;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
- (void)forceProcessingAtSize:(struct CGSize)arg1;
- (void)setInputRotation:(int)arg1 atIndex:(int)arg2;
- (void)adjustAspectRatio;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(int)arg2;
- (id)initWithFragmentShaderFromString:(id)arg1;
- (id)init;

@end

