//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface ImageMath : NSObject
{
}

+ (double)getRatFromSize:(struct CGSize)arg1 ByAngle:(double)arg2;
+ (struct CGSize)getSizeFromSize:(struct CGSize)arg1 ByAngle:(double)arg2;
+ (struct CGPoint)pointChange:(struct CGPoint)arg1 withCenterPoint:(struct CGPoint)arg2 rotate:(float)arg3;
+ (int)calcGaussLenWithImageSize:(struct CGSize)arg1 baseRadius:(int)arg2;

@end

