//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NRGridViewCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface MTMaterialGridViewCell : NRGridViewCell
{
    BOOL _selectionImageViewSizeToFit;
    UIImageView *_selectedImageView;
    UIImageView *_markNewFlag;
    struct CGSize _imageViewSize;
    struct CGPoint _markNewFlagOffset;
}

@property(nonatomic) BOOL selectionImageViewSizeToFit; // @synthesize selectionImageViewSizeToFit=_selectionImageViewSizeToFit;
@property(nonatomic) struct CGPoint markNewFlagOffset; // @synthesize markNewFlagOffset=_markNewFlagOffset;
@property(nonatomic) struct CGSize imageViewSize; // @synthesize imageViewSize=_imageViewSize;
@property(readonly, nonatomic) UIImageView *markNewFlag; // @synthesize markNewFlag=_markNewFlag;
@property(readonly, nonatomic) UIImageView *selectedImageView; // @synthesize selectedImageView=_selectedImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)didMoveToSuperview;
- (id)initWithReuseIdentifier:(id)arg1;

@end

