//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface MTMiniApp : NSObject
{
    BOOL _isNeedFaceDetector;
    NSString *_appID;
    NSString *_appFolder;
    NSString *_appTitle;
    NSString *_uploadImageURLStr;
    NSString *_appHomeIconURLStr;
    NSDictionary *_info;
}

@property(retain, nonatomic) NSDictionary *info; // @synthesize info=_info;
@property(retain, nonatomic) NSString *appHomeIconURLStr; // @synthesize appHomeIconURLStr=_appHomeIconURLStr;
@property(retain, nonatomic) NSString *uploadImageURLStr; // @synthesize uploadImageURLStr=_uploadImageURLStr;
@property(nonatomic) BOOL isNeedFaceDetector; // @synthesize isNeedFaceDetector=_isNeedFaceDetector;
@property(copy, nonatomic) NSString *appTitle; // @synthesize appTitle=_appTitle;
@property(retain, nonatomic) NSString *appFolder; // @synthesize appFolder=_appFolder;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (BOOL)refreshResultJSFile:(id)arg1 isForece:(BOOL)arg2;
- (BOOL)refreshLoadingJSFile:(id)arg1 isForce:(BOOL)arg2;
@property(readonly, nonatomic) NSString *resultJSFilePath;
@property(readonly, nonatomic) NSString *loadingJSFilePath;
@property(readonly, nonatomic) NSURL *resultPageURL;
@property(readonly, nonatomic) NSURL *loadPageURL;
@property(readonly, nonatomic) NSURL *mainPageURL;
- (id)initWith:(id)arg1;

@end

