//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

#import "PickerControlViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSMutableArray, PickerControlView;

__attribute__((visibility("hidden")))
@interface MTMultipleImagePickerController : UIImagePickerController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, PickerControlViewDelegate>
{
    PickerControlView *_pickerControlView;
    BOOL _showHomeBarButtonItem;
    NSMutableArray *_images;
    unsigned int _minimumPickingImageCount;
    unsigned int _maximumPickingImageCount;
    id <MTMultipleImagePickerControllerDelegate> _multipleImagePickerdelegate;
}

@property(nonatomic) __weak id <MTMultipleImagePickerControllerDelegate> multipleImagePickerdelegate; // @synthesize multipleImagePickerdelegate=_multipleImagePickerdelegate;
@property(nonatomic) unsigned int maximumPickingImageCount; // @synthesize maximumPickingImageCount=_maximumPickingImageCount;
@property(nonatomic) unsigned int minimumPickingImageCount; // @synthesize minimumPickingImageCount=_minimumPickingImageCount;
@property(nonatomic) BOOL showHomeBarButtonItem; // @synthesize showHomeBarButtonItem=_showHomeBarButtonItem;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
- (void).cxx_destruct;
- (void)actionCancel:(id)arg1;
- (void)actionHome:(id)arg1;
- (void)back:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)startPuzzleWithPickerControlView:(id)arg1;
- (id)pickerControlViewImageCountLabelText;
- (void)pickerControlView:(id)arg1 deleteImageAtIndex:(unsigned int)arg2;
- (id)pickerControlView;
- (void)pickerControlViewDidFinishPicking;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

@end

