//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "UIGestureRecognizerDelegate.h"

@class OneFingerGestureRecognizer, UIButton, UIView;

__attribute__((visibility("hidden")))
@interface MTPuzzleFreeImageView : UIImageView <UIGestureRecognizerDelegate>
{
    UIView *_borderView;
    OneFingerGestureRecognizer *_oneFingerGesture;
    BOOL _oneFingerGestureEnabled;
    UIButton *_fingerButton;
    int _index;
}

@property(nonatomic) BOOL oneFingerGestureEnabled; // @synthesize oneFingerGestureEnabled=_oneFingerGestureEnabled;
@property(nonatomic) int index; // @synthesize index=_index;
@property(readonly, nonatomic) UIButton *fingerButton; // @synthesize fingerButton=_fingerButton;
- (void).cxx_destruct;
- (void)adjustsFingerButtonFrame;
- (void)actionRotate:(id)arg1;
- (void)actionOneFingerRotating:(id)arg1;
- (void)actionScale:(id)arg1;
- (void)actionPan:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)adjustAnchorPointForGestureRecognizer:(id)arg1;
- (void)actionTouch:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

