//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTAlertViewDelegate.h"
#import "MTPushAndUpdateRequestDeleage.h"

@class MTPushAndUpdateRequest, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface MTPushAndUpdateController : NSObject <MTAlertViewDelegate, MTPushAndUpdateRequestDeleage>
{
    BOOL _isShowingPushInfo;
    BOOL _isPushOrHomeUpdateShowed;
    id <MTPushAndUpdateDeleage> _delegate;
    MTPushAndUpdateRequest *_request;
    MTPushAndUpdateRequest *_versionUpdateRequest;
    float _checkPeriod;
    NSArray *_pushInfoArray;
    NSMutableArray *_showedPushInfoIDArray;
    NSDictionary *_currentSingleInfoDic;
    NSString *_jumpUrl;
    int _openUrlMode;
    NSDate *_lastCheckDate;
    int _alertType;
    NSString *_serverUrlStr;
    NSMutableDictionary *_updateAndPushRecordInfo;
}

+ (id)shareController;
@property(retain, nonatomic) NSMutableDictionary *updateAndPushRecordInfo; // @synthesize updateAndPushRecordInfo=_updateAndPushRecordInfo;
@property(copy, nonatomic) NSString *serverUrlStr; // @synthesize serverUrlStr=_serverUrlStr;
@property(nonatomic) int alertType; // @synthesize alertType=_alertType;
@property(nonatomic) int openUrlMode; // @synthesize openUrlMode=_openUrlMode;
@property(copy, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(retain, nonatomic) NSDictionary *currentSingleInfoDic; // @synthesize currentSingleInfoDic=_currentSingleInfoDic;
@property(retain, nonatomic) NSMutableArray *showedPushInfoIDArray; // @synthesize showedPushInfoIDArray=_showedPushInfoIDArray;
@property(retain, nonatomic) NSArray *pushInfoArray; // @synthesize pushInfoArray=_pushInfoArray;
@property(nonatomic) float checkPeriod; // @synthesize checkPeriod=_checkPeriod;
@property(retain, nonatomic) MTPushAndUpdateRequest *versionUpdateRequest; // @synthesize versionUpdateRequest=_versionUpdateRequest;
@property(retain, nonatomic) MTPushAndUpdateRequest *request; // @synthesize request=_request;
@property(nonatomic) __weak id <MTPushAndUpdateDeleage> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)saveShareDefaultTopic:(id)arg1;
- (void)checkVersionUpateFailed:(id)arg1;
- (void)checkVersionUpateFinished:(id)arg1;
- (void)checkAllFailed:(id)arg1;
- (void)checkAllFinished:(id)arg1;
- (id)lastShowUpdateInfoVersion;
- (void)setLastShowUpdateInfoVersion:(id)arg1;
@property(retain, nonatomic) NSDate *lastCheckDate; // @synthesize lastCheckDate=_lastCheckDate;
- (void)showBlindAppInfoWithAlertIfNeed;
- (void)showVersionUpdateInfo:(id)arg1;
- (void)recordPushInfoID:(int)arg1;
- (void)restoreshowedPushInfoIDArray;
- (id)pushInfoDicWithID:(int)arg1;
- (void)showPushInfo:(id)arg1;
- (BOOL)isExistNewPushInfoNeedToShowInPushInfoArray;
- (BOOL)judgeNeedToShow:(id)arg1;
- (BOOL)isShowingPushInfo;
- (void)showUpdateInfoWithAlert;
- (void)showLatestPushInfoWithAlertView;
- (BOOL)isExistSavedInfoNeedToShowThenShow;
- (void)saveCurrentInfo:(int)arg1;
- (void)canceledVersionUpdateChecks;
- (void)checkVersionUpdate;
- (void)checkAllIfNeed;
- (BOOL)isNeedToCheck;
- (BOOL)newVersionFlagShowState;
- (void)setNewVersionFlagShowState:(BOOL)arg1;
- (void)setAppName:(int)arg1;
- (id)init;

@end

