//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Toolbar)
- (id)addKeyboard:(BOOL)arg1 previous:(SEL)arg2 nextSelector:(SEL)arg3 doneSelector:(SEL)arg4;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)setInputAccessoryView:(id)arg1;
@end

