//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface UMANEkv : NSObject
{
    double ts;
    int du;
    NSString *_id;
    NSString *_key;
    NSMutableDictionary *_values;
}

@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
@property(nonatomic) int du; // @synthesize du;
@property(nonatomic) double ts; // @synthesize ts;
- (id)description;
- (id)attributes;
- (void)updateDu;
- (id)initWithId:(id)arg1 key:(id)arg2 values:(id)arg3;
- (void)dealloc;

@end

