//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSOperationQueue;

@interface UMUFPCache : NSObject
{
    NSMutableDictionary *_cacheDictionary;
    double defaultTimeoutInterval;
    NSOperationQueue *diskOperationQueue;
}

+ (id)currentCache;
@property(retain) NSMutableDictionary *cacheDictionary; // @synthesize cacheDictionary=_cacheDictionary;
@property(nonatomic) double defaultTimeoutInterval; // @synthesize defaultTimeoutInterval;
- (void)dealloc;
- (void)performDiskWriteOperation:(id)arg1;
- (id)imageForKey:(id)arg1;
- (void)setDicWithKey:(id)arg1 andValue:(id)arg2;
- (id)getDicForKey:(id)arg1;
- (id)filePathForUrl:(id)arg1;
- (void)deleteDataAtPath:(id)arg1;
- (void)writeData:(id)arg1 toPath:(id)arg2;
- (void)deleteStringForKey:(id)arg1;
- (void)setString:(id)arg1 forKey:(id)arg2 withTimeoutInterval:(double)arg3;
- (id)stringForKey:(id)arg1;
- (id)dataForKey:(id)arg1;
- (void)setData:(id)arg1 forKey:(id)arg2 withTimeoutInterval:(double)arg3;
- (void)saveCacheDictionary;
- (void)saveAfterDelay;
- (void)updateCache;
- (BOOL)hasCacheForKey:(id)arg1;
- (void)removeItemFromCache:(id)arg1;
- (void)removeCacheForKey:(id)arg1;
- (void)clearCache;
- (id)init;

@end

