//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableData;

__attribute__((visibility("hidden")))
@interface AsyncReadPacket : NSObject
{
    NSMutableData *buffer;
    long bytesDone;
    double timeout;
    long maxLength;
    long tag;
    NSData *term;
    BOOL readAllAvailableData;
}

- (void)dealloc;
- (long)searchForTermAfterPreBuffering:(long)arg1;
- (unsigned int)prebufferReadLengthForTerm;
- (unsigned int)readLengthForTerm;
- (id)initWithData:(id)arg1 timeout:(double)arg2 tag:(long)arg3 readAllAvailable:(BOOL)arg4 terminator:(id)arg5 maxLength:(long)arg6;

@end

