//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class EDAMNoteFilter, NSString;

@interface EDAMfindNotes_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    EDAMNoteFilter *__filter;
    int __offset;
    int __maxNotes;
    BOOL __authenticationToken_isset;
    BOOL __filter_isset;
    BOOL __offset_isset;
    BOOL __maxNotes_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetMaxNotes;
- (BOOL)maxNotesIsSet;
@property(nonatomic, getter=maxNotes, setter=setMaxNotes:) int maxNotes; // @dynamic maxNotes;
- (void)unsetOffset;
- (BOOL)offsetIsSet;
@property(nonatomic, getter=offset, setter=setOffset:) int offset; // @dynamic offset;
- (void)unsetFilter;
- (BOOL)filterIsSet;
@property(retain, nonatomic, getter=filter, setter=setFilter:) EDAMNoteFilter *filter; // @dynamic filter;
- (void)unsetAuthenticationToken;
- (BOOL)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken; // @dynamic authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 filter:(id)arg2 offset:(int)arg3 maxNotes:(int)arg4;

@end

