//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADAd, GADAdFetcher, GADRequestError, NSArray, NSDictionary, NSString;

@protocol GADAdFetcherDelegate <NSObject>
- (void)adFetcher:(GADAdFetcher *)arg1 didFailToFetchAdWithError:(GADRequestError *)arg2;
- (void)adFetcher:(GADAdFetcher *)arg1 didFetchAd:(GADAd *)arg2;
- (void)setScrollEnabled:(BOOL)arg1;
- (void)setNewAdSize:(struct CGSize)arg1;
- (void)setAdDebugDialog:(NSString *)arg1;
- (BOOL)isMediating;
- (void)setIsMediating:(BOOL)arg1;
- (void)setRefreshInterval:(double)arg1;
- (void)setRequestedOrientation:(int)arg1;
- (void)addSwipeToViewControllerConfigurations:(NSDictionary *)arg1;
- (void)addActiveViewConfigurations:(NSDictionary *)arg1;
- (void)addManualTrackingURLs:(NSArray *)arg1;
- (void)addTrackingURLs:(NSArray *)arg1;
- (void)addClickTrackingURLs:(NSArray *)arg1;
@end

