//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADSlotDelegate.h"

@class GADRequest, GADSlot, GADWebAppViewController, NSString;

__attribute__((visibility("hidden")))
@interface GADInterstitial : NSObject <GADSlotDelegate>
{
    BOOL _hasBeenUsed;
    GADRequest *_request;
    GADWebAppViewController *_viewController;
    GADSlot *_slot;
}

@property(retain, nonatomic) GADSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) GADWebAppViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) GADRequest *request; // @synthesize request=_request;
@property(nonatomic) BOOL hasBeenUsed; // @synthesize hasBeenUsed=_hasBeenUsed;
- (void).cxx_destruct;
- (void)loadAndDisplayRequest:(id)arg1 usingWindow:(id)arg2 initialImage:(id)arg3;
- (void)presentFromRootViewController:(id)arg1;
@property(readonly, nonatomic) BOOL isReady;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName;
- (void)loadRequest:(id)arg1;
- (void)sendInterstitialUsageError;
- (BOOL)slotShouldReloadCurrentRequest:(id)arg1;
@property(nonatomic) __weak id <GADInAppPurchaseDelegate> inAppPurchaseDelegate;
@property(nonatomic) __weak id <GADInterstitialDelegate> delegate;
@property(copy, nonatomic) NSString *adUnitID;
- (void)dealloc;
- (id)init;
- (void)webAction:(id)arg1;
- (void)sendInterstitialError:(id)arg1;
- (id)privateRequest;
- (void)cancel;

@end

