//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GADMRAIDInterceptor : NSURLProtocol
{
    NSString *_mraidLocationToLoad;
}

+ (void)resetCanInitWithRequestCounter;
+ (void)resetToDefaultPaths;
+ (BOOL)isAllowed;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (BOOL)canInitWithRequest:(id)arg1;
+ (BOOL)shouldRedirectForMRAID:(id)arg1;
+ (id)refererURLFromRequest:(id)arg1;
+ (id)expandedBannerImplementationPath;
+ (void)setExpandedBannerImplementationPath:(id)arg1;
+ (id)interstitialImplementationPath;
+ (void)setInterstitialImplementationPath:(id)arg1;
+ (id)bannerImplementationPath;
+ (void)setBannerImplementationPath:(id)arg1;
+ (void)updateImplementationsPaths;
+ (BOOL)urlIsAnImplementationPath:(id)arg1;
+ (void)initialize;
+ (void)allow;
+ (void)disallow;
+ (BOOL)canInitWithRequestIsEnabled;
+ (void)disableCanInitWithRequest;
+ (void)enableCanInitWithRequest;
+ (id)classLock;
@property(copy, nonatomic) NSString *mraidLocationToLoad; // @synthesize mraidLocationToLoad=_mraidLocationToLoad;
- (void).cxx_destruct;
- (void)stopLoading;
- (void)startLoading;
- (id)initWithRequest:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;

@end

