//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSLock, NSMutableDictionary, NSString, NSUserDefaults;

__attribute__((visibility("hidden")))
@interface GADStatisticsCore : NSObject
{
    NSMutableDictionary *_statistics;
    NSString *_identifier;
    NSUserDefaults *_userDefaults;
    NSArray *_transientStats;
    NSString *_userDefaultsKey;
    NSLock *_lock;
}

@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(copy, nonatomic) NSString *userDefaultsKey; // @synthesize userDefaultsKey=_userDefaultsKey;
@property(retain, nonatomic) NSArray *transientStats; // @synthesize transientStats=_transientStats;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)appendValue:(id)arg1 arrayForKey:(id)arg2;
- (int)addValue:(int)arg1 numberForKey:(id)arg2;
- (id)dictionaryForKey:(id)arg1;
- (id)arrayForKey:(id)arg1;
- (id)dateForKey:(id)arg1;
- (id)numberForKey:(id)arg1;
- (id)stringForKey:(id)arg1;
- (void)setDictionary:(id)arg1 forKey:(id)arg2;
- (void)setArray:(id)arg1 forKey:(id)arg2;
- (void)setDate:(id)arg1 forKey:(id)arg2;
- (void)setNumber:(id)arg1 forKey:(id)arg2;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (void)synchronize;
- (void)dealloc;
- (id)init;
- (void)setObject:(id)arg1 forKey:(id)arg2 matchingClass:(Class)arg3;
- (void)savePersistentStatistics;
- (void)loadPersistentStatistics;

@end

