//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GCKMediaControlChannel, NSError;

@protocol GCKMediaControlChannelDelegate <NSObject>

@optional
- (void)mediaControlChannel:(GCKMediaControlChannel *)arg1 requestDidFailWithID:(int)arg2 error:(NSError *)arg3;
- (void)mediaControlChannel:(GCKMediaControlChannel *)arg1 requestDidCompleteWithID:(int)arg2;
- (void)mediaControlChannelDidUpdateMetadata:(GCKMediaControlChannel *)arg1;
- (void)mediaControlChannelDidUpdateStatus:(GCKMediaControlChannel *)arg1;
- (void)mediaControlChannel:(GCKMediaControlChannel *)arg1 didFailToLoadMediaWithError:(NSError *)arg2;
- (void)mediaControlChannel:(GCKMediaControlChannel *)arg1 didCompleteLoadWithSessionID:(int)arg2;
@end

