//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (GCKTypedValueLookup)
- (void)gck_setBoolValue:(BOOL)arg1 forKey:(id)arg2;
- (void)gck_setDoubleValue:(double)arg1 forKey:(id)arg2;
- (void)gck_setUIntegerValue:(unsigned int)arg1 forKey:(id)arg2;
- (void)gck_setIntegerValue:(int)arg1 forKey:(id)arg2;
- (void)gck_setStringValue:(id)arg1 forKey:(id)arg2;
- (id)gck_arrayForKey:(id)arg1;
- (id)gck_dictionaryForKey:(id)arg1;
- (BOOL)gck_boolForKey:(id)arg1;
- (BOOL)gck_boolForKey:(id)arg1 withDefaultValue:(BOOL)arg2;
- (double)gck_doubleForKey:(id)arg1;
- (double)gck_doubleForKey:(id)arg1 withDefaultValue:(double)arg2;
- (unsigned int)gck_uintegerForKey:(id)arg1;
- (int)gck_integerForKey:(id)arg1;
- (unsigned int)gck_uintegerForKey:(id)arg1 withDefaultValue:(unsigned int)arg2;
- (int)gck_integerForKey:(id)arg1 withDefaultValue:(int)arg2;
- (id)gck_stringForKey:(id)arg1;
- (id)gck_stringForKey:(id)arg1 withDefaultValue:(id)arg2;
@end

