//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTListDataSource.h"

@class NSString, OSFeedGenreMode;

__attribute__((visibility("hidden")))
@interface OSFeedGenreDataSource : TTListDataSource
{
    NSString *_superGenre;
    OSFeedGenreMode *_feedGenreMode;
}

- (BOOL)reloadButtonForEmpty;
- (id)titleForError:(id)arg1;
- (id)subtitleForError:(id)arg1;
- (id)titleForEmpty;
- (id)titleForLoading:(BOOL)arg1;
- (void)tableViewDidLoadModel:(id)arg1;
- (id)model;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)dealloc;
- (id)initWithSuperGenre:(id)arg1;

@end

