//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "SHKFormFieldCellDelegate.h"
#import "SHKFormOptionControllerClient.h"

@class NSMutableArray, NSString, UITextField;

@interface SHKFormController : UITableViewController <SHKFormFieldCellDelegate, SHKFormOptionControllerClient>
{
    BOOL autoSelect;
    id delegate;
    SEL validateSelector;
    SEL saveSelector;
    SEL cancelSelector;
    NSMutableArray *sections;
    UITextField *activeField;
}

@property BOOL autoSelect; // @synthesize autoSelect;
@property(retain, nonatomic) UITextField *activeField; // @synthesize activeField;
@property(retain) NSMutableArray *sections; // @synthesize sections;
@property SEL cancelSelector; // @synthesize cancelSelector;
@property SEL saveSelector; // @synthesize saveSelector;
@property SEL validateSelector; // @synthesize validateSelector;
@property id delegate; // @synthesize delegate;
- (id)formValuesForSection:(int)arg1;
- (id)formValues;
- (void)saveForm;
- (void)validateForm;
- (void)cancel;
- (void)close;
- (void)SHKFormOptionControllerDidFinish:(id)arg1;
- (void)setActiveTextField:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)rowSettingsForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)addSection:(id)arg1 header:(id)arg2 footer:(id)arg3;
- (id)initWithStyle:(int)arg1 title:(id)arg2 rightButtonTitle:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

