//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface TTCSSParser : NSObject
{
    NSMutableDictionary *_ruleSets;
    NSMutableArray *_activeCssSelectors;
    NSMutableDictionary *_activeRuleSet;
    NSString *_activePropertyName;
    NSString *_lastTokenText;
    int _lastToken;
    union {
        struct {
            unsigned int InsideDefinition:1;
            unsigned int InsideProperty:1;
            unsigned int InsideFunction:1;
        } Flags;
        int _data;
    } _state;
}

- (id)parseFilename:(id)arg1;
- (void)consumeToken:(int)arg1 text:(char *)arg2;
- (void)dealloc;
- (id)init;

@end

