//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TTMessageField : NSObject
{
    NSString *_title;
    BOOL _required;
}

@property(nonatomic) BOOL required; // @synthesize required=_required;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)restoreField:(id)arg1 withData:(id)arg2;
- (id)persistField:(id)arg1;
- (id)createViewForController:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 required:(BOOL)arg2;

@end

