//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTStyle.h"

@class UIColor;

@interface TTShadowStyle : TTStyle
{
    UIColor *_color;
    float _blur;
    struct CGSize _offset;
}

+ (id)styleWithColor:(id)arg1 blur:(float)arg2 offset:(struct CGSize)arg3 next:(id)arg4;
+ (id)styleWithCssSelector:(id)arg1 next:(id)arg2;
+ (id)styleWithCssSelector:(id)arg1 forState:(unsigned int)arg2 next:(id)arg3;
@property(nonatomic) struct CGSize offset; // @synthesize offset=_offset;
@property(nonatomic) float blur; // @synthesize blur=_blur;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (struct CGSize)addToSize:(struct CGSize)arg1 context:(id)arg2;
- (void)draw:(id)arg1;
- (void)dealloc;
- (id)initWithNext:(id)arg1;

@end

