//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface MemoryManager : NSObject
{
    NSMutableArray *_list;
}

+ (id)sharedInstance;
- (void)addMonitorObject:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)removeMemoryNotification;
- (void)registerMemoryNotification;
- (void)lowMemory:(id)arg1;

@end

