//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBBulletin, NSDictionary, NSString, NSURL, SBAlertItem, SBAwayViewPluginController, UIView;

@protocol SBUIUserAgent <NSObject>
- (void)setMinimumBacklightLevel:(float)arg1 animated:(BOOL)arg2;
- (void)notifyOnNextUserEvent;
- (BOOL)isSBUILoggingEnabled;
- (void)removeActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)addActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)activateModalBulletinAlert:(SBAlertItem *)arg1;
- (id <SBBulletinAlertHandlerRegistry>)modalBulletinAlertHandlerRegistry;
- (BOOL)launchDisplayWithURL:(NSURL *)arg1 forCall:(BOOL)arg2 sender:(id)arg3;
- (void)setFlipBackAttributeForSEODisplayWithIdentifier:(NSString *)arg1;
- (void)prepareToAnswerCall;
- (void)stopRinging;
- (void)playRingtoneAtPath:(NSString *)arg1 vibrationPattern:(NSDictionary *)arg2;
- (void)playRingtoneAtPath:(NSString *)arg1;
- (void)setBadgeNumberOrString:(id)arg1 forApplicationWithID:(NSString *)arg2;
- (void)setIdleText:(NSString *)arg1;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(BOOL)arg1;
- (void)lockAndDimDevice;
- (BOOL)isIdleTimerDisabledForReason:(NSString *)arg1;
- (void)setIdleTimerDisabled:(BOOL)arg1 forReason:(NSString *)arg2;
- (void)undimScreen;
- (void)dimScreen:(BOOL)arg1;
- (void)updateLockScreenInterfaceIfNecessary;
- (struct CGRect)defaultContentRegionForAwayViewPlugin:(SBAwayViewPluginController *)arg1 withOrientation:(int)arg2;
- (BOOL)launchFromAwayViewPluginWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2 allowUnlock:(BOOL)arg3 animate:(BOOL)arg4;
- (BOOL)canLaunchFromAwayViewPluginWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2;
- (BOOL)launchFromSource:(int)arg1 withURL:(NSURL *)arg2 bundleID:(NSString *)arg3 allowUnlock:(BOOL)arg4;
- (BOOL)launchFromPushOrLocalBulletin:(BBBulletin *)arg1 origin:(int)arg2;
- (BOOL)launchFromBulletinWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2 allowUnlock:(BOOL)arg3 animate:(BOOL)arg4 launchOrigin:(int)arg5;
- (BOOL)canLaunchFromBulletinWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2;
- (BOOL)launchApplicationFromSource:(int)arg1 withURL:(NSURL *)arg2 options:(NSDictionary *)arg3;
- (BOOL)launchApplicationFromSource:(int)arg1 withDisplayID:(NSString *)arg2 options:(NSDictionary *)arg3;
- (BOOL)canLaunchFromSource:(int)arg1 withURL:(NSURL *)arg2 bundleID:(NSString *)arg3;
- (void)openURL:(NSURL *)arg1 animateIn:(BOOL)arg2 scale:(float)arg3 start:(double)arg4 duration:(float)arg5 animateOut:(BOOL)arg6;
- (BOOL)openURL:(NSURL *)arg1 allowUnlock:(BOOL)arg2 animated:(BOOL)arg3;
- (BOOL)canUserLaunchIcon;
- (BOOL)alertIsActive;
- (BOOL)springBoardIsActive;
- (UIView *)createWallpaperView:(int)arg1;
- (BOOL)homeScreenIsDisplayingWallpaper;
- (int)networkUsageTypeForAppWithDisplayID:(NSString *)arg1;
- (BOOL)lockScreenIsShowing;
- (BOOL)deviceIsTethered;
- (BOOL)deviceIsBlocked;
- (BOOL)deviceIsPasscodeLockedRemotely;
- (BOOL)deviceIsPasscodeLocked;
- (BOOL)deviceIsLocked;
- (BOOL)applicationInstalledForDisplayID:(NSString *)arg1;
- (NSString *)topSuspendedEventsOnlyDisplayID;
- (NSString *)foregroundDisplayID;
- (NSString *)foregroundApplicationDisplayID;
- (int)activeInterfaceOrientation;
- (void)updateInterfaceOrientationIfNecessary;
@end

